### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#101]
We need a theme like this

![image](https://user-images.githubusercontent.com/35181396/39080889-24831244-44ec-11e8-90be-35e07e80948e.png)

**Comment by hydrogenpi** [comment]
I just want the board and the stones to match, that is all.

**Comment by featurecat** [comment]
here you go: https://github.com/3kakakhel/sabaki-wgojs-theme

just copy whatever wood backgrounds and stones as you would like and overwrite the files in the assets directory.
