### ISSUE TITLE
Winrate graph drawing wrong data when in variation

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#102]
I'm moving this out from #64 so I can write a little more without cluttering it up. This is part of number 7 on that checklist.

Currently, the winrate graph tries a little to be aware of the current variation (e.g., how long it is), but when it comes to drawing the lines it just uses the main trunk of the game tree. This causes incorrect data to be displayed, plus the data can extend over the board because its horizontal scaling is based on the variation's game length.

The simple way to fix this is

1. Fast-forward to the end of the current branch and get its last move number, for correct x-scaling (as is currently done)
2. Go backwards from that end node to the beginning, drawing the graph from right to left, instead of rewinding to the root and having to try to remember which branches to follow.

I'll do this myself today if no one gets to it first but I wanted to lay out the solution here in case someone else is working on it.

**Comment by dfannius** [comment]
(The graph probably used to look okay because there was other code, since disabled, that was automatically promoting variations to the main branch whenever you descended into them.)

**Comment by bittsitt** [comment]
The original idea was that the winrate graph should only display the main trunk, not any variations (and that is how the first code worked). The plan was to add support for showing the current variation in addition to the main trunk (an extra line of different color).

I hope to add this this weekend (featurecat asked for this), but not sure if I have time to do so. Right now I'm looking at jumping between variations using arrow keys, but the algorithm is not that straightforward (at least not the one I've found so far) so it takes a bit of time to get rid of the bugs...
