### ISSUE TITLE
Winrate graph displays nonexistent and unreliable data

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#104]
Currently the winrate graph draws a winrate for every node in the current variation, regardless of how many LZ visits that node has gotten. This data can sometimes be silly. Examples to trigger this behavior:

- Load a new SGF file (the whole game will exist but be unexplored)
- Hold down right-arrow to zoom through the loaded game (we get so few visits that the evaluation is nonsense)

I suggest that we require some minimum number of visits to a node before populating its winrate, and have a flag on the node (could be a boolean, could be a negative value of winrate) indicating whether its winrate is reliable and should be drawn.

**Comment by jokkebk** [comment]
To hijack the idea, I was just coming to propose, that it would be amazing if instead of having to step through an SGF manually to get a usable winrate graph, maybe some automated "analysis run" would be possible, with Lizzie spending X seconds every move to build winrate evaluation, and after a coffee or soda and some quality internet forum time, I could tab to Lizzie and see where it went wrong?

Also, make the winrate graph clickable so I can jump to turning points.

PS. Amazing software, I like it a lot!

**Comment by dfannius** [comment]
@jokkebk [Go Review Partner](https://github.com/pnprog/goreviewpartner) does some of what you want, so you may want to check that out, at least until Lizzie gets those features :) It does feel like just automating the process of stepping through the game one move every X seconds shouldn't be too difficult.

**Comment by featurecat** [comment]
I feel like we want an Autoplay function. Some in-program adjustable time per move w/ configurable default, interrupted upon any command. Doesn't seem hard :)

**Comment by featurecat** [comment]
Another feature I was thinking about is, we could write a search function that determines the most likely winrate graph efficiently. Instead of uniformly spending x seconds on each move, it would smartly put more time in places that are more complicated.

**Comment by bittsitt** [comment]
Pre-scanning the file has been on my list ever since I tested the winrate graph the first time. Any ideas on how to discover when a position is more complicated? Less difference between number of playouts in top three candidates?

**Comment by dfannius** [comment]
That sounds reasonable. Another simple criterion would be what fraction of all playouts are going to the top candidate. That would give the same "complication factor" to 60-10-10-10-10 as to 60-40, even though it's probably more likely to change its mind with more time in the second example, but I'm not sure that's a bad thing.

**Comment by bittsitt** [comment]
Although I agree with the idea of making it clear when there is no reliable data available, I'm not sure if I'm a fan of not displaying anything. It no longer looks like a graph and is a bit confusing. Could we just use a grey line where there is no data instead? Will look nicer I think, and still make the user aware that the data is not actual.

**Comment by dfannius** [comment]
Where do you want to draw that grey line? Flat at 50%, regardless of the valid data? Or a grey line connecting the two closest valid points on the graph?

**Comment by jokkebk** [comment]
How would a bar chart look like? The moves are discrete in any case, less
issues with continuity. Could even be "temperature" coloured...

**Comment by dfannius** [comment]
A bar chart would indeed get rid of the issues with continuity. I guess the baseline of the bars would want to be at 50% and they would extend up and down from there. They could even be colored black and white depending on their direction.

The main downside I can see is that there would no longer be a good way to display the variation at the same time.

(I'm not personally sure it's that useful to display the winrates for both the variation and the main branch anyway; it's not the values should have any trend to them, so if you branched off at move _n_ and are now at move _n+d_, the important things to compare are the branch winrate at time _n+d_ and the common winrate at time _n_, not the branch winrate at time _n+d_ and the trunk winrate at time _n+d_.)

Anyway, it wouldn't be hard to mock up.

**Comment by featurecat** [comment]
I like the line graph better. couldn't we just draw an average change line? eg if at move n it's 60% with 10000 playouts and move n+d it's 80% with 10000 playouts

**Comment by featurecat** [comment]
we could draw a line between n, 60 and (n+d), 80

**Comment by featurecat** [comment]
the line could be a dashed line too.

**Comment by dfannius** [comment]
Yeah, that's what I was suggesting [in this comment](https://github.com/featurecat/lizzie/issues/104#issuecomment-384694751). I'm not sure I'd like it though. And I don't think we should display anything after the last valid node (rather than some gray line sloping over to 50% at the very right of the graph). Again, not hard to try out.

**Comment by featurecat** [comment]
OK alternative feature: can enable smoother winrate option. continually, every position in the sgf gets simultaneously evaluated by Leela zero until the minimum playouts of that node is K. k=100 is probably OK. to speed up computation it would be fine to skip every m moves and smooth the graph between the endpoints.

**Comment by bittsitt** [comment]
See #147.

**Comment by featurecat** [comment]
I believe this is mostly fixed now?

**Comment by dfannius** [comment]
Yes, as far as I am concerned it was fixed with #133; if there are still other improvements to be made to the winrate graph they can go in other issues.
