### ISSUE TITLE
Prettier "Pondering on" notice

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#124]
Lizzie is so beautiful and elegant, it's a shame that there's a big "Pondering on" shouting at me from the corner all the time (especially since generally you can already tell whether Leela Zero is pondering by whether the best move display is updating).

A nice elegant way to display the same information might be a little colored light like on a stereo: green if pondering is on, red if pondering is off, amber when Leela Zero is loading.

**Comment by featurecat** [comment]
agreed. we need a way to make it intuitive to new users.

**Comment by DmitriyKhr** [comment]
Perhaps something like:
Pondering on = hamster running in a wheel 
Pondering off = hamster sleeping
loading = standard loading animation

The image of sleeping vs activity will be intuitive to anyone, no matter how computer savvy. It doesn't have to be a hamster, obviously: maybe a cartoon person focusing intently would suffice.

As for loading, no need to re-invent the wheel - users are already trained to recognize a variety of loading animations.

**Comment by featurecat** [comment]
hahahaha. nice. id love to do something like that

**Comment by OlivierBlanvillain** [comment]
Closed in #324.
