### ISSUE TITLE
Configurable UI

### ISSUE THREAD

**Issue by isty2e** [featurecat/lizzie#127]
Despite all new great features added in v0.4, I still use v0.3 because I use Lizzie on a 10:16 screen. It would be better if the positions of UI elements are configurable.

For example, in WGo.js player, the layouts are defined like following:

```
WGo.BasicPlayer.layouts.one_column = {
    top: ["InfoBox", "Control"],
    bottom: ["CommentBox"]
};
```

So if we design UI elements for two separate modes (i.e., horizontal and vertical), they can be placed freely or be hidden, which would be configurable by lizzie.properties. Currently the list of them would be:

- Players info (can be fixed on top)
- Navigation+menu buttons (can be fixed at the bottom)
- Current winrate
- Winrate graph
- Variation tree

I also have another thought or two about how to show variations without trees, which I will propose when I can spare some time on it.

**Comment by featurecat** [comment]
We are refactoring everything for next version. This should also let us support much higher levels of customization.

1. Player info -> I would argue this should stay at title-bar. It makes sense and leaves more room for other things.
2. Navigation -> yes. Menu buttons -> you mean the set of options such as File Edit View etc? Those usually go at the top, below the title bar... I am opposed to putting them anywhere besides the convention.
3. Current winrate -> yes
4. winrate graph -> yes
5. variation tree -> yes

Looking forward to hearing your idea about variations without trees!

**Comment by OlivierBlanvillain** [comment]
I think everything element can be toggled from the config file, so this is partially implemented. Designing every UI element in both horizontal and vertical mode sounds like a lot of work, and I don't think anyone is planning on working on that in the near future, so I will close this for now.
