### ISSUE TITLE
Unable to load SGF Files for Handicap Games

### ISSUE THREAD

**Issue by Aerospace91** [featurecat/lizzie#128]
When pressing O and selecting a SGF file to load, after clicking open. Pondering will turn off and then just hang. In command prompt I see the file path and nothing else after that. I can still input moves manually and turn on pondering. The tree variation also remains unchanged. Tried with multiple SGF files. 

The only instance I can get loading to work is with SGF files on even games.

**Comment by featurecat** [comment]
by pondering turn off and hang, you mean that pressing space won't turn it on?

**Comment by Aerospace91** [comment]
Correct

**Comment by featurecat** [comment]
oh. Pleaes send me a sgf that does not load so I can test it! many thanks
