### ISSUE TITLE
doesn't run on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by magmdot** [featurecat/lizzie#129]
Hi guys,

I compiled leelaz from 
https://github.com/featurecat/leela-zero

and put leelaz into the lizzie directory.

got the best network from 
 http://zero.sjeng.org/best-network

extracted it into the lizzie directory and named it network. 

with "java -jar Lizzie.jar"

I get 

"Leelaz process ended."

the command java -version results in:
"java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)"

thanks for any help, magmdot

**Comment by magmdot** [comment]
When i set print_comms to true: I get additionally:
"> time_left B 0 0"

**Comment by magmdot** [comment]
After installing "Beignet", i get:

./leelaz -w network
Using 2 thread(s).
RNG seed: 16652885729078418633
Leela Zero 0.13  Copyright (C) 2017-2018  Gian-Carlo Pascutto and contributors
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see the COPYING file for details.

Detecting residual layers...v1...192 channels...15 blocks.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 beignet 1.1.1
Platform profile: FULL_PROFILE
Platform name:    Intel Gen OCL Driver
Platform vendor:  Intel
Device ID:     0
Device name:   Intel(R) HD Graphics Haswell GT2 Desktop
Device type:   GPU
Device vendor: Intel
Device driver: 1.1.1
Device speed:  1000 MHz
Device cores:  20 CU
Device score:  612
Selected platform: Intel Gen OCL Driver
Selected device: Intel(R) HD Graphics Haswell GT2 Desktop
with OpenCL 1.2 capability.

Started OpenCL SGEMM tuner.
Will try 578 valid configurations.
(1/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 4.2013 ms (28.1 GFLOPS)
(3/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 2.9468 ms (40.0 GFLOPS)
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
(69/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 2.4854 ms (47.5 GFLOPS)
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
(120/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=1 2.3535 ms (50.1 GFLOPS)
(130/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=1 2.2178 ms (53.2 GFLOPS)
(172/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=16 NDIMC=16 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=2 2.1830 ms (54.0 GFLOPS)
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
(223/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=2 2.1746 ms (54.2 GFLOPS)
(287/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=4 2.1394 ms (55.1 GFLOPS)
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.
Beignet: Work group size exceed Kerne's work group size.

**Comment by magmdot** [comment]
and finally:
Beignet: Work group size exceed Kerne's work group size.
(512/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 2.0454 ms (57.7 GFLOPS)
(517/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 1.9520 ms (60.4 GFLOPS)
Wavefront/Warp size: 16
Max workgroup size: 512
Max workgroup dimensions: 512 512 512 
BLAS Core: Haswell

Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t 
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . . + . . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . . + . . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t 

Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D

Black time: 01:00:00
White time: 01:00:00

Leela: 
Passes: 0            Black (X) Prisoners: 0
Black (X) to move    White (O) Prisoners: 0

   a b c d e f g h j k l m n o p q r s t 
19 . . . . . . . . . . . . . . . . . . . 19
18 . . . . . . . . . . . . . . . . . . . 18
17 . . . . . . . . . . . . . . . . . . . 17
16 . . . + . . . . . + . . . . . + . . . 16
15 . . . . . . . . . . . . . . . . . . . 15
14 . . . . . . . . . . . . . . . . . . . 14
13 . . . . . . . . . . . . . . . . . . . 13
12 . . . . . . . . . . . . . . . . . . . 12
11 . . . . . . . . . . . . . . . . . . . 11
10 . . . + . . . . . + . . . . . + . . . 10
 9 . . . . . . . . . . . . . . . . . . .  9
 8 . . . . . . . . . . . . . . . . . . .  8
 7 . . . . . . . . . . . . . . . . . . .  7
 6 . . . . . . . . . . . . . . . . . . .  6
 5 . . . . . . . . . . . . . . . . . . .  5
 4 . . . + . . . . . + . . . . . + . . .  4
 3 . . . . . . . . . . . . . . . . . . .  3
 2 . . . . . . . . . . . . . . . . . . .  2
 1 . . . . . . . . . . . . . . . . . . .  1
   a b c d e f g h j k l m n o p q r s t 

Hash: 9A930BE1616C538E Ko-Hash: A14C933E7669946D

Black time: 01:00:00
White time: 01:00:00

**Comment by magmdot** [comment]
now it works. Beignet was the trick. 
Thank you.

**Comment by featurecat** [comment]
@magmdot: according to the Leela Zero output, it is using an integrated graphics card. I would also recommend trying the CPU version with more threads and seeing which one is faster for best performance!

**Comment by magmdot** [comment]
I did, how many threads are appropriate?

(*-memory
          Beschreibung: Systemspeicher
          Physische ID: 0
          Größe: 7889MiB
     *-cpu
          Produkt: Intel(R) Core(TM) i5-4570T CPU @ 2.90GHz
          Hersteller: Intel Corp.
          Physische ID: 1
          Bus-Informationen: cpu@0
          Größe: 3556MHz
          Kapazität: 3600MHz
          Breite: 64 bits
          Fähigkeiten: fp)

**Comment by featurecat** [comment]
with cpu I think the max thread count of your cpu is best.. try 2, 4, and whatever your max thread count is. With gpu probably between 1 and 4 is right for you. I would just eyeball it with lizzie and if you want optimal performance you can measure it with "./leelaz -w network --benchmark
