### ISSUE TITLE
 improvement proposal  of the next version 

### ISSUE THREAD

**Issue by tanguocn** [featurecat/lizzie#13]
Next version，we hope increasing the following function key 
1. Only analysis black or analysis white ; and you can edit the situation, freedom in any situation, 
2/ at anytime could set black go or set white to go freely. and display black or white win rate (set to black to go or wihite to go ) 
3, display best move :  recommend the best  with the red circle  instead  of yellow color is more clearly ,easey to find
4/ open sgf file and save as sgf file funtion key
5/  pass funtion: play pass at anytime freely
6/  komi :set komi freely

**Comment by CamWagner** [comment]
1) can you clarify? do you mean that for every other move, you would like no analysis? can't you just pause the analysis or ignore what it writes to the board? 
2) this can be added, especially for handicap games. isn't the winrate already displayed? I prefer the information to be on the stones... 
3) will be added
4) that would be nice. in 2-3 versions!
5) implemented by pull request 
6) difficult for Leela zero. it can only do 7.5 komi. maybe it's impossible.

**Comment by tanguocn** [comment]
1、that means：only white go or only black go , lz analysing.

**Comment by featurecat** [comment]
I think 0.3 implemented most of these features.
