### ISSUE TITLE
I created a repo lizzie-plugins

### ISSUE THREAD

**Issue by cngoodboy** [featurecat/lizzie#131]
https://github.com/cngoodboy/lizzie-plugins
For plug-ins, there are currently no plug-ins.
I hope that a new feature is to export the plugin first and then add it to the code.

**Comment by featurecat** [comment]
so you are thinking the majority of features could be plug-ins which are toggleable via the folder?

**Comment by cngoodboy** [comment]
yes.

**Comment by featurecat** [comment]
Would you be able to export a feature to plugin as an example for others? I would try VariationTree since WinrateGraph has an outstanding pull request.

**Comment by featurecat** [comment]
any updates?
