### ISSUE TITLE
There are some requests

### ISSUE THREAD

**Issue by igofun** [featurecat/lizzie#137]
1.I want to make hover-stones transparent.
2.I want to make the default folder of SGF storage current.
3.I want to assign a togglePonder to a mouse wheel click.

thank you.

**Comment by featurecat** [comment]
3. would that be the middle mouse click?

**Comment by featurecat** [comment]
edit: nvm I see that u said that already.

agreed w all changes. will try to implement for v0.5

**Comment by igofun** [comment]
yes.
thank you.

**Comment by bittsitt** [comment]
I already have a patch for 2, but in my patch, I store it in lizzie.properties which I don't think is a good idea. There are many settings we can persist between sessions (last folder for SGF files, size of window, all the params you can toggle), but those would clutter the lizzie.properties unnecessarily. I would therefore suggest a separate file for storing this. Bit busy for me these days, but can have a look at it again if I find some time (but if somebody else has time, please jump in).

**Comment by ProLeela** [comment]
Hello. First of all thank you for the hard work.
I am not sure if I do everything allright, but it would be nice to be able to save the sgf with all the branches tried (manually till the last move/played alternatively by Leela/played onluy by Leela with force move). I tried and the only branc saved is the main sgf without variants. I tried Ctrl+C/CTRL+V and the same. If I had not understood smth pls help. Thank you !
PS And it would be nice if the tree would have the same posibility to navigate on every branch, or even delete some of the branches as in Sabaki.

**Comment by featurecat** [comment]
Ah. somehow I just assumed that was already being handled. thanks for alerting us.

**Comment by featurecat** [comment]
this is a bit of a different issue. in the future you should raise a new issue for this bug :)

**Comment by igofun** [comment]
Sorry again.
Is there a way to erase a branch or one move?

**Comment by featurecat** [comment]
not yet. but the /next branch already has branch reordering! so you can set whatever you like as main variation. we're working on other features 😌

**Comment by igofun** [comment]
I want to erase it when I make a mistake move

**Comment by bittsitt** [comment]
I have added it, so it should become available if featurecat merges my pull request.

**Comment by igofun** [comment]
thank you.

**Comment by igofun** [comment]
Why was not it implemented?

**Comment by bittsitt** [comment]
2 has been implemented (it remembers the last folder you opened sgfs from), and erase has been implemented (back-space). Nobody has gotten around to the other two yet I guess

**Comment by featurecat** [comment]
Sorry, but I'm running this project out of my own time, for free. I actually like all your features, but don't have the time to implement them as well as the 100 other features people would like me to implement. The surest way to see a feature you would like is to code it yourself and contribute it to this repository!

**Comment by igofun** [comment]
I do not know the details, but will it take so much time?

        else if (e.getButton() == MouseEvent.BUTTON2){ // 
                if (Lizzie.frame.isPlayingAgainstLeelaz) {
                    Lizzie.frame.isPlayingAgainstLeelaz = false;
                    Lizzie.leelaz.togglePonder(); // we must toggle twice for it to restart pondering
                    Lizzie.leelaz.isThinking = false;
                }
                Lizzie.leelaz.togglePonder();
}

It seems to be possible in ten seconds but is it useless?

**Comment by igofun** [comment]
I am an amateur
boardrender.java line 389

                if (Lizzie.board.getStones()[Board.getIndex(i, j)] == Stone.EMPTY){
			    	// アルファ値
					AlphaComposite composite = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);

			        // アルファ値をセット（以後の描画は半透明になる）
			        g.setComposite(composite);
			        gShadow.setComposite(composite);

                    drawStone(g, gShadow, stoneX, stoneY, branch.data.stones[Board.getIndex(i, j)].unGhosted());
                }

Do not you make it transparent in this neighborhood?

**Comment by igofun** [comment]
I moved before but I do not know if it will move because it is not maven

**Comment by OlivierBlanvillain** [comment]
I don't think anyone plans on working on transparency and custom input binding, so I will close this for now. If you happen to implement either of these please open a PR!
