### ISSUE TITLE
better README

### ISSUE THREAD

**Issue by levavft** [featurecat/lizzie#138]
please change the line:
Download the best network from http://zero.sjeng.org/best-network, save it in the lizzie directory as "network"
to:
Download the best network from http://zero.sjeng.org/best-network.
Unpack it (for windows users, winzip /7zip will do it).
Save the unpacked file in the lizzie directory as "network". (with or without the .txt, should be clear).

**Comment by featurecat** [comment]
thanks. added to main github Readme. will add to the release Readmes when I get a chance.

**Comment by levavft** [comment]
Looks great! Happy to help
