### ISSUE TITLE
On high hardware/ high playout, massive lag at beginning of each moves

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#141]
1. "I had to click 20 seconds sometimes for move to enter position. 
It was good that I asked him 40 seconds byomi, because 30 seconds was too small, as it was not instantly making a move. "

2. "This is a problem with Lizzie, I noticed this too!
It  waste so much time per move!"

////

Problem is that say I click a move, and wait 60 seconds, now on decent hardware (like 8x titan V ) it gets massive playout already. Then I click on the next move, there is lag... I have to click and reclick many times for Lizzie to "take" that input and then it won't show any stats as far as wr% or analysis sometimes for almost 10 to 20 seconds...

Why is this such a lag? It creates a HUGE 'overhead" per every move and prevents blitz games.

**Comment by hydrogenpi** [comment]
Video is being uploaded perhaps will show in detail what is meant by the "lag per move" at the beginning

**Comment by featurecat** [comment]
you don't need to make a video. I know exactly what you mean but I don't think I can fix it, it's a problem with Leela zero. one fix I can make is to change the max-time-to-analyze parameter from minutes to seconds. then you might set the max time to around 30 seconds on your machine and it should be fast enough without over-analyzing

**Comment by featurecat** [comment]
one idea that might work is to have K instances of Leela zero at once. when the user makes a move with >20,000 playouts, we terminate that Leela zero instance and start pondering on the next Leela zero instance. meanwhile we restart the terminated Leela zero instance. it might work. it feels completely wrong that it's faster to do this, but I think it works... thoughts?

**Comment by featurecat** [comment]
otherwise, I don't know how to fix this issue.

**Comment by featurecat** [comment]
seems like this is mostly fixed in the latest Leela zero version. soon that will ship with lizzie by default for 0.5 as usual.
