### ISSUE TITLE
Store winrate and playouts in sgf

### ISSUE THREAD

**Issue by bittsitt** [featurecat/lizzie#149]
I think it would be very useful to store winrate (and play outs, and maybe even top alternatives) in the sgf so that if you spend a lot of time processing a file, you don’t have to redo it if you want to look at again. On chess servers, you can also get your file analyzed by a computer for a fee, and something similar is likely to happen with go. 

Are there any sgf experts here that knows how this could be done? One easy solution would be to add it in the comments, but it makes it harder to find actual comments (from a review eg). There is also a value property, but for go it says specifically that it refers to score estimate, also you wouldn’t be able to store play outs.

Is it easy to extend the sgf format eg?

**Comment by featurecat** [comment]
I have seen before developers make their own tags. I think we can do something similar. That way it won't be read as a comment.

**Comment by bittsitt** [comment]
Releases are pretty cheap I think, and there are already many features that are not available in any release yet (scoring, delete move etc). So I would suggest to get a release out this weekend, and then aim for another release in a week or two :-)

**Comment by bittsitt** [comment]
Oh, I asked in leela zero (see https://github.com/gcp/leela-zero/issues/1297 ), but didn't get much feedback. However, I was made aware that goreviewpartner has introduced a "rsgf" format. We should probably have a look at that and see if that can fit our need (I haven't had time yet, had some trouble getting grp to run). It would be good to standardise on something to maintain some cross-compatibility.

**Comment by featurecat** [comment]
I'd prefer to work with the default .sgf files if possible, since it's the file type most SGF programs search for. SGF format generally let's you create your own tags. Such as maybe LZ for Lizzie :). LZ is not used in the SGF specification.

Another option, we could probably attach LZ analysis at the end of comments. The downside is that SGF editors would think there are comments on every move. So I prefer a tag.

**Comment by OlivierBlanvillain** [comment]
Fixed in #364.
