### ISSUE TITLE
Android iOS releases? 

### ISSUE THREAD

**Issue by BHydden** [featurecat/lizzie#161]
Just wondering if there are any plans for Lizzie to have phone / tablet app releases? Or are they not powerful enough to run leela zero?

**Comment by featurecat** [comment]
Phones are most likely are powerful enough to run a 7d or 8d Leela Zero. Currently I use Chrome Remote Desktop to interact with my computer to get analysis. The app is really good. Phone/tablet release would be amazing for the future. But for now we have a large amount of things to deal with in the code, so I see this being added nearer to the end of the year if at all.

**Comment by BHydden** [comment]
Thanks for the feedback, I shall wait patently yet hopefully ;-)

**Comment by featurecat** [comment]
it would be a totally different project. it would be fine to start on it now, but I think in the present, I want to work on a more featured desktop version.

**Comment by BHydden** [comment]
Yeah for sure man I totally agree. Gotta at least aim for Lizzie 1.0 ay? ;-)
