### ISSUE TITLE
Can LZ run this facebook weight?

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#162]
https://github.com/gcp/leela-zero/issues/1311

https://github.com/pytorch/ELF/issues/1

**Comment by dfannius** [comment]
This is a question for Leela Zero, not for Lizzie, unless you want Lizzie to support ELF Open Go (and hack it to produce continual pondering output).

**Comment by merlinpan** [comment]
A new leela-with-lizzie patch binary is needed though (with leela's elf network support).  The one in 0.4 wouldn't do.

**Comment by featurecat** [comment]
#171 indicates this is mostly working... when leela zero officially includes a PR for ELF, we can also incorporate it into Lizzie.

**Comment by kris-computer-go** [comment]
just released:
Leela Zero 0.14 + AutoGTP v16
with support for converted ELF Open Go networks.
