### ISSUE TITLE
Lizzie v0.4 Windows 64-cpu Crashing on first start up

### ISSUE THREAD

**Issue by Wizard106** [featurecat/lizzie#163]
Hey, I'm here to report an issue with the Lizzie v0.4 release.

I unzip the release and the latest network .txt which I rename to network without any file extension; Windows now acknowledges this as a "File" rather than a "Text document". This network file is placed into the lizzie folder. 

First if I were to run it via an Admin Command Prompt I get this error message over and over along with a completely white window:

> 
> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: boardLength may not be less than 18, but was 0
>         at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:486)
>         at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:712)
>         at wagner.stephanie.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:758)
>         at wagner.stephanie.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:555)
>         at wagner.stephanie.lizzie.gui.Input.mouseMoved(Input.java:56)
>         at java.awt.Component.processMouseMotionEvent(Unknown Source)
>         at java.awt.Component.processEvent(Unknown Source)
>         at java.awt.Container.processEvent(Unknown Source)
>         at java.awt.Window.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)

If I were to press the "Ctrl" key when on this white screen a black screen with white text saying "Leela Zero Loading..." appears and the error changes to this:

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
>         at wagner.stephanie.lizzie.Lizzie.shutdown(Lizzie.java:55)
>         at wagner.stephanie.lizzie.gui.LizzieFrame$1.windowClosing(LizzieFrame.java:124)
>         at java.awt.Window.processWindowEvent(Unknown Source)
>         at javax.swing.JFrame.processWindowEvent(Unknown Source)
>         at java.awt.Window.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)

When run like this, no plugin folder or lizzie.properties file is created. 

When I double click on the .jar something different happens. The mentioned files are created and a small window named "Lizzie -Leela Zero Interface" pops up with a Goban and white text saying something to the effect of "Leela is Loading", then it crashes. If I try to double click the .jar again, nothing happens. I don't think the program is still active in the background as Windows allows me to delete it, after which I have been unzipping Lizzie again and starting from scratch. I've done this several times and nothing changes.

I'm running Java Version 8 (build 1.8.0_171-b11).

Edit:
I've been running my command prompt from C:\Windows\system32\> so I used cd to get to the lizzie folder and run Java -jar Lizzie.jar from there. The following error comes up:

> Creating config file
> Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: boardLength may not be less than 18, but was 0
>         at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:486)
>         at wagner.stephanie.lizzie.gui.BoardRenderer.calculatePixelMargins(BoardRenderer.java:712)
>         at wagner.stephanie.lizzie.gui.BoardRenderer.convertScreenToCoordinates(BoardRenderer.java:758)
>         at wagner.stephanie.lizzie.gui.LizzieFrame.onMouseMoved(LizzieFrame.java:555)
>         at wagner.stephanie.lizzie.gui.Input.mouseMoved(Input.java:56)
>         at java.awt.Component.processMouseMotionEvent(Unknown Source)
>         at java.awt.Component.processEvent(Unknown Source)
>         at java.awt.Container.processEvent(Unknown Source)
>         at java.awt.Window.processEvent(Unknown Source)
>         at java.awt.Component.dispatchEventImpl(Unknown Source)
>         at java.awt.Container.dispatchEventImpl(Unknown Source)
>         at java.awt.Window.dispatchEventImpl(Unknown Source)
>         at java.awt.Component.dispatchEvent(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.awt.EventQueue$4.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)
> Leelaz process ended.

A Subsequent run yields this:

> Leelaz process ended.
> java.io.IOException: Problem reading font data.
>         at java.awt.Font.createFont0(Unknown Source)
>         at java.awt.Font.createFont(Unknown Source)
>         at wagner.stephanie.lizzie.gui.LizzieFrame.<clinit>(LizzieFrame.java:87)
>         at wagner.stephanie.lizzie.Lizzie.main(Lizzie.java:43)

I then replaced my jar file with the one you provided at https://github.com/featurecat/lizzie/issues/139 and was presented with simply this error:

> Leelaz process ended.

The difference with me and https://github.com/featurecat/lizzie/issues/139  is that my network file isn't a .txt and it still doesn't work.

**Comment by Dreamkeeper66666** [comment]
same here！

**Comment by Wizard106** [comment]
I have since restarted my computer and downloaded the Visual C++ Redistributable for Visual Studio 2015. I don't know which did it but Lizzie is running fine now. If anyone encounters this issue just follow the steps in my original post and then if you still can't open it download the Visual C++ Redistributable for Visual Studio 2015 from Microsoft.
