### ISSUE TITLE
Feature request: sweep to make graph

### ISSUE THREAD

**Issue by pondturtle** [featurecat/lizzie#164]
I see that last version of lizzie shows graph of winrate development throughout the game, which is really cool feature. The issue is that the graph only build as I go through each of the moves stopping at each one so LZ has time to analyze them.

I think it would be great if there was option to let LZ go through the game first to build the graph in similar manner GRP does so I can quickly locate biggest winrate drops indicating mistakes. Thanks

**Comment by dfannius** [comment]
It's a good idea and we have been discussing it! But it's good to have this open as a distinct issue to have a specific issue to refer to.

**Comment by bittsitt** [comment]
I will re-submit the PR, but will wait for score-mode PR as I know I will have to fix some merge conflicts anyway.

**Comment by bittsitt** [comment]
See #175. Hit a, enter number of playouts per move, sit back and wait.

**Comment by featurecat** [comment]
#175 implements this. More work will be done on this in the future.
