### ISSUE TITLE
Unable to run LeelaZ 14 on windows

### ISSUE THREAD

**Issue by Dorus** [featurecat/lizzie#173]
![afbeelding](https://user-images.githubusercontent.com/4461459/39656733-5b963100-5002-11e8-9243-20ce2e8e241c.png)
 
This happens both with a fresh network as the elf net. Leela works just fine on the command line.

**Comment by isty2e** [comment]
From readme:

> First, you will need to have a special version of Leela Zero that continually outputs pondering information. You can get this from one of the Lizzie releases or build it yourself; just substitute leelaz-src/UCTSearch.cpp for the UCTSearch.cpp file found in the Leela Zero sources. Then copy the resulting leelaz to the root of the Lizzie directory tree.

You can download Lizzie-compatible branch in https://github.com/Ka-zam/leela-zero though.

**Comment by hydrogenpi** [comment]
Lizzie has zero loyalty

![image](https://user-images.githubusercontent.com/35181396/39657657-e3938128-4fbe-11e8-9dbc-1290ecafc773.png)

**Comment by Dorus** [comment]
@isty2e Thanks, this works :)
