### ISSUE TITLE
Request on Upgrading Your LeelaZero Repository to Support ELF Network on Lizzie

### ISSUE THREAD

**Issue by cdqz2014** [featurecat/lizzie#174]
I ran Lizzie on my Arch Linux, and it worked fine with your modified leelazero source code. But yesterday gcp has upgraded the version of LZ to make it compatible with the new converted ELF network. 
In order to run this powerful network on lizzie (on my archlinux), I hope you upgrade your lz repository as well.

**Comment by d7urban** [comment]
Yeah, I'd love to use the ELF with Lizzie too!

**Comment by featurecat** [comment]
Yes! will do before release which is within the next 2 weeks for sure. It's also worth considering merging #172 at the same time.
