### ISSUE TITLE
Could U pls make a CPU version of Lizzie for Lz14?

### ISSUE THREAD

**Issue by cjohnchen** [featurecat/lizzie#176]
Thx

**Comment by featurecat** [comment]
Yes, of course :) We will most likely release like last time. Jar + ( Win64:(gpu.exe, cpu.exe), Linux/Mac:(compile from repository) ). Somewhere a guide was posted about how to compile for Win32 so I will also attempt to do that.

**Comment by jcguu95** [comment]
Any news :) ?
