### ISSUE TITLE
Use Leela 0.11.0 on Lizzie

### ISSUE THREAD

**Issue by kaorahi** [featurecat/lizzie#178]
What do you think about using Leela 0.11.0 instead of Leela Zero with
Lizzie UI?  Leela 0.11.0 is still useful for analysis of handicapped
games because Leela Zero overlooks bad moves and says "B will win
anyway" until the last mistake of B.

I have a toy implementation here.
  https://github.com/kaorahi/lizzie/tree/leela_nonzero
Is there any possibility of merging if I brush it up?

It works in a similar way as #172.  Namely, it repeats
(1) Send "time_left b 0 0" to start pondering.
(2) Wait for 1 second.
(3) Send "name" to stop pondering.
(4) Read outputs of leela.
(5) Go to (1).

See README_leela0110.txt in the above branch for trying it.  As a side
effect, it can also run the original Leela Zero without modification.

**Comment by featurecat** [comment]
yes. this is a good idea. we can also use this as a failsafe for incompatible Leelaz versions.
