### ISSUE TITLE
sgf loading  feature please

### ISSUE THREAD

**Issue by pickcherry** [featurecat/lizzie#18]
Possible to add teh feature for loading sgf file? It will save tons of time!!

**Comment by CamWagner** [comment]
Really popular request. I will be able to release after this week. Are there any specific requests you have for SGF loading? How should we handle different variations?

**Comment by pickcherry** [comment]
Very quick reply. It would be good to make the function as simple as possible for the early version. for example, komi sets to 7.5 (default) because most of AI are trainned under 7.5 komi. 

Also, to make it more convenient, a feature that conver picture to sgf file would be exciting for go fans (or directly import picture to lizzie). There is already a Phython based project in github.

**Comment by CamWagner** [comment]
convert image to sgf file? not a single image I imagine, since that only shows the final board position. I think image to sgf is beyond the scope of Lizzie. But basic sgf interfacing is possible.

**Comment by CamWagner** [comment]
I think some simple interfacing features are best since 1) I don't have a lot of time to devote to projects and 2) in the future, I might like to port this to something besides Java.

**Comment by jillybob** [comment]
Is it somehow possible to decompile/ reverse-engineer the Leela11 GUI?

**Comment by CamWagner** [comment]
Not really necessary; what feature about it do you miss?

I think a more modern writeup of the Leela UI would be popular, with Leela Zero.

**Comment by jillybob** [comment]
I like the "Histogram" feature that shows winrate over time. I also like the analysis window, that shows a window of playouts/winrates for its moves.

**Comment by pickcherry** [comment]
A modern UI sounds a good idea. How about to add line that we can specify the parameters for leelazero and other AI?

**Comment by isty2e** [comment]
By the way, sgf files obtained from images are not usable for LZ unless numbered, since LZ requires move history as a part of input.

**Comment by CamWagner** [comment]
Implemented, thanks to cngoodboy for writing the SGF parser :)
