### ISSUE TITLE
GUI sluggish running under Linux

### ISSUE THREAD

**Issue by Ka-zam** [featurecat/lizzie#188]
This is something I've noticed since the start actually but never bothered investigating very much. 

GUI is noticeably more sluggish in Ubuntu 18.04 than Win10 using the exact same hardware (2700X, GTX1080, 32GB RAM).

I did try this:
   `-Dsun.java2d.opengl=true`
but that didn't seem to help much.

**Comment by featurecat** [comment]
could you describe how it is sluggish? I use lizzie on windows and Ubuntu but with weaker hardware on Ubuntu, but I haven't observed it being slower.

**Comment by Ka-zam** [comment]
Mouse clicks take something lika half a second to register. Scrolling through game record is equally slow. Im using Iced Tea and maven. Interesting that you havent noticed anything!

**Comment by featurecat** [comment]
Without pondering, is it the same?

**Comment by Ka-zam** [comment]
It's definitely more pronounced with pondering on.

**Comment by Ka-zam** [comment]
OK, I fixed it:

Step 1: Install Oracle java version [instructions for apt-get here](https://linuxconfig.org/how-to-install-java-on-ubuntu-18-04-bionic-beaver-linux)
Step 2: Run with `-Dsun.java2d.opengl=true`
Step 3: Observe snappy behaviour

**Comment by featurecat** [comment]
That might explain why I had snappy behavior by default, since I used oracles jdk

**Comment by tasuki** [comment]
This should be mentioned in a more visible place! I'm on Ubuntu 16.04. Especially with the recent larger Leela Zero networks, the Lizzie interface became unusable for me: easily a second of a delay for any action. A friend referred me to this issue, running with `-Dsun.java2d.opengl=true` makes Lizzie super snappy! :heart:
