### ISSUE TITLE
Saving SGF / Ctrl+C does not include variations

### ISSUE THREAD

**Issue by featurecat** [featurecat/lizzie#189]
The only branch saved is the main variation, without any variations.

**Comment by dfannius** [comment]
This feels more like an enhancement than a bug (it's not like anyone wrote any code to save variations that is unfortunately broken) but I agree that it's a priority.

**Comment by afalturki** [comment]
It would be great if we could delete nodes from the tree too instead of having to use seperate program for that. I'm not sure if Lizzie currently saves winning rates with the sgf but that would be nice too.

**Comment by bittsitt** [comment]
Deleting nodes using backspace/delete button has already been added. See #145 

Winning rates is not yet stored to sgf. See #149.

**Comment by OlivierBlanvillain** [comment]
Fixed in #364.
