### ISSUE TITLE
Where's it go?

### ISSUE THREAD

**Issue by Climu1d** [featurecat/lizzie#192]
I downloaded it, and it downloaded fine and as soon as I double click Lizzie it opens and it says Leela Zero loading oor something and then it just closes.... now I try to open it and it doesnt open anymore.

**Comment by featurecat** [comment]
strange
please go to lizzie.properties and enable Leelaz output to true. then start lizzie via command kine with Java -jar Lizzie.jar and let me know what the output is.

**Comment by Climu1d** [comment]
enable leelaz output to true? what do you mean, when I go to properties i see the settings and I see nothing called output...

**Comment by Climu1d** [comment]
leela settings such as thinking time settings... and such I see nothing called output... all I see is this...
{
  "leelaz": {
    "max-analyze-time-minutes": 2,
    "threads": 2,
    "max-game-thinking-time-seconds": 2,
    "weights": "network",
    "gpu": [0,1],
    "print-comms": false
  },
  "ui": {
    "shadows-enabled": true,
    "board-color": [
      178,
      140,
      0
    ],
    "shadow-size": 100,
    "show-winrate": true,
    "fancy-board": true,
    "show-variation-graph": true,
    "win-rate-always-black": false,
    "confirm-exit": false,
    "show-move-number": false,
    "show-next-moves": true,
    "show-leelaz-variation": true,
    "theme": "wagner.stephanie.lizzie.theme.DefaultTheme",
    "fancy-stones": true,
    "show-best-moves": true
  }
}

**Comment by bittsitt** [comment]
set "print-comms":true

**Comment by Climu1d** [comment]
setting that as true didnt do anything.

**Comment by featurecat** [comment]
Ah sorry I got busy and forgot to reply. I'm not sure what the problem is -- can you wait until new version (within 1 week) and try that when it's released?

**Comment by featurecat** [comment]
It will most likely solve the issue, I think.

**Comment by Climu1d** [comment]
oh new version? ok sure ! I'll let u know if anything has changed, thx !
