### ISSUE TITLE
Lizzie 0.4 GUI not working correctly for 4K

### ISSUE THREAD

**Issue by afalturki** [featurecat/lizzie#197]
Hi,

I have a 15.4 inch 4K screen and, when the windows is maximized, Lizzie does not show anything or it shows the GUI but I can't interact with it. Not sure what the problem is.

Below are screenshots:
![](https://vhc2fq.dm.files.1drv.com/y4mOFx1FtOnKx6DGX4N9xd3xcWMEkvpQP3bxjRhKMqv1g6GpgbaOp31xqPmzhq3s5B-O33Ed9lYoK45ddDCtxzKpEakSs_sIpbJKHd2mVLNxW2tuKlddbdJfidfHnF_TyF3QtObKfn6G9N1jY_d-cwHytx9Fy3AA2jNpyvgdlqTgD5naAytKWwIP3S2Zx33hKsEPtD1bJI16eNxKSdFiL1thQ?width=3840&height=2160&cropmode=none)

![](https://t8lw6a.dm.files.1drv.com/y4mA9fwkTEgU0kl_HR6p2iq4YFjrxOzXq6DPo9F_D6ahgSE2xU1lq07ozv-L4BpIOT2MxZuzd-nYE-mp9Cy89tsDsd4EisrdAOnZWyKIAH6FXIydw-A1h0yXmeoj9yZpyGgf6iVTJAsYJlY3n5asMysRhGPa6tSBp0G-HpI-b1fiHhZP_odVEi_oRgftIPdba5DyHBa_b_K0hnPwztl_IJnqg?width=3840&height=2160&cropmode=none)

![](https://tftjrq.dm.files.1drv.com/y4mYo4EkLF3yZu2uB8bdvosMLJvp-zg7DMFEw6xRyXh_cne1IZW_OwUGLDf9a18RHiX5DnpMPuN4qVfZiCA7sTw-zXvmWKx06Hn6YiGFh3VWF86vhdm0-3bxK0wZ_xW5_u22YxhOGMtU4wj7izjX3ih5GHFt4JTmWrFfiEcSd77KB61nQgfZdit2K3t6WOZ_1LtbiQgXlU16tnC_urjlFsHGg?width=3840&height=2160&cropmode=none)

The first is when I first open Lizzie. The other two are after I minimize and maximize again and the screen is also frozen. When the window is not maximized, Lizzie works correctly.

I'm using Windows 10 x64 and Java Version 8 Update 161.

**Comment by featurecat** [comment]
so when the window is not maximized and you gradually bring it up to your full monitor size, lizzie still works, even at its largest possible size?
