### ISSUE TITLE
Can't see the board when launching Lizzie.jar

### ISSUE THREAD

**Issue by 8139david** [featurecat/lizzie#202]
I am on Windows 8.1 with Java 1.8.0_171.b11
I have downloaded the latest version of lizzie.
I also followed recommendations in the issue forum to replace Lizzie.jar by another.
I downloaded the network file, extracted it, and renamed it to network.
I can launch Lizzie.jar by double-clicking on it or by the command line.
It launches ok, but it doesn't show the board:
http://www.imagebam.com/image/953d97857632134
By the way, here is what the command line shows:
https://textsaver.flap.tv/lists/1ylr
(PS: It's the same result if I just write this: java -jar Lizzie.jar.)

**Comment by featurecat** [comment]
could I see what your directory looks like? screenshot. also what does your assets folder look like?

**Comment by 8139david** [comment]
Here is the Lizzie directory:
http://www.imagebam.com/image/b9ec68858580334
I don't have any assets folder. None was provided when downloading Lizzie.
(The plugings folder is of course empty.)

**Comment by featurecat** [comment]
The assets folder *definitely* comes with the Lizzie release. Re-download a release from the Releases tab. Then the assets (board, background, stones) will appear.

**Comment by 8139david** [comment]
The instructions are definitely not clear -- that's the first thing you should update: what to download, and what to put where?

**Comment by featurecat** [comment]
Sorry if it's not clear. Generally I recommend including everything that comes with the .zip in your Lizzie directory. It works now, right?

**Comment by 8139david** [comment]
In fact, it's my mistake, I'm very sorry.
I was trying to use the ELF weights adaptaed for Leela, and all got mixed up.
When I simply download Lizzie and the latest weights (network) from Leela, it works like a charm.
Thanks for your help and for the program.
I'm looking forward to the new developments.
