### ISSUE TITLE
Compiling Leelazero with the modified UCTSearch

### ISSUE THREAD

**Issue by lszinv** [featurecat/lizzie#203]
I'm on mac and am trying to get the leelazero binary compiled with the modified UCTSearch module from this repo. It seems like the LeelaZero code has been modified enough that it's not longer compilable with a simple file replacement.

Is there a suggested commit id to use to for compiling the modified LeelaZero binary?
Maybe that commit should be added to this repo as a submodule

**Comment by LesterS4t1qbit** [comment]
After some git bisecting, it seems like the last compilable version of leelazero with the utcsearch from this repo is `64860c071364f196411e6560183ed2dea86a1979`

**Comment by lszinv** [comment]
After some git bisecting, it seems like the last compilable version of leelazero with the utcsearch from this repo is `64860c071364f196411e6560183ed2dea86a1979`

although launching lizzie immediately terminates with `Leelaz process ended.` in terminal

**Comment by bittsitt** [comment]
I've submitted a pull request to leela zero that adds proper support for Lizzie by extending the GTP protocol (see https://github.com/gcp/leela-zero/pull/1388 ). I hope and think it will go through within the next few days, which leaves the extra patch for lizzie unnecessary.

**Comment by featurecat** [comment]
so the secret is, you don't need the whole file. you just need the lines that have a // lizzie comment at the end of them. I haven't tried this with the latest Leela zero yet. I'll try to release a new version that uses bittsitt's patch for Leela zero.

**Comment by lszinv** [comment]
Oh i see, adding those lines into the master branch of LeelaZero was nice and simple then, and is compiling now.

I suppose the `NumberFormatException` on a non existing object is technically a different issue then, and isn't caused by a faulty LeelaZero

**Comment by featurecat** [comment]
oh that's really weird, so does it work? or is there still a number format exception?

**Comment by lszinv** [comment]
The `NumberFormatException` is still present using a modified version of the LeelaZero master branch. 

The backtrace makes me think that the problem is potentially coming out of the Lizzie code. It seems like the double object in question might be the coordinate positions. I'd try to offer more information, but to be quite honest, I'm not all too familiar with Java debuggers

**Comment by featurecat** [comment]
Does Lizzie continue to function despite the exception?

**Comment by lszinv** [comment]
The application continues to run and I can place stones down, but the analysis from LeelaZero stop

**Comment by featurecat** [comment]
Oh that's very strange. We should be more exception resistant in Lizzie. But likely this is a strange compilation from Leela Zero. I expect it will be fixed when we use the Leela Zero realtime pondering PR that bittsitt is working on.
