### ISSUE TITLE
Usg sgf4j for parsing and saving sgfs

### ISSUE THREAD

**Issue by bittsitt** [featurecat/lizzie#205]
I was planning to add support for loading and saving variations, but I came across this:
https://github.com/toomasr/sgf4j

Would it be better to just integrate this into Lizzie instead? Not necessary to reinvent the wheel maybe? It uses the apache license v2.0.

**Comment by featurecat** [comment]
Maybe... but aren't we very close to that already? Variations won't be that difficult to add, and we have everything correct except for variations, right? I would be highly in support of refactoring our sgf parser, instead of trying to learn a different api.

**Comment by bittsitt** [comment]
There are two different formats for variations (multigo), which makes it a bit tricky. Then, we need to add comments and marking for people to be able to use it for proper reviews. Most importantly though (and I didn't think of this until right now), we shouldn't delete information already in the sgf that the user might like to keep (everything from name of venue to time settings, sgf4j looks quite complete).

I can have a quick look to see if it is trivial or difficult at least.

**Comment by featurecat** [comment]
That's true. Maybe we should look into it, then. I'll consider it for the list of things we should work on. It would be pretty important to adopt this before we start doing much more with SGFs. I assume it doesn't handle Tygem .gib files? Fortunately those have a pretty consistent format, we can just keep the gib parser.

**Comment by OlivierBlanvillain** [comment]
I don't think we plan on switching to sgf4j in the near future, so I will close this for now.
