### ISSUE TITLE
make it work with cronus open source aka top cgos bot by Tencent

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#210]
One benefit of pushing forward open bots that are superhuman is it may force the hand of others as well, now that Fb and Tencent have open sourced their bots that are both much stronger than LZ, maybe Deepmind will come back for thirds and get a fourth place prize in openness to cheapshot score one last PR hooray for Google by open sourcing their AGZ weights to spit in fb's face and to show whos the alpha by mastering the Chinese competition once again.. open competition is good for go. This is truly the end of a human era.

**Comment by featurecat** [comment]
um. I'm not going to make this feature just to try and advance your conspiracy theory. It actually won't be too hard to do this yourself in the next version of Lizzie. But I'm not tempted to support a bot with only one network when Leela Zero has 136 different strength networks plus an overpowered ELF network.

**Comment by hydrogenpi** [comment]
http://archive.is/vPs81

**Comment by 22nsuk** [comment]
yenw announced LeelaZero_PhoenixGo and its source. Based on this, how about using PhoenixGo's weight on Lizzie?

https://github.com/yenw/LeelaZero_PhoenixGo

**Comment by featurecat** [comment]
How does it compare to Elf weights?

**Comment by 22nsuk** [comment]
It is weaker than elf, but stronger than lz.

**Comment by featurecat** [comment]
if it's weaker than elf, I kind of want to only recommend using elf. but if the PhoenixGo code is updated to use leelaz's next branch, it will work with lizzie by default (for lizzie 0.5 onwards)
