### ISSUE TITLE
Can Lizzie run Leela with parameters?

### ISSUE THREAD

**Issue by 8139david** [featurecat/lizzie#211]
I suppose so but I haven't found documentation about this.
If it's possible, is there a file to set-up with the parameters?
Or a command-line instruction?
(For instance, this game of Leela-zero online say this:
`Leela Zero options: -p 0 -v 3201 -r 5 -m 999 -t 1 -d -n --noponder -s 12583113985515942489 -g -q -w networks/62b5417b64c46976795d10a6741801f15f857e5029681a42d02c9852097df4b9`
I would like to chose my own parameters when running Leela through Lizzie.)

**Comment by featurecat** [comment]
See #182 for Leela 0.11 support coming next version. 

Command line arguments are coming.
