### ISSUE TITLE
Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by humuyan** [featurecat/lizzie#219]
After `java -jar Lizzie.jar`:
![2018-05-15 16-16-48](https://user-images.githubusercontent.com/28784198/40044908-666be726-585b-11e8-88a9-5db3904c2c94.png)
I'm sure that `leelaz` is compiled and able to work properly.

**Comment by featurecat** [comment]
is this Leelaz the leela-zero/next branch? we don't support that yet but we will very soon. Our lizzie/next branch can probably support your copy of Leela zero; you should try it.

otherwise you need to compile Leela zero from my repository. it's an old version. we will update lizzie soon :)

**Comment by humuyan** [comment]
ok thx
