### ISSUE TITLE
When using a 76M weight file, leelaz often  stop and crash

### ISSUE THREAD

**Issue by tanguocn** [featurecat/lizzie#23]
When using a 76M weight file, it often takes more than 100 rounds. Suddenly, it reminds Leelaz to stop and crash. This does not happen when using a 35M size weight file. The use of 76M weight files under sabaki software will not be the case. Is it related to lelaz.exe that comes with lizzie? How to solve this problem?

**Comment by CamWagner** [comment]
I was successfully able to use up to 20 blocks 256 filters. Could you run it via command line and show me the output? also what is your OS/available ram?

**Comment by featurecat** [comment]
Closed unless someone can help me reproduce the bug.
