### ISSUE TITLE
Quick-anaylisis-overview

### ISSUE THREAD

**Issue by WYVYW** [featurecat/lizzie#235]
I wish there was a quick-analysis option (with a fixed amount of a few visits) 
so the winrategraph would be more usefull (similar to Go Review Partner).

**Comment by featurecat** [comment]
Do you mean our current auto play feature (in /next branch)?

**Comment by WYVYW** [comment]
I am not sure. I no coder (can't compile or test any new features) but I will find out once the version is out.

**Comment by featurecat** [comment]
Oh - then, it seems we've already implemented this in an early form. It will continue to improve for allowing the saving of analysis and smarter analysis.
