### ISSUE TITLE
To-Do-List

### ISSUE THREAD

**Issue by WYVYW** [featurecat/lizzie#236]
Is there somewhere a to-do list a list of features that will hopefully implemented some day?

**Comment by featurecat** [comment]
currently every open issue marked with "enhancement" is one I would like to add, in no particular order/priority or timeline at the moment. Same with the "bug" label... 

I am currently a student; after my last final exam on Wednesday, I'm planning to release Lizzie and a TODO list for the next version after that. It will be fine to add other features that are not on the TODO list, but I am hoping that every feature will be implemented before we release each version.

**Comment by featurecat** [comment]
Off the top of my head, the to-dos for this version that is about to be released: 
- optional(default=true) automatic best-network downloading
- support for new leelaz/next ponder data format (which also happens to make winrates more accurate)
- write to-dos/guide for contributing for next version, to guide future development
- write better documentation

**Comment by featurecat** [comment]
Looks like all of these I mentioned before are done except for a proper contribution guide; I'd like to write that tomorrow.
