### ISSUE TITLE
Do you have plan to make lizzie mobile?

### ISSUE THREAD

**Issue by Godady** [featurecat/lizzie#237]
Since i used lizzie 3 months ago, I gave up almost every GTP client application(sabaki, gogui...). I feel lizzie is so awsome that i can really feel happy Go games. Lizzie is also a best tool to help goers analyze games and can be a good teaching tool. As the mobile devices becoming more and more powerful,  I think it's the time to develop a mobile version for lizzie. That would make lizzie more popular and convenient.

**Comment by featurecat** [comment]
See #161. I would love to begin, but have other features in mind first!
