### ISSUE TITLE
UCTSearch.cpp causing errors with the latest git version of leelaz

### ISSUE THREAD

**Issue by Nazgand** [featurecat/lizzie#238]
Further clarification about which version of leelaz to compile would be nice

**Comment by Nazgand** [comment]
The latest git checkout of leelaz compiled correctly after making the changes to the function
void UCTSearch::ponder() {
The only lines needing changes end with '// lizzie'

**Comment by featurecat** [comment]
Yes - it's a bit outdated. Glad you got it working. New version of Lizzie will soon work with default Leela zero.

**Comment by cdqz2014** [comment]
Oh, thank you so much. 
I replaced the corresponding lines of UCTSearch::ponder() with comments of //lizzie and it worked again!
