### ISSUE TITLE
[Question] Needed change on top of leelaz

### ISSUE THREAD

**Issue by tychota** [featurecat/lizzie#24]
## Problem

AFAIK, unmodified leelaz did not work with lizzie. It does not show anything on screen.

## Context

I want to be able spend some times learning MCTS / other tree search algorithm by modifying Leela Zero code.
I then want to use Lizzie to test modification so I can see impact of my changes (eg same network but Thomson filter instead of raw MCTS, or different pruning parameter.

## Analysis

- Leelaz is modified to output informations as it ponder https://github.com/featurecat/lizzie/blob/master/src/wagner/stephanie/lizzie/analysis/Leelaz.java#L18
- the parsing is done here https://github.com/featurecat/lizzie/blob/master/src/wagner/stephanie/lizzie/analysis/Leelaz.java#L18
- https://github.com/gcp/leela-zero/blob/5958e02cf539d42ee20704b664043036d5c3c18b/src/UCTSearch.cpp has to be modified

## Request

Can you share a diff of your modified leelaz and upstream one ?

**Comment by featurecat** [comment]
Yes. I'll upload that today. It's a very small change but really useful for lizzie :)

**Comment by tychota** [comment]
Thank you very much !

**Comment by featurecat** [comment]
Check the file: https://github.com/featurecat/lizzie/blob/master/leelaz-src/UCTSearch.cpp

Currently you can replace your default UCTSearch with this modified version; in the future, this class will change, so just add the lines that end in "// lizzie" to the ponder function.

All I need, for Lizzie, is to output data similar to this.. Maybe I can get something like it into the default Leela Zero, then we won't need to distribute our own version, or I can just make my own branch of Leela Zero.
