### ISSUE TITLE
[Question] Build Steps / Getting started

### ISSUE THREAD

**Issue by tychota** [featurecat/lizzie#25]
Can you add build steps ?

I have tried `mvn install` but that seems to make an empty / unexecutable jar file.

**Comment by featurecat** [comment]
I will try a clean install later, but, I have it as a project in intellij and you can add it as a maven project and it downloads the dependencies you need.

**Comment by tychota** [comment]
I finally made it works:
- import the project as maven
- mark `src` as source root
- copy leelaz binary (cf #24 to knon how to modify LZ) and download networks from http://zero.sjeng.org/
- go to `src/wagner/stephanie/lizzie`
- cli on the run button

![image](https://user-images.githubusercontent.com/13785185/37870092-89ea1fec-2fc5-11e8-9ea9-fd5a798f1972.png)
