### ISSUE TITLE
Handicap stones are not recorded in SGF

### ISSUE THREAD

**Issue by kaorahi** [featurecat/lizzie#250]
1. Start Lizzie
2. Hit "n" key (new game)
3. Input "3" on Handicap field and click "OK".
4. Wait until leelaz puts the first white stone.
5. Hit Ctrl-c key (copy SGF)
6. Paste it on a text editor

Then we have no handicap stones in SGF. e.g.

    (;KM[7.5]PW[]PB[]DT[2018-05-11]AP[Lizzie: 0.4];W[pd])

It occured on 21f049d (just before merging #247 "Support for new leela zero GTP format.")

**Comment by OlivierBlanvillain** [comment]
@zsalch Do we still have this issue after all the changes you made related to sgf handling?

**Comment by zsalch** [comment]
Now will be:
(;DT[2018-10-06]KM[7.5]PB[]PW[]AP[Lizzie: 0.5]AB[dd][dp][pp];W[pd])
