### ISSUE TITLE
Handicap stones does not appear after #247

### ISSUE THREAD

**Issue by kaorahi** [featurecat/lizzie#251]
1. Start Lizzie
2. Hit "n" key (new game)
3. Input "4" on Handicap field and click "OK".

Then no handicap stones appear on the board.
But lizzie behaves as if they are there (plays 3-3).

It occurred on 893a078 (just after merging #247 "Support for new leela zero GTP format.")

**Comment by featurecat** [comment]
Oh that's really strange I'll look into it..

**Comment by featurecat** [comment]
unfortunate bug that slipped into 0.5 :( I thought I fixed it... will fix soon

**Comment by akvadrako** [comment]
It would be great if there was a new release with this bug fixed.
