### ISSUE TITLE
lizzie 0.5 coming tomorrow or later this week - there is a bug...

### ISSUE THREAD

**Issue by featurecat** [featurecat/lizzie#254]
it seems the latest Leela Zero has a bug that prevents the new pondering gtp command and genmove from working together. For some reason, when ponder mode is enabled and a genmove request starts to output, it sometimes outputs a number before the actual move coordinate. Try looking at the output yourself by setting print-comms to true in the lizzie config and pressing 'enter' to play against leela-zero (make sure to re-enable the enter key in Input.java).

because of this, I am very hesitant to release Lizzie 0.5 tonight... We should probably fix this in leela-zero. I am really excited to release, but also very tired since I've stayed up hoping to release tonight. I would appreciate it if @bittsitt or others could help figure out this bug in leela-zero! Hopefully we can release Lizzie 0.5 soon. This bug seems important to fix before proceeding.

**Comment by bittsitt** [comment]
Did kaorahis fix correct this or there still a bug?

**Comment by bittsitt** [comment]
Just an observation: I added a command number which is optional in the gtp protocol (basically you just put a number in front of any command, and then the same number is returned by LZ in front of the response). This is done for all commands now. That is probably the number you see, and it is not a bug.

**Comment by featurecat** [comment]
oh I see. I assumed it was a multi-threading bug. good to know it was intentional! thanks :)

**Comment by featurecat** [comment]
I think this is fixed now. release can happen tonight hopefully.
