### ISSUE TITLE
Next version 0.3

### ISSUE THREAD

**Issue by igofun** [featurecat/lizzie#26]
When will the release be done?

**Comment by featurecat** [comment]
Sorry, I've been super busy up until now. I'm working on a lot of features for this version. It might take me 2-3 days:
- SGF loading/saving (cngoodboy)
- Move numbers / show branch variations (cngoodboy)
- Config file (cngoodboy)
- More shortcut commands
- Optimized rendering performance
- Improved graphics
- Add 32 bit windows binaries, set up a better system for mac/linux users

**Comment by igofun** [comment]
I understand
We look forward
If possible, please insert Estimate (Key:E)
thank you

**Comment by featurecat** [comment]
Leelaz doesn't output a score, how would estimate work?

**Comment by igofun** [comment]
Oh
Please forget it.
I thought it would be possible with final_score

**Comment by featurecat** [comment]
it might be possible but not for this version

**Comment by ThorAvaTahr** [comment]
just checking, the release will also update to the latest lzero release, right?

**Comment by kris-computer-go** [comment]
I think update is necessary because lizzie 0.2 and lzero 0.13 seem to dislike each other

**Comment by featurecat** [comment]
yes

**Comment by isty2e** [comment]
Currently cngoodboy's fork have the PV moves numbered only if the show move numbers option is on. Isn't it better to show move numbers of PV regardless of the option?

**Comment by featurecat** [comment]
Good suggestion. I was thinking about that change.

Another configurable idea could be, instead of move numbers, the PV moves could be displayed sequentially at a fixed rate, from beginning to end of variation, every time they update. Or maybe you could use the navigation buttons to scroll through the variation at your own pace? How would it be best to represent the variations?

**Comment by isty2e** [comment]
Personally I'd prefer them to be just shown at once without delay. But no idea about what other people like, though.

**Comment by wonsiks** [comment]
Is it possible to play pass on v0.3 ?
coz sometimes I need it.

**Comment by featurecat** [comment]
Yes, pass is implemented.

**Comment by featurecat** [comment]
Here's a few updates for 0.3's analysis features! Winrate gained a significant figure by sacrificing the % sign, font rendering is better. Playouts that exceed 1,000 are truncated. Rendering is much faster.

![screenshot from 2018-03-26 03-42-53](https://user-images.githubusercontent.com/10515890/37893033-cd8656a2-30a7-11e8-880c-e000e9849c38.png)

Hovering over a move immediately shows you what Leela Zero is thinking, without needing to skip through the variations yourself.

![screenshot from 2018-03-26 03-42-54](https://user-images.githubusercontent.com/10515890/37893038-cff6ea64-30a7-11e8-9fa3-2f8b8e81d3af.png)

Tomorrow I will improve the board graphics and we will hopefully release 0.3 :)

**Comment by wonsiks** [comment]
What if the board align to left side?
![20180326_165441](https://user-images.githubusercontent.com/37356450/37893698-5bbb00a8-30cb-11e8-80c8-0f5795f5f9da.jpg)

**Comment by isty2e** [comment]
Can the board graphic depend on external files? For example, my favorite is the [photorealistic theme](https://github.com/SabakiHQ/theme-photorealistic), so it will be awesome if the theme can be configurable. Never mind if this requires some hard work.

**Comment by featurecat** [comment]
@wosniks I'm not sure what you mean. Are you requesting that the board could be displayed like this?
![t](https://user-images.githubusercontent.com/10515890/37894064-e47a10bc-30aa-11e8-9d6d-697ab3bbb795.png)

**Comment by wonsiks** [comment]
Yes, that's what I meant...;)

**Comment by featurecat** [comment]
why? it looks like the right side of the window is being wasted to me.

**Comment by featurecat** [comment]
Oh, I see what you mean in the screenshot you added. The controls are cut off. This won't be a problem when I add an options pane at the top. That will allow you to view shortcuts at any time.

**Comment by wonsiks** [comment]
It would be great then..thanks~~~

**Comment by featurecat** [comment]
It's out! https://github.com/featurecat/releases/tag/0.3

**Comment by isty2e** [comment]
It's awesome! I really appreciate you for this great work.

**Comment by featurecat** [comment]
Thanks! By the way, in your opinion, how does the default Lizzie theme compare to the photorealistic theme? Is there anything I could do to improve it?

**Comment by isty2e** [comment]
Well, isn't it a matter of personal preference? Though if you are interested in mine, I felt like the default theme is a bit dim. I replaced stone images to those from photorealistic theme, the board image to sabaki default one, and reduced shadow_size to 50. Here is what it looks like:

![lizzie](https://user-images.githubusercontent.com/571680/38010910-11e6c3b4-3296-11e8-90a3-b3e46e873fce.png)

**Comment by featurecat** [comment]
That looks really nice! I'm glad the customization is straightforward. Thanks :)

**Comment by featurecat** [comment]
@isty2e Do you mind if I include your screenshot in the reddit post I made?

**Comment by isty2e** [comment]
Of course not. Feel free to use it for whatever you want.

**Comment by igofun** [comment]
Thank you for updating v0.3.
As one question, is there a way to display the change chart thinly?

**Comment by featurecat** [comment]
change chart? you mean, a winrate graph?

**Comment by igofun** [comment]
Hovering over a move immediately shows

**Comment by featurecat** [comment]
is it that you want the hover-stones to be more transparent? to be disabled?

**Comment by igofun** [comment]
to be transparent

**Comment by featurecat** [comment]
OK. I'll bring that back next version(0.4). there will be more customization options.

**Comment by igofun** [comment]
Thank you very much

**Comment by kris-computer-go** [comment]
Very nice look indeed of version 0.3 !
It would be nice if it's possible to toggle show branch variations on / off

**Comment by featurecat** [comment]
OK. that feature will come :)
