### ISSUE TITLE
THIS IS NOT ACCEPTABLE

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#261]
WHY HAVE WE NOT GOTTEN A NEW RELEASE YET?
WHY THE STALLING?

**Comment by featurecat** [comment]
omg this is great

no yelling please 

seriously

thanks

release is tonight... THANKS FOR BEING PATIENT!!!

**Comment by WYVYW** [comment]
Thanks for your patience, featurecat! I thought hydrogenpi would have been banned finally on github, since we did not hear anything from him anymore. But luckily we have something to lough about again...
