### ISSUE TITLE
Auto-save to SGF / Resume play feature

### ISSUE THREAD

**Issue by bvandenbon** [featurecat/lizzie#263]
On many occasions I've played a quick game,
closed the window, and only afterwards realized : 
"If only I saved that game. I still wanted to review it."
Unfortunately, it's too late, game is gone.

I think it would be cool, if after restart Lizzie would always ask: 
"would you like to resume your previous game ?"

To make it work, perhaps just always store a "temp.sgf".
we could enable/disable this feature in the properties file of lizzie.

**Comment by featurecat** [comment]
this would be a great feature to put for the next version. I would love it to work something like the Sublime Text editor: you can close a game and open it again without having to use the file explorer.

for now, on lizzie 0.5, you can set confirm-exit to true in the Config. on each exit, you have the option menu to save the sgf. it's not the same, but it might be helpful in the short term. probably your suggestion would replace that feature.

**Comment by OlivierBlanvillain** [comment]
Fixed in #298.
