### ISSUE TITLE
Lizzie crash on Mac

### ISSUE THREAD

**Issue by roy7** [featurecat/lizzie#266]
Just cross posting this in case you don't see the error report on Reddit.

https://www.reddit.com/r/cbaduk/comments/8npo6r/lizzie_version_05_released/dzyeqou/

dp01n0m1903 wrote:

> Lizzie 0.5 crashes on my Mac (10.13.4), but Lizzie 0.4 still seems to work. I'd be happy to help with debugging/testing if you can tell me what to do.
> 
> Anyway, here is the message I get:
> 

> lizzie 9: java -jar Lizzie.jar java.io.IOException: Stream closed at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) at java.base/java.io.OutputStream.write(OutputStream.java:116) at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143) at featurecat.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:301) at featurecat.lizzie.analysis.Leelaz.<init>(Leelaz.java:103) at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:38) at java.base/java.lang.Thread.run(Thread.java:844) java.io.IOException: Stream closed at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442) at java.base/java.io.OutputStream.write(OutputStream.java:116) Leelaz process ended. at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:143) at featurecat.lizzie.analysis.Leelaz.sendCommand(Leelaz.java:301) at featurecat.lizzie.analysis.Leelaz.ponder(Leelaz.java:360) at featurecat.lizzie.analysis.Leelaz.togglePonder(Leelaz.java:366) at featurecat.lizzie.Lizzie.lambda$main$0(Lizzie.java:42) at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by featurecat** [comment]
thanks. I'll followup here how it goes (talking via reddit). has anyone else used Mac with lizzie 0.5 successfully? (it's the one platform I can't test...)

**Comment by castal** [comment]
As suggested, I tried recompiling leelaz after commenting out the line, "#define USE_OPENCL" in config.h. Lizzie 0.5 seems to work with the resulting leelaz. As I mentioned before, Lizzie 0.4 works with the leelaz compiled for GPU, so maybe that will help locate whatever changed between 0.4 and 0.5.

**Comment by featurecat** [comment]
OK! that's good... so if you recompile it for gpu right now it doesn't work? could you verify that it's really the gpu?

what happens when you do "./leelaz -w network.gz" for the gpu version?

**Comment by castal** [comment]
My Bad! It seems that I copied over the leelaz that I had been using with Lizzie 0.4. That version works fine with Lizzie 0.4 but fails with Lizzie 0.5. I recompiled a fresh new version with:
    git clone -b next https://github.com/gcp/leela-zero

I really should have known better. Sorry for the false alarm! I'll edit my comment on Reddit so that people won't be misled.

**Comment by featurecat** [comment]
glad it is resolved :)
