### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by ParmuzinAlexander** [featurecat/lizzie#267]
Congratulations on the release 0.5.
There are several suggestions for the future.
1 Support seamless texture for board and background.
2 Support SVG stone.
3 Setting for background color.
4 AutoSave SGF.
5 Setting for hide score panel.
6 Show and edit SGF info.
Event _______________________ Date _______________
Black ________________________ Rank _____
White _______________________ Rank _____
Result _________________ Komi ___ Handicap _

**Comment by ParmuzinAlexander** [comment]
#263

**Comment by featurecat** [comment]
1. Why do you want this? Does Lizzie not scale well to larger screen resolutions? I don't have one available, so I'm not sure how it scales.
3. You just want a simple background-color? Couldn't you just supply your own image for the background.jpg file located in assets?
6. Currently, at least some of this is implemented. It would be nice to expand this to more options, as a SGF editor.
![image](https://user-images.githubusercontent.com/10515890/40864448-e16732dc-65c1-11e8-8759-124f144eb18a.png)

**Comment by ParmuzinAlexander** [comment]
1 I made several themes for Sabaki https://github.com/ParmuzinAlexander/sabaki-themes and wanted to similar customization for Lizzie. Seamless texture not need scale and they always fit the screen resolution. Example https://raw.githubusercontent.com/ParmuzinAlexander/sabaki-themes/master/background1.png 
2 For myself and my screen, I of course already made the background. Now background is set black, I think change this with option more correct. In addition can be used transparent texture with noise. Example https://raw.githubusercontent.com/ParmuzinAlexander/sabaki-themes/master/background2.png
If you set the background color to green it will look like this https://github.com/ParmuzinAlexander/sabaki-themes/blob/master/screenshot/background2.png No need to create a background.jpg for different colors.
3 Currently info not show players name if open SGF, only in window title. The result is not shown anywhere.

**Comment by ParmuzinAlexander** [comment]
For testing https://github.com/ParmuzinAlexander/go-themes
4 background sets, 4 stone sets, 7 board sets ~1 Mb
