### ISSUE TITLE
score estimate

### ISSUE THREAD

**Issue by WYVYW** [featurecat/lizzie#269]
It should be possible to (un-)mark single dead stones for scoring.

Why is Gnu-Go not included as a scoring/estimate tool, until LZ can estimate the score?

**Comment by featurecat** [comment]
scoring should (maybe?) be simple enough that we don't need external tools to calculate it. why do you need to unmark a single stone? do you mean group? so we don't support that already?

**Comment by WYVYW** [comment]
if i mark a dead stone like d17 it marks almost all stones unless they is not clearly seperated by the opponent.
![image](https://user-images.githubusercontent.com/38362247/40872540-52edcaea-6650-11e8-9d6a-141e4d305101.png)

**Comment by bittsitt** [comment]
It is a scoring tool for scoring a completed game, not a score estimator. Those are two vastly different things with a magnitude difference in complexity. Score estimation is hard, e.g. gnu go is not particularly good at it from what I've heard (although it might be better than nothing).

Porting the gnu go estimator is one option. Adding score estimation to Leela Zero is another. I think the second option is much more interesting, but it requires work on the Leela Zero side.

The reason Gnu-go is not included as a scoring tool is because neither you or anybody else have submitted a patch for that yet ;-)

**Comment by WYVYW** [comment]
I would be glad if could submit a patch, unfortunately my coding knowledge is just good enough to open a text editor and close it. I could offer to translate the gui to german, if there is a desire for translations.

However, in my opinion Gnu-go is good enough for estimations and would be a good addition for Lizzie.
The sample above is from the game Haylee vs. LZ. It is finished W+R. Gnu-go estimates w+8.8 
It might not be the final score, but a sufficient estimate. 

![image](https://user-images.githubusercontent.com/38362247/40878368-73365c64-6690-11e8-84a0-a440fba937b1.png)

**Comment by ParmuzinAlexander** [comment]
We have a Pro level engine for analyzes and shows who is leading. Lizzie created for this. And use GNU Go? W+8.8 what?!

**Comment by featurecat** [comment]
if we want to have a score estimator (which would be great), I want it to use Leela Zero somehow. Either we can do network/engine hacking or estimate it mcts style... Personally I want to try extracting it out of the existing network, just to try it.

**Comment by WYVYW** [comment]
@ParmuzinAlexander 
Neither Lizzie nor the Pro level engine can estimate. 
Therefore I was asking "why not GnuGo until" LZ can estimate.
I can't code, but maybe it is not a big deal for a contributor.
Hacking/modifing LZ seems a much bigger task, but if someone is able do that in the near future than forget about this issue.

**Comment by alreadydone** [comment]
[MyLizzie](https://github.com/aerisnju/mylizzie/commits/eabc33dc6257856c1648a064db14938bc1db2438/src/main/java/wagner/stephanie/lizzie/analysis/GnuGoScoreEstimator.java) does include GNUGo (also Zen) as a score estimation tool.

**Comment by ParmuzinAlexander** [comment]
@WYVYW 
GNU Go not see the status of the groups correctly if need to predict the moves. What's dead for LZ, can be alive for GNU Go. No way convert winrate to score by use GNU Go. Score like W+8.8 nonsense.

**Comment by WYVYW** [comment]
@featurecat I tried to finish the ove sample game with the help of Lizzie to see what the final result will be, but Lizzie always crashes/shuts down without any error message. The first time it just stopped pondering before shutting down. Then I set print-comms to true, but still don't see any error message.

**Comment by featurecat** [comment]
could you please upload the sgf and tell me exactly what keys cause the crash?

**Comment by WYVYW** [comment]
It is not a key that causes the crash. I just manually input the cyan moves. I once counted 20 moves before the crash, last times it took about 60 moves before crashing.
The sgf is downloaded from ogs. I will reboot my laptop and try again.
[12940129-214-RoyalZeroSlow-Haylee.zip](https://github.com/featurecat/lizzie/files/2065782/12940129-214-RoyalZeroSlow-Haylee.zip)

**Comment by WYVYW** [comment]
Laptop reboot did not help. Crashed after inputing 10 moves. 
Maybe the problem rises from the low win rate. I tried now a different sgf where the winrate is more ballanced without any problem so far.
I will be experimenting more.

**Comment by WYVYW** [comment]
@featurecat  A fresh install of lizzie probably solved the problem. Sorry for the trouble.

**Comment by WYVYW** [comment]
@ParmuzinAlexander If you play out the game until scoring works you will find that the result will be about ten points. So W+8.8 is not nonsense. 

Maybe @aerisnju can add the GnuGo score estimate, if nobody objects.

GnuGo is only about 5kyu (my level) but much faster than me estimating the result.
And those people who don't like the comfort of GnuGo's estimate, don't need to use that estimate.
It is supposed to be an optional feature until we get the Pro Level estimate.

**Comment by WYVYW** [comment]
Another idea is to provisionally implement some sabaki features.

https://github.com/SabakiHQ/deadstones
https://github.com/SabakiHQ/influence

![image](https://user-images.githubusercontent.com/38362247/40885905-9363112c-672f-11e8-966e-ef7e822469fd.png)

**Comment by ParmuzinAlexander** [comment]
@WYVYW 
I think you don't understand me. 8.8 after dot 8, not 8.0, not 8.5. This is just one game. This analysis by GNU Go (who's alive, who's dead, where the territory) in the program for analysis Leela Zero. Everyone has their own opinion. Let's get this over with.
