### ISSUE TITLE
Is there a quick and easy way to edit Sabaki code to have Lizzie's colored heatmap?

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#27]
I really like the colored heatmap of green to red, with the winnrate % and # playout dynamically shown per move ... is there a quick way for me to edit Sabaki code  to made it like Lizzie's heatmap?

**Comment by hydrogenpi** [comment]
I want to edit and compile my own version, I really like the colored heatmaps

**Comment by featurecat** [comment]
Probably -- this is an issue for the https://github.com/SabakiHQ/Sabaki, though.
