### ISSUE TITLE
suggest to use smaller background and borad image file

### ISSUE THREAD

**Issue by l1t1** [featurecat/lizzie#274]
they occupied the most of the source code size

**Comment by l1t1** [comment]
[lizzie-0.5.zip](https://github.com/featurecat/lizzie/files/2065522/lizzie-0.5.zip)
i simply ave screen0.5.png as jpg format, and save board.png and background.jpg as a blank page.
zip file drop from 6M to 960K

**Comment by featurecat** [comment]
agreed the pngs should be jpgs. but I don't think I want to ship with a blank background... I enjoy changing every version... picking a new color each release would be less fun :P

one suggestion was for tileable seamless backgrounds. this would greatly reduce the file size if we found an interesting tiling to use.

**Comment by l1t1** [comment]
![2018-06-04_205854](https://user-images.githubusercontent.com/23301704/40918843-1c475332-67f7-11e8-8b6e-9ce4b0063a34.png)
how about this icon, that is the icon of cgos

**Comment by featurecat** [comment]
someone on reddit suggested 3 stones in the shape of an L... may be a good icon for the program. I like it. I will try making it.

**Comment by ParmuzinAlexander** [comment]
For testing seamless texture https://github.com/ParmuzinAlexander/go-themes
