### ISSUE TITLE
v0.5 gets stuck on "Leela Zero is loading..."

### ISSUE THREAD

**Issue by farnaby** [featurecat/lizzie#277]
While lizzie 0.4 runs without problems with my patched custom build of leela-zero 0.13, lizzie 0.5 complains that it needs version 0.15 at least. From the release site I conclude, that this time no special patch should be needed, so I copied a standard build of leelaz 0.15 to the lizzie directory and started. Now, lizzie just gets stuck while saying "Leela Zero is loading". There's no output on terminal. Config.txt is freshly generated, everything left at defaults. I've also tried to change settings like the `leelaz` parameters, but to no avail. 
When running from terminal, `leelaz` starts quickly, since opencl tuning has already been done and saved to the same directory.

Any idea what might be going wrong here, or how I could help in debugging this?

Some boundary conditions, in case it matters: I'm using Manjaro linux, running openjdk version "1.8.0_172".

**Comment by aerisnju** [comment]
Yes it's true that you don't have to get a special patch for the official leelazero. But the builtin analysis functionality has not been published to the "master" branch(for release) yet. And you should rebuild your leelaz from the latest source of the "**next**" branch.

**Comment by BHydden** [comment]
My copy of Lizzie 0.5 also hangs on "Leela Zero is loading..." but only when I have auto-download best network set to "true"
Lizzie 0.4 worked fine with auto-download enabled but since upgrading to 0.5 it hangs on loading even if the best network has previously been downloaded manually.

**Comment by raspingbard** [comment]
I'm having the same problem on Mac OS.  I verified that my "automatically-download-latest-network" property is set to false.  I'll wait to hear from farnaby after he tries the "next" branch tonight.

**Comment by farnaby** [comment]
Yes! Using the current next branch (commit dae7011c1c8b03d4554410230015dde84118a9b7, to be precise...) lizzie now runs. Thanks for the support.

**Comment by Proton-Panther** [comment]
i am actually having the same issue.
i have compiled leela zero from the `next` branch https://github.com/gcp/leela-zero/tree/next
but it did not work.
also i do not see an explanation how or where to put the individual files.
like do i just put my leelaz file into the lizzie folder i get from unpacking the release and that's it?
i am on arch labs / arch linux btw.
any help would be very much appreciated.
i do not see how i shall get around getting stuck on "Leela Zero is loading..."

**Comment by featurecat** [comment]
Sorry that the process is not so smooth.. yes please put Leelaz into the same directory as lizzie.jar (a recent commit to this repo may have made this less necessary, but I haven't tested it yet. if youre on the release branch you should still put it in the Lizzie.jar directory.) it sounds like you're doing this already? 

enable gtp output via Config file and send it to me. also please disable auto updating of the network and download one manually or use the one that came with lizzie release. auto downloading of network broke shortly after release... I haven't released the fix yet.

failing all that, could you please screenshot your lizzie directory?

**Comment by Proton-Panther** [comment]
thank you for your response.
actually it is somehow working now.
i just compiled the `next` branch of leela zero once more and put the resulting `leelaz` file into my `lizzie` folder and now it is just working.
i literally have just compiled it again, so exactly the same as i was doing before.
but i am just happy that it works now.
and thanks a lot for this amazing tool.
it is very helpful.
