### ISSUE TITLE
Problem DLL lizzie0.5

### ISSUE THREAD

**Issue by ZeMannFred** [featurecat/lizzie#279]
Hi,

I just DL lizzie 0.5 then i unzip it and launch lizzie.jar (some stuff appears in the folder and i saw one second a goban then nothing)

I launch leelaz.exe and the program say : msvcp140.dll is missing
I found it and install it, run the program again it say : vcruntime140.dll is missing
Same as before, I re-re-run it : api-ms-win-crt-runtime-l1-1-0.dll is missing (booooring)
find it,  re-re-re-run it : "the application was unable to start correctly (0xc000007b)"

somebody HELP pleeeeaaaaaase :'(
Little information, I tried it before with the previous version and I got the same problem.

Thx

**Comment by featurecat** [comment]
did you install Microsoft VC++ 2015 redistributable? try it if not.

**Comment by ZeMannFred** [comment]
Hmm, I think the problem must be my computer, I can't install VC++ 2015 redistributable either (another error that I try to fix but....)

**Comment by featurecat** [comment]
that's confusing... the error could be anywhere if that doesn't even install. definitely try to figure out what's going wrong... sounds like it might be a potential issue for installing other software as well.

**Comment by ZeMannFred** [comment]
Ok, after a little cleaning on the computer and windows updating my rusty junk of hardware, I finally successfully installed VC++ 2017 without error.
Then re-install lizzie and it is finally work up.

Thanks for the help :)

**Comment by ZeMannFred** [comment]
Ok, after a little cleaning on the computer and windows updating my rusty junk of hardware, I finally successfully installed VC++ 2017 without error.
Then re-install lizzie and it is finally work up.

Thanks for the help :)
