### ISSUE TITLE
can lizzie offer/adopt the waltheri/wgo.js theme/color/style 

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#28]
I like the look and style of this better

https://github.com/waltheri/wgo.js

Can it be made an optional theme?

**Comment by featurecat** [comment]
Yes, the next version will have moddable themes.

**Comment by featurecat** [comment]
You can now swap out the files in the Assets folder for your own. If you do create this theme, please share it here for other users! Thanks :)
