### ISSUE TITLE
New to Lizzie need tutorial

### ISSUE THREAD

**Issue by Splee99** [featurecat/lizzie#293]
![lizzie](https://user-images.githubusercontent.com/35020997/41072923-817a88f4-69b5-11e8-98f4-6e10b3da6bcc.png)

Can anybody explain the picture above? What does the circle without number mean?

**Comment by featurecat** [comment]
the circles without number are ones with very low playouts. the blue circle indicates that move has the highest winrate value (but fewer playouts than the "best" move).

**Comment by Splee99** [comment]
OK Thanks.

**Comment by WYVYW** [comment]
There are some red dots without any numbers (so very low playouts). The blue circle has no colour filling. Should the blue the circle at least it not get also at least a red filling?

**Comment by Splee99** [comment]
This is a replay from a sgf file, I guess the blue circle is the next move? What is the top number in a circle corresponding to? I know the bottom number means visits.

**Comment by WYVYW** [comment]
AS featurecat wrote: blue circle = highest winrate with few Playouts
The next move is indicated by white or black circkles. 

The top numbers are the winrate. Low numbers= Playouts

Maybelline it might bei worth to make a helpbutton (H) with  a screenshot to show what something means.
Or what changed.
