### ISSUE TITLE
Lizzie gets stuck if the SGF has an move that has been undone.

### ISSUE THREAD

**Issue by lmhsjackson** [featurecat/lizzie#296]
I was trying to load a game from KGS, and the game can only be read (without issues) until a certain move. After that no moves where shown, but when I opened it with Multigo it displays the entire game. I realized that at that exact move the game had a miss click and an undo was conceded.

**Comment by pondturtle** [comment]
I have similar problemw here Lizzie doesn't see any move after branching when opening SGF made in sabaki software. I enclose SGF with which lizzie is exhibiting this problem. Even though there is plenty of moves in lizzie I can only see coople ones until the first branch.

[vyklep.zip](https://github.com/featurecat/lizzie/files/2129845/vyklep.zip)

**Comment by OlivierBlanvillain** [comment]
Fixed in #306.
