### ISSUE TITLE
2 GPUs lower speed than lizzie 0.4 

### ISSUE THREAD

**Issue by baduk1** [featurecat/lizzie#300]
Hello, I did not find a word about GPU in a readme file. 
I pasted it from lizzie 0.4
On 8 threads, GPU 0,1 I compared 30 seconds pondering same position.
Results: 
lizzie 0.4 ELF weights : 32k playouts 
lizzie 0.5 ELF weights: 20.3k playouts
Why is that so? How can I enhance power? 
Thanks 
 
My current config: 
{
  "leelaz": {
    "automatically-download-latest-network": false,
    "max-analyze-time-minutes": 55,
    "analyze-update-interval-centisec": 10,
    "network-file": "network.gz",
    "max-game-thinking-time-seconds": 55,
  "gpu": [0,1],   "engine-start-location": ".",
    "engine-command": "./leelaz --gtp --lagbuffer 0 --weights %network-file --threads 8",
    "print-comms": false
  },
  "ui": {
    "shadows-enabled": true,
    "board-color": [
      217,
      152,
      77
    ],
    "shadow-size": 100,
    "show-winrate": true,
    "fancy-board": true,
    "show-variation-graph": true,
    "win-rate-always-black": false,
    "confirm-exit": false,
    "handicap-instead-of-winrate": false,
    "large-subboard": false,
    "show-move-number": false,
    "show-next-moves": true,
    "show-leelaz-variation": true,
    "show-subboard": true,
    "theme": "DefaultTheme",
    "fancy-stones": true,
    "show-best-moves": true,
    "board-size": 19
  }
}

**Comment by kaorahi** [comment]
I guess that '"gpu": [0,1]' in your config may not work because "git grep gpu" hits nothing in the current code.
You may need to add something ("--gpu 0 --gpu 1" ?) into "engine-command" in your config.txt.

**Comment by baduk1** [comment]
this particular text "--gpu 0 -- gpu 1" does not work, lizzie fails to start with it

**Comment by kaorahi** [comment]
Is "-- gpu" a typo?  It is "--gpu" correctly (no space after --).

**Comment by baduk1** [comment]
I pasted what you wrote - does not work
{
  "leelaz": {
    "automatically-download-latest-network": false,
    "max-analyze-time-minutes": 55,
    "analyze-update-interval-centisec": 10,
    "network-file": "network.gz",
    "threads": 8,
    "max-game-thinking-time-seconds": 55,
    "weights": "network",
    "engine-start-location": ".",
   "--gpu 0 --gpu 1",
    "engine-command": "./leelaz --gtp --lagbuffer 0 --weights %network-file --threads 8",
    "print-comms": false
  },
  "ui": {
    "shadows-enabled": true,
    "board-color": [
      178,
      140,
      0
    ],
    "shadow-size": 100,
    "show-winrate": true,
    "fancy-board": true,
    "show-variation-graph": true,
    "win-rate-always-black": false,
    "confirm-exit": false,
    "handicap-instead-of-winrate": false,
    "large-subboard": false,
    "show-move-number": false,
    "show-next-moves": true,
    "show-leelaz-variation": true,
    "show-subboard": true,
    "theme": "wagner.stephanie.lizzie.theme.DefaultTheme",
    "fancy-stones": true,
    "show-best-moves": true,
    "board-size": 19
  }
}

**Comment by kaorahi** [comment]
I meant this:

    "engine-command": "./leelaz --gpu 0 --gpu 1 --gtp --lagbuffer 0 --weights %network-file --threads 8",

**Comment by featurecat** [comment]
oh dear, this is definitely a problem of updating the Config file... yes, follow kaorahi's advice, you now have to specify multiple gpus in the Leela Zero command.
