### ISSUE TITLE
Wrong move number color over dead stones

### ISSUE THREAD

**Issue by ParmuzinAlexander** [featurecat/lizzie#301]
Numbers 10 and 12 on black stones, but shows white dead stones. https://imgur.com/6bEfK1G

**Comment by featurecat** [comment]
I just didn't want to get around to fixing this haha. It's pretty minor... I would fix it eventually but I'm not very concerned about it.

**Comment by OlivierBlanvillain** [comment]
@ParmuzinAlexander Could you upload a sgf file?

**Comment by ParmuzinAlexander** [comment]
@OlivierBlanvillain 
`(;GM[1]FF[4]SZ[19]HA[0]KM[7.5]CA[UTF-8]PB[]
BR[]PW[]WR[]DT[]RE[];B[qd];W[dd];B[pq];W[dp];
B[fq];W[qo];B[op];W[oc];B[cn];W[pe];B[qe];W[pf];B[qg];W[dn];B[dm];W[en];
B[cp];W[cm];B[co];W[dl];B[dq];W[em];B[fc];W[fd];B[gd];W[fe];B[dc];W[cc];
B[ec];W[cd];B[jc];W[gi];B[cf];W[ch];B[dh];W[ci];B[gg];W[hf];B[hd];W[gf];
B[di];W[cj];B[pc];W[pb];B[qb];W[oh];B[gk];W[fj];B[ih];W[hg];B[qp];W[po];
B[oo];W[pm];B[om];W[ol];B[nm];W[qh];B[qf];W[kc];B[kd];W[ld];B[lc];W[kb];
B[lb];W[le];B[mc];W[pd];B[qc];W[jd];B[ke];W[kf];B[je];W[ie];B[jf];W[id];
B[jb];W[jg])`

**Comment by zsalch** [comment]
@ParmuzinAlexander 
The sgf seems not the same as mentioned in the issue.

**Comment by ParmuzinAlexander** [comment]
@zsalch 
Same. But actually there is a more global problem double move prediction in one place not shows. But how to solve I don't know.

**Comment by zsalch** [comment]
@ParmuzinAlexander 
I understand what you mean, I will provide a test version later to determine if this problem can be solved.

**Comment by zsalch** [comment]
I have a question: does need remove the dead stones when display the ghost branch?

**Comment by zsalch** [comment]
@ParmuzinAlexander 
There is a beta version here: [pre-release](https://github.com/zsalch/lizzie/releases/tag/v0.5%2B)

**Comment by ParmuzinAlexander** [comment]
Beta version work correct.
