### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by CRDE** [featurecat/lizzie#305]
While Lizzie Start this Message appears since some windows update (dunno exactly what update)

**Comment by featurecat** [comment]
are you able to run any other Java applications at all? such as KGS.

**Comment by CRDE** [comment]
wow, i can't reproduce the error. before i openend the issue i bootet windows several times (running as a VM in parallels on a mac). now, after some hours i did it again and lizzie works properly. looks ike parallels stuff, isn't it?

**Comment by featurecat** [comment]
yay I'm glad it works :) why don't you use lizzie natively on Mac?

**Comment by CRDE** [comment]
oh, didn't realize that there is simple jar. just thought i have to build myself and feared the complexity, lol
