### ISSUE TITLE
How do I show the heatmap?

### ISSUE THREAD

**Issue by Atarust** [featurecat/lizzie#31]
Hi,
after installing the 0.3 release, copying leelaz and the tuning file into the folder, then starting java -jar Lizzie.jar the board shows. Things like showing move numbering or generating a new move by Leelaz work. But how do I show the heat map or any evaluation by Leelaz?

(on Linux, using lizzie0.3 release zip)

**Comment by featurecat** [comment]
did you use Leela zero compiled from https://github.com/featurecat/leela-zero, which is the modified version lizzie needs? or did you use GCP's version?
