### ISSUE TITLE
GPU version was working a couple days ago, but stopped working suddenly

### ISSUE THREAD

**Issue by dmeff** [featurecat/lizzie#312]
I downloaded the latest release of lizzie GPU a few days ago, and it worked flawlessly.

Today, i tried to open it but it's not working. 

Tried running the included leelaz.exe alone and it got stuck at "Trying 290 configurations" after which it closed. 

Downloaded the CPU version and it works flawlessly (albeit slow, of course)

Anyone have any ideas why it stopped working all of a sudden?

**Comment by raspingbard** [comment]
What machine are you running this on?

**Comment by dmeff** [comment]
Windows 10 64 bit.
AMD-Athlon II X3 455 3.3ghz
ATI Radeon HD 4650
4Gb ram

**Comment by dmeff** [comment]
I tried compiling the "next" version of leelazero and using that, but it didn't work either

**Comment by featurecat** [comment]
Well, it sounds like the opencl optimization file is wrong since it tries those configurations before failing. Maybe the file has been corrupted? Please delete it and retry. (leelaz_opencl_tuning).

Also try reinstalling lizzie entirely. delete the directory you're currently using and try again.

**Comment by dmeff** [comment]
@featurecat That file is not there. This might be because I already tried deleting the version that was working and the new one I installed has never worked. It never generates the file.

I believe it has to do with OpenCL drivers, but I have no idea why it stopped working all of a sudden
