### ISSUE TITLE
Incompatible Leela-zero version

### ISSUE THREAD

**Issue by sedetweiler** [featurecat/lizzie#314]
New to your app, and I am REALLY happy someone is making a better interface.  However, when I try and run it, I get an incompatibility error.  I have tried .15 and .14 versions of both the leela zero and supporting .dll files as well as the generated network and I have no idea what it wants.  It runs, but it has zero brains.

**Comment by featurecat** [comment]
What about with the included Leela zero program?

What is your operating system? 64 bit windows? lizzie cpu only version as well.

**Comment by sedetweiler** [comment]
The included one also failed with the generic message.  I am using the
network mentioned in the readme.  Win 10 64bit on Intel with Nvidia gpu.
Note that the gpu version closed immediately with no error, but the
cpu version at least appears to work until the pop-up about
incompatibility.

**Comment by featurecat** [comment]
are you absolutely sure you are using lizzie 0.5? not 0.4. that's the most likely explanation I can think of at the moment.

**Comment by featurecat** [comment]
additionally please send me a screenshot of your lizzie folder?

**Comment by sedetweiler** [comment]
yes, I downloaded it from here yesterday.  I can try again with a fresh dl of all assets and see if I perhaps missed something.  It would be nice if the error spoke to the expected version to help with troubleshooting for future users.

**Comment by sedetweiler** [comment]
![image](https://user-images.githubusercontent.com/8366665/42331641-908f3334-803b-11e8-921a-8d4038a313a4.png)

**Comment by sedetweiler** [comment]
this is after a bunch of troubleshooting with different versions of lot of things, but at least it opens and doesn't immediately close without a message.

**Comment by sedetweiler** [comment]
Oh, I got it!  Finally. That was 2 hours of my life I want back. lol.  Well, keep up the great work!

**Comment by featurecat** [comment]
Ah. was it the 0.5 version of Lizzie that I as the problem?

**Comment by sedetweiler** [comment]
Actually, it was the generation of the network file.  I let leela run and
create a new network and that one works, but the downloaded one just causes
the app to abend.

**Comment by featurecat** [comment]
oh. thanks :)

**Comment by sedetweiler** [comment]
I should point out I never did get the gpu version to work, only the
cpu build.

**Comment by featurecat** [comment]
try using the gpu Leela zero exe and change nothing else.

**Comment by sedetweiler** [comment]
I did as you requested, and used the network specified in the readme and received the incompatibility error.  I then tried with my newly generated version to the same result.  To my knowledge, no network file makes the gpu version happy.

![image](https://user-images.githubusercontent.com/8366665/42341313-4ad37a86-8058-11e8-96ad-13adc352b239.png)

**Comment by sedetweiler** [comment]
Here is a screenshot showing the same leelaz exe in the gpu version as well as the handy exit when executed.  this does run on the cpu version:
![image](https://user-images.githubusercontent.com/8366665/42341879-2644dc62-805a-11e8-9592-427917c4c5ee.png)

**Comment by featurecat** [comment]
just a thought what if you name it network.gz?

**Comment by sedetweiler** [comment]
Just tried that with both the new and old network versions and get the same "process ended" using the gpu version.
