### ISSUE TITLE
Nick Sibicky has jumped on the badnwagon

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#316]
https://www.youtube.com/watch?v=P-xiROvqSZ4

**Comment by hydrogenpi** [comment]
https://soundcloud.com/user-449495344/wfstyqd71mqh

**Comment by featurecat** [comment]
Please explain what is this audio saying, for English users.

**Comment by hydrogenpi** [comment]
Okay it was my voice recorindg, long story short, LZ has reached it point of deminishing returns, the low hanging fruit is gone... we need  to find ways to move strategically if there are to be great hope for continued forwards. It is geared towards the chinese community at large hence why I recorded in Chinese, my Chinese is rough and I'm much better as English speaker actually

**Comment by hydrogenpi** [comment]
you know you've made it when the haters come out of the woodworks and 

https://www.youtube.com/watch?v=BJ54Pnpfksk
