### ISSUE TITLE
-bash: brew: command not found

### ISSUE THREAD

**Issue by bcordoba555** [featurecat/lizzie#319]
I am not a programmer, and I read in the readme.txt and it says that you need the source code and the Java version 8.  I installed Java.  When I run the command to brew I get the error message:
"-bash: brew: command not found"

I get that there is a package (?) from Homebrew called Brew but since I do not know anything I am hesitant to install something that I don't know and that the readme file does not ask to install.  

I could use some help and tips for a newbie.  Just trying to install Leela on Mac.  

Thank you!

Benoît

**Comment by featurecat** [comment]
Yes, get Homebrew. Sorry, I don't own a Mac, so I was not aware that not all Macs come with Homebrew installed.
