### ISSUE TITLE
Winrate heatmap

### ISSUE THREAD

**Issue by Gurxtav** [featurecat/lizzie#321]
I'd like a feature where Lizzie lets LeelaZ explore each legal move on the board with a specified number of visits and then displays a heatmap with colors based only on calculated winrate for each move (the difference in winrate between this position and the one after the move or something like that).

This may be a good way for me to understand good direction of play (if there are a lot of green moves on the top of the left side for example).
Also, good moves and tesujis which the policy network missed can be found by exploring every move.

Of course it would be a bit computationally expensive since there are many legal moves, but something like 100 visits per move still gives good strength and can be computed in reasonable time.

**Comment by featurecat** [comment]
oh that is pretty interesting. I imagine there would be a lot of noise with low playouts. Even 100. probably we can do this by executing the specified number of playouts on each move and writing the winrate

**Comment by WYVYW** [comment]
MiniGo has something similar. The lower right corner shows the value of the board.
![image](https://user-images.githubusercontent.com/38362247/42717514-dc06438a-8701-11e8-9f82-eefb9cafd22d.png)

**Comment by OlivierBlanvillain** [comment]
I think this would require some non trivial modifications on the Leela Zero side. Please reopen if/when implemented there.

**Comment by Diapa** [comment]
no not at all.
It is probably possible to make it better by modifying LZ, but what I am talking about is a pure Lizzie thing.
Lizzie can just sutomatically go into every move on the board, let LZ think a little, note the winrate and go back, just like I can do this manually. 
And then display it as a heatmap when every move has been looked at.

**Comment by alreadydone** [comment]
There's LZ review mode https://github.com/gcp/leela-zero/issues/1758#issuecomment-416186612 developed by @AncalagonX. He has added additional configurable options since then, but it seems he's not working on a pull request. You can use his release though.

**Comment by gcp** [comment]
>we can do this by executing the specified number of playouts on each move and writing the winrate

I agree with this. Note that you can now control the number of playouts/visits on the fly via lz-setoption.

>Changing that to "automatically go into every move on the board" would require large architectural changes.

That's unfortunate :-(

Nevertheless it makes no sense from my side to implement something protocol/engine side when it can already be achieved by the GUI. Those kind of protocol design mistakes have the unfortunate habit of potentially outliving both Leela Zero and Lizzie, which is probably why we're in the state right now where people regularly ask to make the time control parameters settable via command-line parameters...

Let's hope we can encourage people to improve Lizzie instead.

**Comment by gcp** [comment]
FYI further discussion is in https://github.com/gcp/leela-zero/issues/1675, notable whether it makes sense to add an option to make Leela less selective at the root.
