### ISSUE TITLE
File location checking is broken on next branch, works on master

### ISSUE THREAD

**Issue by infinity0** [featurecat/lizzie#323]
`next` branch in `Config.java` supports looking at PATH to auto-detect `leelaz` program. However in `Lizzie.java` and `Leelaz.java` there is logic that checks `startfolder` which uses completely different logic.

**Comment by featurecat** [comment]
OK. I would fix this in August if no one else will! sorry for not reviewing the changes to next enough.

**Comment by OlivierBlanvillain** [comment]
Fixed in #357.
