### ISSUE TITLE
Retina screen (resolution 3840X2160), Lizzie 0.3 program display blur. (Installed Java version 10)

### ISSUE THREAD

**Issue by DX3906-DX3906** [featurecat/lizzie#33]
Retina screen (resolution 3840X2160), Lizzie 0.3 program display blur. (Installed Java version 10)

**Comment by featurecat** [comment]
could you please attach a screenshot? thanks

**Comment by DX3906-DX3906** [comment]
Sorry, the resolution to fill in error, should be 3200x1800.
![lizzie 0 3](https://user-images.githubusercontent.com/37873538/38063618-98c02f60-332c-11e8-91b6-dea218b42221.PNG)
![lizzie 0 3](https://user-images.githubusercontent.com/37873538/38063623-a0d48f7a-332c-11e8-8d2e-f7ffc40fdf57.PNG)
![java 10](https://user-images.githubusercontent.com/37873538/38063641-a536deec-332c-11e8-9f17-1681f17eaa8b.png)
![3200x1800](https://user-images.githubusercontent.com/37873538/38063645-a9b50d40-332c-11e8-96c3-252ac29f9f41.PNG)
Lizzie 0.2 shows clear:
![lizzie 0 2](https://user-images.githubusercontent.com/37873538/38063695-f60813c2-332c-11e8-8cb7-3e2f036c0016.PNG)

**Comment by featurecat** [comment]
strange. I'll try to figure out what's going on.

**Comment by DX3906-DX3906** [comment]
Installing the Java 8 version will not have a fuzzy problem. If the Java 10,lizzie is installed, it still blurs.

**Comment by featurecat** [comment]
Oh that is interesting. I did not test with Java 10. I'll use that to try to figure it out.

**Comment by OlivierBlanvillain** [comment]
@DX3906-DX3906 @zsalch Is this fixed after #366?

**Comment by zsalch** [comment]
I think #366 will to improve this.

**Comment by featurecat** [comment]
I think the issue is from not using g.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY); before drawing.

I managed to reproduce this issue, and adding this code fixed it for me. So I think Lizzie 0.6 will fix this issue!
