### ISSUE TITLE
Problem running the new Lizzie

### ISSUE THREAD

**Issue by BadukBoard** [featurecat/lizzie#330]
Hi, I know next to nothing about running these sort of things but I have experienced an error. When I run the Leelaz application it does not work and just says the file MSVCP140.dll is missing from my computer and when I run the Lizzie Jar File it flashes for a second, I see the board and then crashes. Probably something I am doing wrong but thank you for your time anyway:)

**Comment by featurecat** [comment]
yeah I think that means, to run Leela zero, you need to install Microsoft visual studio runtime version 14 or higher? just download the latest one.

**Comment by BadukBoard** [comment]
Thank you so much!! I installed that program and everything works perfectly:) Thank you for your time!!

**Comment by featurecat** [comment]
yay :)
