### ISSUE TITLE
UI Loads But Not Engine

### ISSUE THREAD

**Issue by bdnelson22** [featurecat/lizzie#331]
Hi!  I'm very excited to continue learning about Go and am thrilled to have Lizzie available as a tool to help me improve.  With that said, I have been unable to successfully install and use v5.  

I downloaded the GPU version of the program and extracted to my desktop.  I then extracted the network file to the same folder, renamed it to network and deleted the file extension using cmd.  When I open the jar it loads the UI but either the engine isn't loading or it is frozen.

I set print comms to true but haven't seen an error message. 

Does anyone have any ideas?

![image](https://user-images.githubusercontent.com/41711976/43236468-48bd6a1c-9053-11e8-97f4-7ece823cdbb5.png)

**Comment by mlopezviedma** [comment]
Hi! How much time did you wait? First time you run the engine it takes some time because it tunes its options to run with your specific hardware.

**Comment by bdnelson22** [comment]
I waited over 20 minutes and have tried starting with a fresh download multiple times.  I am able to basically instantly load v4 so I know it isn't an issue with choosing GPU or with my hardware.

Here are a few more screenshots in case they help.

![image](https://user-images.githubusercontent.com/41711976/43236633-3f34331c-9054-11e8-898d-00c8fdeaa731.png)

![image](https://user-images.githubusercontent.com/41711976/43236703-8dae2908-9054-11e8-9a41-a9a11244b078.png)

**Comment by bdnelson22** [comment]
Nobody has any ideas?  No matter what I try I can't get v5 to work.  I've tried using the network file still zipped, I've tried using with file extension and without file extension.  I've tried using leelaz with .exe and without.  I don't understand the program enough to fix this and really want to be able to use the graph and the analyze function.

**Comment by bdnelson22** [comment]
Ok, so I finally figured out my issue.  Apparently everything is loaded up but I couldn't see anything happening when the window was maximized.  I needed to change the size of the window in order to make it work...
