### ISSUE TITLE
MiniGo is catching up, will the next version of Lizzie support MiniGo engine?

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#334]
Minigo has started their 19x19 v9 recently and already their best model (369 warrior) is scoring 50% against best LZ 128x10 net (39d46507).
see: http://www.cloudygo.com/v9-19x19/eval-graphs
and: http://cloudygo.com/cross-eval/eval-model/2523?sorted=True
discord: https://discordapp.com/channels/417022162348802048/433085673088614401

 they started this run last Friday... in a few more weeks if all goes well it may catch up to the 15b... and LZ has fully stalled hard core now...

**Comment by wonsiks** [comment]
Is MiniGo opened to public?
Can I download and use it via Sabaki or something?

**Comment by featurecat** [comment]
it is..

not sure if I want to do something or not. maybe we can convert Minigo weights to Lz weights again?

**Comment by alreadydone** [comment]
A script is available to convert the weights at https://github.com/gcp/leela-zero/pull/1538, but it requires tensorflow installation, and weight conversions are not done regularly and automatically. Would be nice to have a pre-compiled executable to ease the conversion ...

**Comment by featurecat** [comment]
The incentive to use Minigo isn't strong enough yet for me to do it. I'll fully support anyone's implementation on Lizzie's side, though, if they need Lizzie to change somehow.

**Comment by OlivierBlanvillain** [comment]
I don't think anyone is planning on working on this in the near future so I will close it for now.
