### ISSUE TITLE
Leela Zero has turned into a fucking disaster, with people calling for GCP's head

### ISSUE THREAD

**Issue by davidye2020** [featurecat/lizzie#335]
And demanding the project go back to 15blocks and drop the bastard out of wedlock love child that is the 20block  (which this random guy on the Internet called  bjyxo or something had created originally from a SIX block net2net but actually he "had his friend do it" and there is no saying what kind of mystery meat is in that network!) 

https://archive.is/rqd8r

https://archive.is/4rUp5

**Comment by featurecat** [comment]
ewwww no. this is also the wrong repository. please don't complain to me about it.
