### ISSUE TITLE
a web version of lizzie

### ISSUE THREAD

**Issue by ericliu24** [featurecat/lizzie#337]
Could we develop a web version of lizzie, so that go fans around the world could easily analyse their games, and improve their go skills.

Even just displaying the analysis results(winrates, variations) on the web could be greatly beneficial to the go conmmunity,  To do so, maybe we could include the leelazero analaysis data in the sgf standards.

**Comment by Zacharias030** [comment]
there is
www.ai-sensei.com
with pretty nice UI & SGF support.
