### ISSUE TITLE
gpus mode doesn't work！

### ISSUE THREAD

**Issue by Suker5692** [featurecat/lizzie#34]
Lizzie can not start when the config file was written “ "gpu": [0,1]”

**Comment by featurecat** [comment]
but it works when you write [] instead of [0,1]?

**Comment by Suker5692** [comment]
yes

**Comment by featurecat** [comment]
I'll look into it, thanks

**Comment by Climu1d** [comment]
Yeah I had the same issue... I'm rlly confused ... I downloaded the cpu z.ip and I thought I can just add the one gpu that i have by using [0,1] but i tried adding it in so many ways within the default which is []    ]
such as [0,1]   ] ... or just [0,1] without the extra line at the end being deleted..... or just putting it as [1]    ] .... and nothing works .... or if it did work.... lizz won't even come up after doube clicking it.... Help Pls I I want to add my gpu so it can be much stronger with my 8 threads

**Comment by featurecat** [comment]
so with multiple gpus it doesnt use multiple gpus at all? I don't have a machine to test.

**Comment by featurecat** [comment]
I have a jar that might? work?

**Comment by featurecat** [comment]
does this jar work at all? it wasn't designed to solve this issue but it also touches the same code: https://drive.google.com/open?id=14Kv4kX7GCCDtILns4qXn17EQXcwxuGjI
