### ISSUE TITLE
Ability to view _worst_ moves on the board?

### ISSUE THREAD

**Issue by cuallito** [featurecat/lizzie#340]
Hi, would it be possible to add a feature to show the _worst_ moves on the board, instead of the best ones? It might be more instructive for amateurs (like me) who are really just learning to avoid blunders, starting out.  Thank you.

**Comment by featurecat** [comment]
That's sort of interesting.. Of course, the worst moves will be on the first line, which would be distracting, since you want the worst reasonable moves. What if you review using a weaker version of Leela zero? maybe one that is only a few ranks stronger than you?
