### ISSUE TITLE
Lizzie Winrates

### ISSUE THREAD

**Issue by aodesky** [featurecat/lizzie#341]
Forgive me if I'm simply being impatient; I'm a first-time user. I've had Lizzie open for over three hours with an SGF file from a game of mine loaded in. It says Pondering On and it is taking up all of my CPU, so presumably something is happening. I pressed 'a' to get it to "analyze", and entered '100 playouts' (the lowest suggested parameter) in the dialog box which came up at the beginning. Thus far I don't see any progress, and it's still just showing the game. The winrate graph is empty and there are no colored markers on the board. What's going on? Does it really take this long every time to analyze a single game? Is there a progress indicator? Or an indicator that it's working and not just stuck in some infinite loop? I know that the LeelaZero engine is working because I can play a new game with LeelaZero and it makes sensible moves. 

Yes, I am running Java 8 and I also downloaded the correct branch (next) of LeelaZero. No, I do not have a GPU (should I not even bother with trying to analyze then?); Yes, I compiled LeelaZero with the OpenCL setting turned off and I modified the engine command in Lizzie's config file so that it wouldn't try to run with GTP; Yes, I have a working weight file.

Thank you.

**Comment by Atarust** [comment]
Some ideas to try, but not sure if they solve your problem.

First, if you are windows, you can just install the precompiled release without having to install leela separately.

Have you tried closing Lizzie and reopen it? Pressing a only works if you are not in the last move of the game. Do you see the heatmap (moves highlited green/red-ish and one turquise that show leelas winrate)? Normally what a does is, it looks at the current state, then the numbers on the heatmap increase until they add up to 100 and then it automaticcally goes to the next move that was played in the game. So unless you see the heatmap with rapidly increasing numbers (even the slowest computer should not take much more than a second to increase the playout counter by one.

**Comment by aodesky** [comment]
Thank you for the comment. I am running it on Ubuntu 18.04.1 LTS. I do not see any heat maps nor do I see any winrates at all.
