### ISSUE TITLE
Port to javax.json instead of org.json

### ISSUE THREAD

**Issue by infinity0** [featurecat/lizzie#345]
Hi I'm trying to package this for Debian. There's one major problem, org.json isn't in Debian due to [licensing issues](https://wiki.debian.org/qa.debian.org/jsonevil). There is a replacement from the Android project but the API is different, `JSONException` is for some stupid reason a [checked exception there and all the methods `throws` it](https://developer.android.com/reference/org/json/JSONObject) so if I try to use it with Lizzie I get compile errors. Thanks Google! These are in theory fixable with a Debian-specific patch wrapping everything in a `try {} catch {}` but that is a bit pointless.

Java these days has a JSON parser in its stdlib and the parse exceptions are all unchecked. Could you migrate please? e.g. see here https://docs.oracle.com/javaee/7/api/javax/json/JsonObject.html

**Comment by infinity0** [comment]
Looks like javax.json is an immutable API and changing config values is pretty awkward (create a builder from the old json object, add a new value, build it, rebind this new object back to the old variable).

Google's GSON library is another alternative. https://github.com/google/gson

**Comment by infinity0** [comment]
I figured out a way around this, closing for now.

**Comment by featurecat** [comment]
OK! what was the alternative way?

**Comment by infinity0** [comment]
I added a hacky patch on top of Android's org.json reimplementation to provide the newer unchecked API, and uploaded both versions to Debian.
