### ISSUE TITLE
which commits do I need for lizzie support in leelaz?

### ISSUE THREAD

**Issue by ThorAvaTahr** [featurecat/lizzie#346]
I have been working on a different tree search for Leelazero. I would like to test it and require the lizzie interface for diagnostics. I have based my tree search on leelazero - base branch - as the leelazero next branch does not work for me (it crashes my graphics driver and i cannot get it resolved, see https://github.com/gcp/leela-zero/issues/1690). 

Now i just tried to cherrypick the commits that add lizzie support to leelaz, but it fails as i get the message that 'This version of Leela Zero is incompatible with Lizzie, Please follow the instructions in the readme'. 

I have used the following commits (by pull # in leelazero next branch)
https://github.com/gcp/leela-zero/commit/893a0786b5571cc23a0c68336746c7c3ca4603a4
https://github.com/gcp/leela-zero/commit/62ddf58027da1b2952f0934eddd820a11d3879b8
https://github.com/gcp/leela-zero/commit/9fd7542d7b918f432c9ab985433ea42565edf1f1
https://github.com/gcp/leela-zero/commit/6e847e134df63bc15fe1fa4c2c1989f37bf225a7
https://github.com/gcp/leela-zero/commit/237b5785aed91faceb7defcc6070e80373c4fb0d

**Comment by featurecat** [comment]
really... It should always be compatible ever since https://github.com/gcp/leela-zero/pull/1388

**Comment by featurecat** [comment]
oh really? are you sure you're using the right most recent code for lizzie? that's an old thing. I'll check.

**Comment by featurecat** [comment]
I checked the code base and that string doesn't exist anymore. I'm pretty sure you have old code. update your lizzie!!

**Comment by ThorAvaTahr** [comment]
yeah, i just found out... omg. i spend more than a week on this (first debugging the next branch as it is killing my graphics driver for unknown reason and now on getting lizzie to work) ... it works fine now, I have updated to lizzie 0.5 no problems

thx for bearing with me.

**Comment by featurecat** [comment]
absolutely! how are you modifying the tree search for lizzie? it's pretty interesting to me

**Comment by featurecat** [comment]
for Leela zero*

**Comment by ThorAvaTahr** [comment]
Well I am trying a bayesian approach, using the policy Network outputs as priors for initializing a gaussian winrate distribution and updating that gaussian with playouts. I have the math worked out and will publish the entire story, but first i have to do some debugging and get some data. 
Thanks for your interest!
