### ISSUE TITLE
Lizzie show winnrate, variations

### ISSUE THREAD

**Issue by justafoolishfool** [featurecat/lizzie#349]
I'm running LeelaZero on my Mac, Lizzie isn't showing any of the variation or win rate info.

When I press x to bring up the controls, some of the controls work, but others don't.  For instance, I can toggle move numbers and co-ordinates and I can start a game against LeelaZero, and I can force Leela to move, but I can't access the win rate or variation info.  

If I hold down 'v' or 'w' or 'z' nothing happens.  Also, the "Leela Zero is loading" text never disappears, even when I'm playing Leela.

Here's all the version info if anyone has ideas . . . thanks!

MacOS 10.13.6
Java 10.0.2
Lizzie 0.5 -  a82c8ec

**Comment by featurecat** [comment]
it's Mac so my suspicion is an opencl problem. compile Leela zero without opencl

**Comment by justafoolishfool** [comment]
i did a fresh build with //#define USE_OPENCL in config.h . . . and still same problem.  any other ideas?

thanks!

**Comment by justafoolishfool** [comment]
thanks — went back to leela zero, and there was a new release on the next branch — commit  bd36100.  that one works!
