### ISSUE TITLE
About display comment of sgf and read/write sgf with variation & Winrate.

### ISSUE THREAD

**Issue by zsalch** [featurecat/lizzie#350]
First of all, I am very grateful for the amazing program.

It has helped me a lot.

However, I hope that can see the comments of the sgf when review the game, and I also hope to save the variation and Winrate.

I guess the author must be very busy, I can't wait and to try to make some minor changes.

1. Add the display the comment of the sgf (C tag): Forgive me very lazy, directly displayed under the variation panel, please ignore the ugly style :(
2. Add the ability to read and write the sgf with variation
3. By the way, write the Winrate in the comment of sgf for each step (C tag): Just a little try

Attached the codes and files, the code base on the release 0.5, and use the class (WrapString) of the Jim Menard. Thanks Jim Menard.
There are not many changes, not list the differences.

Just a reference for those in need.

Sorry for use the Issue because I can't find the author E-mail.
If not suitable, please remove it.

Looking forward to related functions of next release.

Thanks again.

**Comment by featurecat** [comment]
Hi

I am happy to introduce changes like these. Please make a pull request (on the Next) branch. it becomes easy to merge and review changes. I will merge when you do that (or I might request some changes if I see potential bugs) 

Thanks for your contribution

**Comment by zsalch** [comment]
Thanks for your reply.
I got it and will to try.
Screen attach failed.
<img width="1280" alt="screen" src="https://user-images.githubusercontent.com/42595514/44468248-5e582280-a657-11e8-8988-08f53db40fdf.png">

**Comment by featurecat** [comment]
uh oh that screenshot looks like Leela Zero assumed the next move has already been played. bug

**Comment by featurecat** [comment]
the comment space on the right looks good though

**Comment by zsalch** [comment]
When open the sgf with the variation, the Winrate looks wrongs.
Switch branch between the variations, the Winrate looks normal:
![image](https://user-images.githubusercontent.com/42595514/44470652-dd038e80-a65c-11e8-960f-fca7c80f6107.png)
May be miss some things when load the variation?

**Comment by zsalch** [comment]
Attached the changed codes & test sgf.
Create pull request later
[20180822.zip](https://github.com/featurecat/lizzie/files/2310876/20180822.zip)

**Comment by zsalch** [comment]
new update:
fix the Winrate wrong when load the sgf with variation. #352 

>> uh oh that screenshot looks like Leela Zero assumed the next move has already been played. bug
