### ISSUE TITLE
Feature-request: Blunder check mode

### ISSUE THREAD

**Issue by killerducky** [featurecat/lizzie#351]
I would like to have ponder, current winrate, last move +/-, and eval graph all on. But turn off the board display of winrates and variations. This way I can play out moves/variations live and notice when LZ says I made a mistake, but I won't know what the correct move is. I can undo and try again until I find what LZ thinks is a better move.

**Comment by fsh** [comment]
I've sorely wanted something like this too, had a hack for forcing it to turn off variations on board, but it required a different copy and wasn't a very good solution.

But actually found a project based on Lizzie has this very thing: https://github.com/aerisnju/mylizzie

They don't have any releases so you'll need to compile it yourself, but it's pretty great. You can turn off on-board move suggestions with a keyboard shortcut and still keep doing variations etc., having it either list the moves that were less than so-and-so many negative diff from last move in value score, or when you notice the graph plummets.

**Comment by AncalagonX** [comment]
I would prefer a display like Crazy-Sensei has, which is a bar chart with one bar per move showing how much the winrate changed on that move.

Example:

![2018-10-01_20-34-25_ chrome](https://user-images.githubusercontent.com/37827291/46286339-cdf7f080-c5b9-11e8-927e-e6f18fad47c2.png)

The blue line shows winrate, with a small middle divider line at 50% tie winrate. The red bars are what I am talking about.

A red bar *above* the middle divider line means white made a mistake that moved the winrate higher in favor of black. Likewise, a red bar *below* the middle divider line is a black mistake, which moved the winrate in favor of white. The size of the red bar indicates the degree of winrate change (i.e. how big of a blunder it was).

This has always been the best implementation/visualization for "blunder detection" I've seen to date. I find it to be much more immediately informative than just looking at the simple winrate line graph.

**Comment by AncalagonX** [comment]
Here's move 137 from that game above, the biggest "blunder" of the kifu. It was a game against LZ from many, many, many moons ago:

![2018-10-01_20-43-04_ chrome](https://user-images.githubusercontent.com/37827291/46286776-54610200-c5bb-11e8-9ab8-62fbf202a175.png)

The blue square on the board is the blunder, where black (LZ) played next. The [1] [2] [3] on the board are the best three sequences that Crazy-Sensei found. [Full game here on Crazy-Sensei.](https://www.crazy-sensei.com/?lang=en&location=game&game=845&move=1)

I'd be super happy for a long time just having the "red bar graph" implemented and nothing else.

**Comment by featurecat** [comment]
this feature looks so good. I would love to have it too!

**Comment by phiming** [comment]
Press ctrl-z,  lizzie will display  a clean board, and lastmove's rate rise/fall.  

Is this what you need?

**Comment by phiming** [comment]
Sorry, press shitf-z,  NOT ctrl-z.  
I also agree that current last move rate display is useful but not graceful

**Comment by zsalch** [comment]
I'm trying do it, but the display does not look very good, maybe someone can make some suggestions.
![image](https://user-images.githubusercontent.com/42595514/46515145-9aa4b280-c894-11e8-8737-e8ef480bc4fc.png)

**Comment by zsalch** [comment]
More moves:
![image](https://user-images.githubusercontent.com/42595514/46519545-4b1db100-c8ab-11e8-9ebd-56a5c2a34ea0.png)
