### ISSUE TITLE
Problem with 'make' terminal command on mac

### ISSUE THREAD

**Issue by unjax** [featurecat/lizzie#358]
I'm trying to compile Leela Zero in order to make Lizzie work on mac. 

Installed lizzie from here:

https://github.com/featurecat/lizzie/releases/tag/0.5

I opened the readme.txt and followed the instructions for mac:

	### Example of compiling Leela Zero - macOS ###
		# Clone github repo
		git clone -b next https://github.com/gcp/leela-zero
		cd leela-zero/src
		brew install boost

		## OPTIONAL: if you want to compile the CPU-only version of Leela Zero, open config.h and replace the line
		##     #define USE_OPENCL
		## with
		##     //#define USE_OPENCL

		# Compile Leela Zero
		make

		# Move the resulting 'leelaz' program to your Lizzie directory
		mv leelaz %DIRECTORY_OF_YOUR_LIZZIE_FOLDER%/leelaz

Note: homebrew is required for the 'boost' command, something I've seen on a few other issues boards. I got homebrew installed, allowing me to install boost. 

Everything works fine, but when I run the 'make' command, I get the following output:

3 warnings and 2 errors generated.
make[1]: *** [Tuner.o] Error 1
make: *** [default] Error 2

The leelaz program doesn't get created, and if I try to launch Lizzie, it's still stuck on the loading screen as (I assume) a result. 

If anyone could help out, I'd greatly appreciate it. Otherwise I might try redoing the entire process from scratch to see if some random error occurred. 

Cheers,

Unjax

**Comment by unjax** [comment]
Update:

The problem is fixed if I run the CPU only version. 

I have an Intel Iris Graphics 6100 1536 MB graphics processor.

IIRC this has a 'dynamic' gpu feature (no idea what that means). I'm not sure why it won't allow me to run the gpu version.

**Comment by TFiFiE** [comment]
The `next` branch of LZ is (partially) broken right now (gcp/leela-zero#1809).
Until it's merged, apply gcp/leela-zero#1811 manually or change the `clone` line to:
`git clone -b patch-1 https://github.com/TFiFiE/leela-zero`

**Comment by gcp** [comment]
Should be fixed now.
