### ISSUE TITLE
Nullpointer exception on startup

### ISSUE THREAD

**Issue by farnaby** [featurecat/lizzie#36]
Hi!

I've had a look at the screenshots and am very keen to try out the GUI.
But, when trying to start Lizzie 0.3, I only get the following output:

```
time_left b 0 0
Using 2 thread(s).
RNG seed: 13477237188667865876
Using per-move time margin of 0.00s.
Detecting residual layers...v1...128 channels...10 blocks.
BLAS Core: Haswell
= 

java.lang.NullPointerException
	at wagner.stephanie.lizzie.analysis.Leelaz.parseLine(Leelaz.java:122)
	at wagner.stephanie.lizzie.analysis.Leelaz.read(Leelaz.java:155)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This is on Ubuntu 16.04, no GPU running (I've disable OPENCL via compile flag in leelaz). I've tried with different Java versions (OpenJdk 8, 9, Oracle JRE 10), always resulting in the same NullPointerException. Customized Leelaz in textmode runs fine.

**Comment by featurecat** [comment]
I know what this bug is. it's pretty simple to fix hopefully. I'll fix it and update the release... watch this space :)

**Comment by featurecat** [comment]
Try this jar instead. Let me know if it works.
[lizzie031.zip](https://github.com/featurecat/lizzie/files/1857896/lizzie031.zip)

**Comment by farnaby** [comment]
Yes! It runs now. Thanks. :+1:
