### ISSUE TITLE
About Custom Theme by Images & Configuration file.

### ISSUE THREAD

**Issue by zsalch** [featurecat/lizzie#361]
Lizzie now supports custom theme, but its requirements may be a bit high and require a jar file.
I think it may be easier for more users to use image files or configuration files directly.

I made a simple solution that would allow you to customize the Theme directly from external images. Of course, this is only the first step. You can only modify the background, the board and the stone, and will support more UI settings in the future.

Here's an example, here I'm trying to define a look like Sabaki, of course just similar. I really like the appearance of Sabaki, so I used Sabaki's image file directly. If it is an offense to the original author, I will delete it.
![image](https://user-images.githubusercontent.com/42595514/45597830-3369b000-ba04-11e8-827a-b0b54051e5ad.png)

The configuration method is as follows:
    a) Change the 'theme' value to 'Custom' (which is a fixed value) in the config.txt file:
        "theme": "Custom",
    b) Add a new item "custom-theme" to specify your theme name:
        "custom-theme": "<your-theme-name>",
        for example:
        "custom-theme": "sabaki",
    c) Create subfolders in the lizzie folder, attached please find the sample theme (theme.zip, I really like the appearance of Sabaki, so I used Sabaki's image file directly. If it is an offense to the original author, I will delete it.):
        <lizzie-folder>/theme/custom/<your-theme-name>
        for example:
        <lizzie-folder>/theme/custom/sabaki
    d) The custom-theme folder must contain the following images, the names must be the same, feel free to use your favorite images:
        background.jpg
        board.png
        black0.png
        white0.png
    e) Run the Lizzie. Enjoy it.

The modified Lizzie file and more sample files, I published a pre-release for testing. Welcome to test and suggest: (This Pre-release may be updated frequently)
https://github.com/zsalch/lizzie/releases/tag/v0.5%2B

**Comment by ParmuzinAlexander** [comment]
I see your fork supports seamless texture, this added in lizzie/next branch? How about SVG stone? 
More texture here https://github.com/ParmuzinAlexander/go-themes
#267

**Comment by zsalch** [comment]
Not yet in the next branch, just a beta version in my fork.
I'll create a pull request when the testing is passed.

About svg stone, it will be considered after completing the configurable theme and font.

The 'go-themes' is beautiful,  maybe you will have better suggestions for beautifying Lizzie.

**Comment by hred6** [comment]
Why the appearance of Sabaki can't be made into a lizzie interface？

**Comment by hred6** [comment]
Why the appearance of Sabaki can't be made into a lizzie interface？
Directly apply the numbers represented by Lizzie stone？

**Comment by OlivierBlanvillain** [comment]
Fixed in #366.
