### ISSUE TITLE
Lizzie does not autosave because "persist" never gets "autosave" added to it

### ISSUE THREAD

**Issue by AncalagonX** [featurecat/lizzie#397]
Using Lizzie /next/ built today (and any built ever since the original autosave PR #298), autosaving is broken because the "autosave" entry is always missing from the `persist` file. Deleting `persist` and having Lizzie regenerate from scratch also never adds the "autosave" entry.

Lizzie should add the "autosave" line to the `persist` file automatically, but it doesn't right now.

Here is an example of a working `persist` file that autosaves to the persist file:

```
{
  "autosave": "",
  "ui-persist": {},
  "filesystem": {"last-folder": "C:\\Lizzie_SGFs"}
}
```

It seems all autosave functions work properly though (autosave time interval, auto-reloading board state, board change detection, etc.), as long as we add the above "autosave" line to the `persist` file. The solution for making this happen is probably straightforward for those who know Java better than me.

**Comment by featurecat** [comment]
That's amusing. it should be a simple fix, really silly that this hasn't been enabled all this time! Thanks.

**Comment by kaorahi** [comment]
thx for your informative report. I fixed it.

**Comment by AncalagonX** [comment]
@kaorahi 	Thanks so much for this awesome feature! It's definitely needed and it works beautifully as you've implemented it. :)
