### ISSUE TITLE
Lizzie for game analysis

### ISSUE THREAD

**Issue by kris-computer-go** [featurecat/lizzie#4]
It would be great tool if one can open sgf file and jump to choosen move number :)

**Comment by CamWagner** [comment]
Okay, I will add this for one of the next few versions. Thanks for the suggestion.

**Comment by tanguocn** [comment]
Next version，we hope increasing the following function key 1. Only analysis black or analysis white ; and you can edit the situation, freedom in any situation, set black go or set white to go freely.   and display black or white win rate  (set to black to go or wihite to go ) 3, display; will recommend the best go with the red circle or blue instead yellow ,easey to catch

**Comment by tanguocn** [comment]
add function key:   free set komi , handi 1-20

**Comment by featurecat** [comment]
Added for 0.3 release. I didn't add jump to specific move number per se, but holding down ctrl while going back/forwards will now do it 10 times as fast, so it should be no problem.
