### ISSUE TITLE
Lizzie does not Run on Win 10 :(

### ISSUE THREAD

**Issue by a2ens** [featurecat/lizzie#406]
The UI windows briefly flashes and then closes. 
And it doesn't matter if I run CPU or GPU version.
When I run it from "cmd" with "java -jar Lizzie.jar" it says "Leelaz process ended." And that's all...

Java (1.8.0_191) installed.
Visual Studion Community 2017-15.8.7 installed.
Win 10 ver 1809 (17763.55) (macbook pro 2017, Boot Camp).

When I try to install "vc_redist.x86.exe" (as you recomended in previous thread) it comes with error message: "error 0x80070666 - there is another version of this product installed on this computer"... 

<img width="241" alt="default" src="https://user-images.githubusercontent.com/26697316/47269872-63105880-d56c-11e8-9ecd-fe865291b16c.PNG">

Please Help Me!)

**Comment by Atarust** [comment]
Can you try running leelaz in cmd? What is the error?

**Comment by a2ens** [comment]
> Can you try running leelaz in cmd? What is the error?

 no errors, just "Leelaz process ended."

![tempsnip](https://user-images.githubusercontent.com/26697316/47273062-d038e380-d596-11e8-972b-c878ff8ab14f.png)

**Comment by Atarust** [comment]
The problem might be with Leelaz and not Lizzie. if you type in
$ leelaz -w weights.gz  (I am uncertain about the windows syntax, I am using linux)
you can start Leelaz without Lizzie. Make sure a weights.gz file exists in folder lizzie.

**Comment by petete1** [comment]
Do you have a x64 processor? The version of leelaz that comes with Lizzie doesn't run on x86.
