### ISSUE TITLE
Is there an option to NOT re-use tree search?

### ISSUE THREAD

**Issue by Strappa71** [featurecat/lizzie#408]
Sometimes I get very different results from analysis if I save a position and close and reload it and start from a specific move# compared to re-use of the search tree.

If there isn't such an option I would appreciate if it was added.

**Comment by OlivierBlanvillain** [comment]
One way to start a new search from a clean search would be to configure multiple engines (all using the same weights), then switching to a new engine let's you analyse the position without re-using the tree search.
