### ISSUE TITLE
[Question] Can I use Lizzie like look&feel for my app?

### ISSUE THREAD

**Issue by y-ich** [featurecat/lizzie#409]
@featurecat san,

I am making a Go AI app for iOS.
For study, I adopted Lizzie look&feel as below.

![img_16fe2d5aebbd-1](https://user-images.githubusercontent.com/922001/47545507-a2052c00-d927-11e8-9d87-17bb7f435674.jpeg)

Is it acceptable for you?
I will be grad if you permit to use your design.
I respect for your right of your design, so if it is not acceptable, I will change the design of my app.

Thank you.

**Comment by OlivierBlanvillain** [comment]
Yes.

**Comment by y-ich** [comment]
Thank you!
