### ISSUE TITLE
Do not forbid long cycles

### ISSUE THREAD

**Issue by alreadydone** [featurecat/lizzie#410]
https://github.com/featurecat/lizzie/blob/edec38890e80fad71953fc9ab046b0b184c53295/src/main/java/featurecat/lizzie/rules/Board.java#L401
https://github.com/featurecat/lizzie/blob/edec38890e80fad71953fc9ab046b0b184c53295/src/main/java/featurecat/lizzie/rules/BoardHistoryList.java#L176

Lizzie implements *situational* superko, in contrast to *positional* superko implemented in Leela Zero. Self-play games are generated and networks are trained with the rule in effect, but LZ does not forbid moves leading to a superko position (even suicide of one stone), and can function (genmove, lz-analyze) normally. Moreover, the superko rule is not enforced in practice in competitions and on Go servers. With superko in effect, people won't be play out triple ko etc. in Lizzie, which is not good for an analysis tool, considering that many human games were drawn due to triple/quadruple-ko infinite repetition, and that someone has lost an online game using Lizzie due to inability to input his opponent's superko-forbidden move. I suggest that Lizzie only detects and forbids immediate recapture of ko.

**Comment by featurecat** [comment]
I'm interested to hear more about how someone lost a game? do you have more information? I'd like to see the position.

**Comment by alreadydone** [comment]
It's a quadruple ko situation in [this game](https://github.com/featurecat/lizzie/files/2521484/kilerwhale.vs.2016.1539371820010001343.sgf.txt). Since the Fox server doesn't forbid long cycles, black chose to repeat the cycle and I think move 217 is the first move forbidden by superko, hence all subsequent moves are rejected by Lizzie. Then, when black ends one of the ko, white can no longer use Lizzie and therefore resigned. White actually usually uses mylizzie but I think it's good to fix it in Lizzie as well. Maybe we can detect and label superkos but not forbid them.

**Comment by OlivierBlanvillain** [comment]
I agree, we should remove this constraint from the lizzie side.

@alreadydone would you like to give it a shot?

**Comment by zsalch** [comment]
I can only say that this discussion is too timely.
I am now fixing a problem: when reading sgf, since the branch will remove some stones and continue move, the result is that the move superko in the main trunk and directly skips the move. .
Based on this discussion, let us try to remove this constraint first.
