### ISSUE TITLE
lz-analyze output changed in lz 0.16

### ISSUE THREAD

**Issue by ParkJunYeong** [featurecat/lizzie#418]
Updated lz to 0.16, lz-analyze output is changed.
Similar to the previous one, however, 'prior' attribute has been added.
So now it is printed as "info move ~ visits ~ winrate ~ prior ~ order ~ pv ~"
But current lizzie can't parse it correctly. As a result, variation is not properly shown.

Below is lz's source code.
<pre><code>std::string get_info_string(int order) const {
    auto tmp = "info move " + m_move
      + " visits " + std::to_string(m_visits)
      + " winrate "
      + std::to_string(static_cast<int>(m_winrate * 10000))
      + " prior "
      + std::to_string(static_cast<int>(m_policy_prior * 10000.0f));
      if (order >= 0) {
      tmp += " order " + std::to_string(order);
      }
      tmp += " pv " + m_pv;
      return tmp;
 }
</code></pre>

**Comment by zsalch** [comment]
I'll test it.

**Comment by alreadydone** [comment]
Isn't prior already supported in the next branch?

**Comment by zsalch** [comment]
@ParkJunYeong 
May be you can try the [pre-release.](https://github.com/zsalch/lizzie/releases/tag/v0.5%2B)

**Comment by featurecat** [comment]
We will release a new version soon based on the next branch. Don't worry :)

I'm going to reopen until we get this fixed since this issue contains the answer to the problem.

**Comment by featurecat** [comment]
Fixed https://github.com/featurecat/lizzie/releases/tag/0.6
