### ISSUE TITLE
Can't load incomplete games?

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#42]
When I try to load an SGF that I recorded with SmartGo Kifu, nothing happens (although the program does not hang). Loading games from KGS works fine. My first guess is that Lizzie is not able to load games that don't have an end and a result, but I'm sure there are plenty of other differences between SGFs from the two sources that could possibly account for it.

**Comment by cngoodboy** [comment]
I was fixed this bug, I will publish a pre-release in my forked repository.

**Comment by dfannius** [comment]
This was indeed fixed when @cngoodboy's pull request #45 was merged.
