### ISSUE TITLE
Any chance of an official release?

### ISSUE THREAD

**Issue by fohristiwhirl** [featurecat/lizzie#421]
With LZ 0.16 out, this would be a good time for a release, if Lizzie is compatible with it?

Many people (like me) struggle to actually build it from source.

**Comment by pondturtle** [comment]
You can just put LZ 0.16 into Lizzie folder and it will work. Though it behaves choppy, does not display variations and has few other minor kinks..

**Comment by featurecat** [comment]
Yes I am hoping to release today. I meant to do it yesterday, but I got sick. Sorry for all the delay.

@pondturtle any interesting kinks I should be aware of? I know the variations refuse to show with Lizzie 0.5.

**Comment by fohristiwhirl** [comment]
Excellent, thanks.

**Comment by pondturtle** [comment]
> 
> 
> Yes I am hoping to release today. I meant to do it yesterday, but I got sick. Sorry for all the delay.
> 
> @pondturtle any interesting kinks I should be aware of? I know the variations refuse to show with Lizzie 0.5.

As I said. Interface at times acts choppy and has latency showing results after new move on occasion. Also colours of moves changed for some reason and I can't tell anymore what move LZ would actually play anymore.
![schranka 01](https://user-images.githubusercontent.com/28937761/47963799-0cf1e980-e031-11e8-8d90-4f262a59efc6.jpg)

(take care of yourself too. I wish you speedy recovery. Users can wait, Health matters! ;-) )

**Comment by featurecat** [comment]
I haven't experienced the latency, I hope it goes away magically for you with 0.6. Color order is fixed in 0.6 :)

Thanks

**Comment by featurecat** [comment]
Releasing soon, sorry about the wait... lots of exciting changes :)

**Comment by wonsiks** [comment]
@featurecat You're awesome...!!  :)

**Comment by d7urban** [comment]
> Releasing soon, sorry about the wait... lots of exciting changes :)

How exciting are they? ;)

**Comment by featurecat** [comment]
Super exciting. https://github.com/featurecat/lizzie/releases/tag/0.6
