### ISSUE TITLE
Hiding panels slows ui

### ISSUE THREAD

**Issue by ParmuzinAlexander** [featurecat/lizzie#424]
Hiding 3 panels (variation-graph, comment, winrate) slows ui (increases CPU usage) LZ variation shows with a delay after mouseover. Beta version works fine so I guess it's not my computer's problem. upd: Latest beta version works like 0.6.
Also if deleted config.txt, new config.txt contains wrong "engine-command".

**Comment by ParmuzinAlexander** [comment]
I made video.
https://yadi.sk/i/qK5Kka0-rDX2wg
Beta version before this commit https://github.com/zsalch/lizzie/commit/700a46d812b16bec60723c42ef44e6cb1646c64d works fine.

**Comment by featurecat** [comment]
oh it's only when you hide? very interesting... please give me some time to investigate.

**Comment by zsalch** [comment]
The 700a46d commit expanded the tree container, which contains the comment panel. Maybe this is the reason?
