### ISSUE TITLE
lizzie 0.6 "Leelaz process ended." even using the next branch's leelaz 

### ISSUE THREAD

**Issue by scaomath** [featurecat/lizzie#426]
I compiled leelaz binary from the next branch in gcp's repo.

after `java -jar lizzie-0.6-shaded.jar`, I just got 

![lizzie](https://i.imgur.com/3e2doHw.png "Loading forever")

with the cursor still blinking.

I am on macOS mojave.

**Comment by featurecat** [comment]
Please try:

Copy the engine-command from lizzie's Config. run it in the command line in your lizzie directory, replacing network file with your weights file. Does it run?

If it does, also try setting print-comms to true in Config and posting the result.

**Comment by scaomath** [comment]
Wow thanks for the quick reply. 

The result is certainly interesting:

`Error in OpenCL calculation: Update your GPU drivers or reduce the amount of games played simultaneously.
Both single precision and half precision failed to run.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to initialize net.`

It now seems to be a problem with the OpenCL on macOS. Not a problem on Lizzie. I will try to find a solution on that one.

**Comment by scaomath** [comment]
> Please try:
> 
> Copy the engine-command from lizzie's Config. run it in the command line in your lizzie directory, replacing network file with your weights file. Does it run?
> 
> If it does, also try setting print-comms to true in Config and posting the result.

Hi, featurecat

I re-compiled leela zero 0.16 using CPU only toggle as follows:
`cmake .. -DUSE_CPU_ONLY=1`

Now everything works on macOS now. I guess I need a new computer that has a GPU...

**Comment by featurecat** [comment]
Excellent. Yes almost every Mac user I've spoken to has to use cpu mode. I don't know why exactly. I'm so glad it can work for you :)
