### ISSUE TITLE
Test failures when building V 0.6

### ISSUE THREAD

**Issue by ksafford** [featurecat/lizzie#431]
I have a working version of leela-zero (confirmed by running it on the command line and playing several moves) and a network.gz file in the root directory of lizzie

Running `mvn package` from this directory leads to test failures:

> Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.021 sec <<< FAILURE!
> run(featurecat.lizzie.rules.SGFParserTest)  Time elapsed: 0.971 sec  <<< FAILURE!
> org.junit.ComparisonFailure: expected:<(;B[pd][;W[dp];B[pp];W[dd];B[fq](;W[cn];B[cc];W[cd];B[dc];W[ed];B[fc];W[fd](;B[gb](;W[hc];B[nq])(;W[gc];B[ec];W[hc];B[hb];W[ic]))(;B[gc];W[ec];B[eb];W[fb];B[db];W[hc];B[gb];W[gd];B[hb]))(;W[nq];B[cn];W[fp];B[gp];W[fo];B[dq];W[cq];B[eq];W[cp];B[dm];W[fm]]))> but was:<(;B[pd][C[

with a stacktrace like:

>         at org.junit.Assert.assertEquals(Assert.java:115)
>         at org.junit.Assert.assertEquals(Assert.java:144)
>         at featurecat.lizzie.rules.SGFParserTest.testVariaionOnly1(SGFParserTest.java:72)
>         at featurecat.lizzie.rules.SGFParserTest.run(SGFParserTest.java:31)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
>         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
>         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
>         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
>         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
>         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
>         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
>         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
>         at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
>         at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
>         at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
>         at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
>         at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
>         at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
>         at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
>         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)
> Running featurecat.lizzie.analysis.MoveDataTest
> Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
> 
> Results :
> 
> Failed tests:   run(featurecat.lizzie.rules.SGFParserTest): expected:<(;B[pd][;W[dp];B[pp];W[dd];B[fq](;W[cn];B[cc];W[cd];B[dc];W[ed];B[fc];W[fd](;B[gb](;W[hc];B[nq])(;W[gc];B[ec];W[hc];B[hb];W[ic]))(;B[gc];W[ec];B[eb];W[fb];B[db];W[hc];B[gb];W[gd];B[hb]))(;W[nq];B[cn];W[fp];B[gp];W[fo];B[dq];W[cq];B[eq];W[cp];B[dm];W[fm]]))> but was:<(;B[pd][C[Move 1
> 
> Tests run: 7, Failures: 1, Errors: 0, Skipped: 0

Possibly worth noting: If I download the Lizzie.0.6.Mac-Linux.zip and run

`java -jar lizzie.jar` there (also with the same leelaz and network.gz available) it hangs without ever loading a board.

**Comment by ksafford** [comment]
More info, if it helps:

If I build with

`mvn package -DskipTests=True`

I can build and also successfully run Lizzie.

**Comment by zsalch** [comment]
The option 'append-winrate-to-comment' should be disable by default. It will be changed.

**Comment by featurecat** [comment]
now this is fixed. I hope. you should be able to compile it with tests now.
