### ISSUE TITLE
0.6的引擎就是个笑话！！！

### ISSUE THREAD

**Issue by arrow-sy** [featurecat/lizzie#453]
![image](https://user-images.githubusercontent.com/45023737/48889407-c5f95600-ee70-11e8-8a8e-f1b4a332943e.png)

**Comment by featurecat** [comment]
@zsalch

**Comment by zsalch** [comment]
@arrow-sy 
Lizzie本身是不带引擎的，它是一个将Leela Zero的分析结果展示出来的界面。
看截图中的命令行，这应该是用的Leela Zero官方0.16的引擎，那么这个局面是分析的已有棋局，还是和Leela Zero对奕的结果。
能否提供些更详细的信息，以便分析原因？
