### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#46]
I am not a Java programmer, but I am enough of a general programmer that if I were able to build the source I might be able to fix or at least diagnose bugs that I run into. From the existence of `pom.xml` I assume that I am supposed to use Maven, but just running `mvn package` doesn't seem to know to what sources to compile, and generates an (almost) empty `target/lizzie-1.3.jar`. Clearly I'm missing something simple, but I don't know enough to know what it is. Some minimal build instructions would be very useful to people like me.

**Comment by igofun** [comment]
1."C:\Program Files\Java\jdk-9.0.4\bin\jar.exe" xvf lizzie.jar
2.trunk\ from 1.\org
3.Compile by modifying trunk contents as you like
3.1 ex:"C:\Program Files\Java\jdk-9.0.4\bin\javac.exe" trunk\src\wagner\stephanie\lizzie\rules\SGFParser.java

4.copy SGFParser.class to 1.\wagner\stephanie\lizzie\rules\
4.1folder:1.\     current
5."C:\Program Files\Java\jdk-9.0.4\bin\jar.exe" cvfm newlizzie.jar META-INF\MANIFEST.MF wagner com fonts org

en joy

**Comment by dfannius** [comment]
Unfortunately GitHub mangled the formatting of those instructions too much for me to follow them. If you are able to restore them I'd appreciate it. (Meanwhile, I'm getting closer; with @cngoodboy's recent changes to `pom.xml` I am able to generate a jar file that contains all the lizzie classes, though when I run it it's unable to find the JSON library.)

**Comment by dfannius** [comment]
Now that PR #67 has been merged, building is a breeze. Just `mvn package` (assuming Maven is installed) and then `java -jar target/lizzie-1.3.shaded.jar` runs everything without having to worry about dependencies. I'm leaving the issue open for now because I still think the README should be updated.

**Comment by featurecat** [comment]
Got it, I'll add that to the Readme when I next install from scratch.
