### ISSUE TITLE
Can you make a tourament mode?

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#47]
So now that LeelaZero has hundreds of network and plenty of unofficial networks, people want to test one network against the other. Back in the Chess days Shredder UI even had a tourament mode where it pit engines against each other and spit out a final score etc..

Can you bring this to Lizzie so we can scedule matches and then go to sleep and wake up and get results of hundreds of games?!

Even Sabaki no has this feature.

**Comment by isty2e** [comment]
Gomill ringmaster is already doing a very fine job regarding this. I don't see any reason to implement this to lizzie.

**Comment by featurecat** [comment]
Agreed, it steers away from my original objective... if you'd like to write something that does this I'd be happy to add it as an optional feature.
