### ISSUE TITLE
lizzie startup cooks dual i5 cpu

### ISSUE THREAD

**Issue by gogre** [featurecat/lizzie#481]
dual i5 tower c.2014 under Fedora 28.  leelaz cpu-only.

On starting lizzie 0.6 for the first time, cpu temperature quickly rose to 74 deg C, leelaz cpu usage running at 94%

afraid for my expensive hardware (cost me a whopping $120!), i stopped lizzie before it finished starting

i can run leelaz from Sabaki without cooking the cpu by limiting leelaz playouts and time_settings

**Question**: is there a way to similarly restrict leelaz in lizzie ?  if it requires modifying the .jar file i would need very precise instructions on how to edit it.  i tried opening it with gedit and saw red everywhere so abandoned that before it finished loading!  needless to say, i am not a programmer.

my leelaz already has sjeng's best-network, which is more than good enough for me :)  

So i edited Lizzie's config.txt as best i could aiming to set the same leelaz parameter values i use with Sabaki, and replaced Lizzie's network.gz with best-network, trying first editing "network-file": "network.gz",  and then trying again by deleting network.gz and renaming best-network to network.gz 

But both times lizzie still started cooking my cpu, and overwrote config.txt, so all my trial and error efforts were all trial and error :(

i see from your Readme that "The first run of the program may take a while to set up, as Leela Zero sets up the quick tuning. Feel free to replace the leelaz_opencl_tuning it creates with your own tuning. When Leela Zero finishes setting up, the board will display Leelaz's analysis."

Would it help to disable the quick tuning procedure, whatever that is, and if so, how?  i'm not using opencl, so maybe that isn't even the cause?  And anyway, what board?  java -jar lizzie.jar doesn't mention an sgf.

**Comment by featurecat** [comment]
Yes fortunately this should not be too hard. Try reducing the number of threads used by Leelaz to 1. You can do this via Lizzie's Config file: the Leelaz command. After %network-file, write --threads 1. Let me know if it works, and if it doesn't, please also share your Config file here.

**Comment by featurecat** [comment]
this will of course make Leelaz run slower but it should also reduce the cpu temperature

**Comment by gogre** [comment]
i unpacked a new edition of Lizzie.0.6.Mac-Linux.zip and copied leelaz
to it.   i did not tinker with network.gz this time.

 i noticed that there was no config.txt file in /Lizzie, from which i
infer that lizzie.jar creates config.txt afresh each time it runs.

ran lizzie, temp shot up to 62, aborted manually.

edited --threads 1 into config.txt

"engine-command": "./leelaz --gtp --lagbuffer 0 --weights
%network-file --threads 1",

re-ran lizzie, starting at 3.15pm

as you predicted, temp stayed down around 40-53C

QUESTION: i can run leelaz under Sabaki ok with --threads 2
temp gets up a bit, but not too much
will i be able to do the same with lizzie once it's finished it's fine-tuning?

what is fine-tuning anyway?  isn't it just doing some pondering to
pretty up the weights file?  wouldn't it be possible to just use
sjeng's best-network weightfile instead and skip fine tuning
altogether?

i am writing this waiting for lizzie to start... it's been going for
10 minutes so far... temp is stabilising at around 43C; leelaz %CPU is
0!!, i'm just going to let lizzie carry on with whatever it's doing
and do something else myself...

ah.. one thing lizzie has done is change config.txt
... but on reloading it into gedit, i see that lizzie.jar hasn't
changed the engine command

3.35 pm : this is making me feel like a creaking old Miss Marple,
except that i'm still in the dark :)

btw, this is off-topic re startup cpu temperature, but possibly
on-topic for lizzie display of lz move temperature:
https://www.lifein19x19.com/viewtopic.php?p=240821#p240821

3.38 pm : omigod i can see a lizzie board!

so i infer that  fine-tuning = asking leela to ponder an empty board,
although there's a thumbnail of a non-empty board on the left as well.
  oh well, mine not to reason why...
https://www.youtube.com/watch?v=KE4HGlmtOcg

thank you for your advice.

**Comment by featurecat** [comment]
are you sure you chose cpu only mode? I didn't think fine tuning was required for cpu only mode...
