### ISSUE TITLE
Configuring Lizzie for Different Board Sizes on Windows

### ISSUE THREAD

**Issue by trunterzx** [featurecat/lizzie#482]
I am trying to run Lizzie with different board sizes. For the Leela Zero part I can prepare by changing config.h and compiling in VS2017. (refer to https://github.com/gcp/leela-zero/issues/1291) 
But after that how do I use that in Lizzie for Windows? I tried replacing the leelaz.exe in the Lizzie folder with the newly compiled Leela Zero.exe, but it didn't seem to work.

For Mac it worked by directly replacing the leelaz in the Lizzie folder, but I'm not sure if Windows is the same. It would help if someone could advice me on how to do it for Windows as well.

**Comment by trunterzx** [comment]
@featurecat you mean it should work just by replacing the leelaz.exe with the newly compiled one? Alright, I'll give it a try again...

**Comment by trunterzx** [comment]
@featurecat 

I tried again by replacing the leelaz.exe with the newly compiled one, but when I ran Lizzie it just said "leelaz.exe has stopped working".

Is there anything else I should do rather than just copy the new leelaz.exe over?

**Comment by alreadydone** [comment]
not sure if antything in config file needs to be changed?

**Comment by trunterzx** [comment]
@featurecat Seems like it was an issue with compiling Leela Zero. Now it works correctly. Thanks for the help!
