### ISSUE TITLE
LeelaZ limit thinking time via time_settings?

### ISSUE THREAD

**Issue by m1nd0nf1r3** [featurecat/lizzie#484]
Dears,

how to run command using time_settings? In config file I added

"./leela-zero/leelaz --noponder --weights %network-file --gtp time_settings 0 2 1"

but then LeelaZ does not start. In Sabaki editor, as engine, it works..

So what I am doing wrong?

Kind regards, Tomasz

**Comment by featurecat** [comment]
instead of using the time settings parameter you must use the "max game thinking time seconds" option in Config.txt

I honestly shouldn't have made this design decision early on, but at the time, I just implemented the playing mode as quickly as possible.

**Comment by m1nd0nf1r3** [comment]
From read me file I understood that parameter max game thinking time seconds is applied when you hit Enter to have next move by LeelaZ?

Does it apply as well to N key - so new game, when Human plays against LeelaZ?
