### ISSUE TITLE
Lizzie + a little User Interface AI

### ISSUE THREAD

**Issue by gogre** [featurecat/lizzie#487]
https://github.com/gogre/irgobot is a proposed enhancement to Lizzie which combines methods of Swim and Influencie with callouts to leela-zero to accurately compute local life-and-death and thereby compute overlays of meaningful estimated territory and influence.
Illustrative video of irgobot processes: https://www.youtube.com/watch?v=pwxiBqykHGc&t=0s&index=7&list=PLfW0QbIZVHrf3fKo5Yp6soqOzgm6j3Jrc
Programming and/or redesigning irgobot - or parts of it - would make a practical computer science student project, and/or an ongoing hobby for people interested in AI and Go.
![pyramidirsmall](https://user-images.githubusercontent.com/46689669/52531552-f3b0b580-2d62-11e9-8cb2-708452ce1261.png)

**Comment by zsalch** [comment]
This is a great idea, I wonder if you have plans to implement it and merge it into lizzie.

**Comment by gogre** [comment]
i plan to take Tom Watson's advice
https://www.youtube.com/watch?v=9kP8viDHZTA&list=PLfW0QbIZVHrf3fKo5Yp6soqOzgm6j3Jrc&index=4

**Comment by featurecat** [comment]
Since irgobot is a very large scale project that has not begun yet, I am closing this issue. Please let me know if you start work on the project.
