### ISSUE TITLE
Build fails on test, no tar is created

### ISSUE THREAD

**Issue by chenqing1000** [featurecat/lizzie#495]
When mvn package, it fails as following
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running featurecat.lizzie.analysis.MoveDataTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.055 sec
Running featurecat.lizzie.rules.SGFParserTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.819 sec <<< FAILURE!
run(featurecat.lizzie.rules.SGFParserTest)  Time elapsed: 0.818 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<(;B[pd][;W[dp];B[pp];W[dd];B[fq](;W[cn];B[cc];W[cd];B[dc];W[ed];B[fc];W[fd](;B[gb](;W[hc];B[nq])(;W[gc];B[ec];W[hc];B[hb];W[ic]))(;B[gc];W[ec];B[eb];W[fb];B[db];W[hc];B[gb];W[gd];B[hb]))(;W[nq];B[cn];W[fp];B[gp];W[fo];B[dq];W[cq];B[eq];W[cp];B[dm];W[fm]]))> but was:<(;B[pd][C[Move 1
50.0%
(network.gz / 0 playouts)];W[dp]C[Move 2
50.0%
(network.gz / 0 playouts)];B[pp]C[Move 3
50.0%
(network.gz / 0 playouts)];W[dd]C[Move 4
50.0%
(network.gz / 0 playouts)];B[fq]C[Move 5
50.0%
(network.gz / 0 playouts)](;W[cn]C[Move 6
50.0%.......

I'm working on Win10, JDK 11.0.2, and already copied leelaz.exe and network.gz in current directory, leelaz works well alone too.

**Comment by chenqing1000** [comment]
I comment the threes in featurecat.lizzie.rules.SGFParserTest.java:
    // testVariaionOnly1();
    // testFull1();
    // testMore1();
Now I get the lizzie-0.6-shaded.jar, and it works well.

**Comment by zsalch** [comment]
The new submit has temporarily skipped Testing. Will not open before Testing completed.
