### ISSUE TITLE
is version 7 going to be released timeline soon 

### ISSUE THREAD

**Issue by hydrogenpi** [featurecat/lizzie#497]
there was talk that a lot of 'fixes' that if gcp didn't incorporate into LZ that version 7 would have baked in?

**Comment by featurecat** [comment]
not soon. hopefully within a month or two.

**Comment by pondturtle** [comment]
From LZ github it looks that new version of LZ is coming up. Might be prudent to wait for that too :-)

**Comment by featurecat** [comment]
I'm planning to work on Lizzie over my spring break (as a student). It will include a lot of nice features, including the new Leela Zero commands to control which moves will be searched/excluded from search. It will be a significant improvement, I hope.
