### ISSUE TITLE
What's wrong with gpu?

### ISSUE THREAD

**Issue by Climu1d** [featurecat/lizzie#50]
I downloaded cpu.zip and the change in settings with gpu doesnt work, I only have one gpu and tried the [0,1] in so many ways under the leela settings and it juust doesnt work if i change it from []    } ... to ... [0,1]      ] Lizzie won't even load up..... pls help I am trying to see how strong it can be with 8 cpu and 1 gpu.... I've even read another on another issue that it doesnt work on gpu.zip ( and if it does now and I can only use gpu on gpu.zip pls let me know )

**Comment by featurecat** [comment]
Maybe it doesn't work on either. In my limited single-gpu testing it worked but I'll figure out the issue. Cpu.zip shouldn't be able to use gpu, though. So you will want gpu when it is fixed.
