### ISSUE TITLE
Lizzie v0.6 AMD Radeon VII - end of process

### ISSUE THREAD

**Issue by bearyangry** [featurecat/lizzie#514]
Hi,

On WIN10, I get a "Leelaz process ended" and "java.io.IOException" when trying to load Lizzie. I had an AMD RX580 and swapped to the new Radeon VII yesterday. Everything worked great before the swap. I used AMD uninstall utility to do clean install of drivers.

I also tried compiling next tree branch but i'm a novice at this. I got to the step of running "leela-zero2017.sln" that portion failed on Visual Studio but not sure if it's needed? 

Any ideas why it would of worked perfectly for months then swapping to new VII card would cause the error? Output attached.
[lizzle_error.txt](https://github.com/featurecat/lizzie/files/3027127/lizzle_error.txt)

**Comment by gcp** [comment]
This looks like a GPU/driver issue with leela zero and probably has nothing to do with Lizzie itself.

**Comment by bearyangry** [comment]
Thanks, I opened a new issue on the Leela Zero's github. I get a "*ERROR*: Could not talk to engine after launching." when running autogtp.

I also did a clean install of system and latest drivers, it did not help.

https://github.com/leela-zero/leela-zero/issues/2321

**Comment by bearyangry** [comment]
Deleting OpenCL.dll resolved the issue.
