### ISSUE TITLE
Automatical analysis using lizzie0.6+leela0.17 is slower than lizzie0.6+leela0.16

### ISSUE THREAD

**Issue by daxuebeng** [featurecat/lizzie#520]
Since leela0.17 supports the tensor core of nvidia GPU, I have tested leela0.17 using a Tesla V100 in google cloud by the ‘--benchmark’ option. Indeed, leela0.17 can use more threads (e.g. 32) and is faster than leela0.16 by a factor of 5. However, I then used lizzie0.6 in my local desktop to remotely call leela0.17 in google cloud and found it is even slower than leela0.16 to complete the analysis of the same sgf.
The command I used to call leela in google cloud is something like ‘ssh -i id_rsa root@myip leela-zero/build/autogtp/leelaz --gtp --lagbuffer 0 --threads 32 --weights %network-file ’. Is there any problem in my parameter setting or lizzie0.6 does not support leela0.17 well?

**Comment by featurecat** [comment]
Can you also try it with current Lizzie master?

**Comment by daxuebeng** [comment]
I think I had used a wrong version of leela when I posed this issue. I have tried the correct version and found lizzie0.6+leela0.17 is indeed much faster than lizzie0.6+leela0.16 (3x ~ 4x).
Sorry for my confusing information and please close this issue. Thanks.
