### ISSUE TITLE
can't build on MACOS

### ISSUE THREAD

**Issue by palusijf** [featurecat/lizzie#522]
Hi,
I have this error when I build with maven : 

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  32.201 s
[INFO] Finished at: 2019-04-12T14:26:58Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle (default) on project lizzie: Execution default of goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle failed: An API incompatibility was encountered while executing sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle: java.lang.ExceptionInInitializerError: null

Best regards,
J-Fred

**Comment by featurecat** [comment]
That might be due to https://github.com/featurecat/lizzie/pull/517

I'll try to figure out updated Mac instructions. If you get it to work from there please let me know. I need to find a Mac in order to test this out.

**Comment by njfox** [comment]
I'm running into this same issue on Arch Linux, so it doesn't seem to be specific to Mac

**Comment by nhytgbvfredc** [comment]
> I'm running into this same issue on Arch Linux, so it doesn't seem to be specific to Mac.
> 
> I noticed this in case it's relevant:
> 
> ```
> [INFO] --- appbundle-maven-plugin:1.2.0:bundle (default) @ lizzie ---
> [INFO] Creating and setting up the bundle directories
> [INFO] Copying the native Java Application Stub
> [INFO] Copying the Icon File
> [INFO] Copying dependencies
> [INFO] Writing the Info.plist file
> [INFO] FileResourceLoader : adding path 'target/classes'
> [INFO] Null reference [template 'config/Info.plist', line 61, column 13] : $APP_ROOT cannot be resolved.
> ```

I'm too.[INFO] --- appbundle-maven-plugin:1.2.0:bundle (default) @ lizzie ---
[INFO] Creating and setting up the bundle directories
[INFO] Copying the native Java Application Stub
[INFO] Copying the Icon File
[INFO] Copying dependencies
[INFO] Writing the Info.plist file
[INFO] FileResourceLoader : adding path 'target/classes'
[INFO] Null reference [template 'config/Info.plist', line 61, column 13] : $APP_ROOT cannot be resolved.
[INFO] Copying additional resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.411 s
[INFO] Finished at: 2019-04-23T12:16:21+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle (default) on project lizzie: Execution default of goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle failed: An API incompatibility was encountered while executing sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>sh.tak.appbundler:appbundle-maven-plugin:1.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/f/.m2/repository/sh/tak/appbundler/appbundle-maven-plugin/1.2.0/appbundle-maven-plugin-1.2.0.jar
[ERROR] urls[1] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
[ERROR] urls[2] = file:/home/f/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[3] = file:/home/f/.m2/repository/commons-collections/commons-collections/3.1/commons-collections-3.1.jar
[ERROR] urls[4] = file:/home/f/.m2/repository/velocity/velocity/1.5/velocity-1.5.jar
[ERROR] urls[5] = file:/home/f/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
[ERROR] urls[6] = file:/home/f/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar

**Comment by nhytgbvfredc** [comment]
I replace $APP_ROOT to absolutly path of the line in file "Info.plist". But it still report ERROR like under: 
`[INFO] --- appbundle-maven-plugin:1.2.0:bundle (default) @ lizzie ---
[INFO] Creating and setting up the bundle directories
[INFO] Copying the native Java Application Stub
[INFO] Copying the Icon File
[INFO] Copying dependencies
[INFO] Writing the Info.plist file
[INFO] FileResourceLoader : adding path 'target/classes'
[INFO] Copying additional resources
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.369 s
[INFO] Finished at: 2019-04-23T12:34:38+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle (default) on project lizzie: Execution default of goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle failed: An API incompatibility was encountered while executing sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>sh.tak.appbundler:appbundle-maven-plugin:1.2.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/f/.m2/repository/sh/tak/appbundler/appbundle-maven-plugin/1.2.0/appbundle-maven-plugin-1.2.0.jar
[ERROR] urls[1] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
[ERROR] urls[2] = file:/home/f/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[3] = file:/home/f/.m2/repository/commons-collections/commons-collections/3.1/commons-collections-3.1.jar
[ERROR] urls[4] = file:/home/f/.m2/repository/velocity/velocity/1.5/velocity-1.5.jar
[ERROR] urls[5] = file:/home/f/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
[ERROR] urls[6] = file:/home/f/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
[ERROR] urls[7] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-archiver/3.0.3/plexus-archiver-3.0.3.jar
[ERROR] urls[8] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[9] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-io/2.7/plexus-io-2.7.jar
[ERROR] urls[10] = file:/home/f/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
[ERROR] urls[11] = file:/home/f/.m2/repository/org/apache/commons/commons-compress/1.10/commons-compress-1.10.jar
[ERROR] urls[12] = file:/home/f/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[ERROR] urls[13] = file:/home/f/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[14] = file:/home/f/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[15] = file:/home/f/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[16] = file:/home/f/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
[ERROR] urls[17] = file:/home/f/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[18] = file:/home/f/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[19] = file:/home/f/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[20] = file:/home/f/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[21] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[22] = file:/home/f/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
[ERROR] urls[23] = file:/home/f/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[24] = file:/home/f/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : multiple points
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
`

**Comment by scw1109** [comment]
Issue is not related to macos. Error saying its `An API incompatibility was encountered while executing sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle: java.lang.ExceptionInInitializerError: null` 

Similar issue found around, 
 * https://stackoverflow.com/questions/53696439/appbundle-maven-plugin-fails-on-mac-osx-with-java-10
 * https://github.com/spotify/dockerfile-maven/issues/77
 * https://github.com/forcedotcom/dataloader/issues/168

I could build successfully after applying the follow to `pom.xml`,
```
            <plugin>
                <groupId>sh.tak.appbundler</groupId>
                <artifactId>appbundle-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <mainClass>featurecat.lizzie.Lizzie</mainClass>
                    <iconFile>assets/icon.icns</iconFile>
                    <dictionaryFile>config/Info.plist</dictionaryFile>
                </configuration>
                <executions>
                    <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>bundle</goal>
                    </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-archiver</artifactId>
                        <version>4.1.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-velocity</artifactId>
                        <version>1.2</version>
                    </dependency>
                </dependencies>
            </plugin>
```
And my env is,
```
Apache Maven 3.6.1
Java version: 11.0.2, vendor: Oracle Corporation
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"
```

**Comment by palusijf** [comment]
Thanks.

**Comment by featurecat** [comment]
OK. I'm going to leave this issue open until I actually fix it for the future!

**Comment by ysangkok** [comment]
I just stumbled into this on Ubuntu.

**Comment by jfsamper** [comment]
Yes I ran into the same problem on Ubuntu.
I can confirm that pasting:
`	<plugin>
                <groupId>sh.tak.appbundler</groupId>
                <artifactId>appbundle-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <mainClass>featurecat.lizzie.Lizzie</mainClass>
                    <iconFile>assets/icon.icns</iconFile>
                    <dictionaryFile>config/Info.plist</dictionaryFile>
                </configuration>
                <executions>
                    <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>bundle</goal>
                    </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-archiver</artifactId>
                        <version>4.1.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.codehaus.plexus</groupId>
                        <artifactId>plexus-velocity</artifactId>
                        <version>1.2</version>
                    </dependency>
                </dependencies>
            </plugin>`
between <plugins> and </plugins> inside pom.xml works.

**Comment by gjm11** [comment]
I am seeing a very similar problem building on Windows 10, with Maven 3.6.1 and JDK 12.0.1. The pom.xml file in the current version of Lizzie is very like the one above except without the \<dependencies> element; adding that in makes the build apparently succeed.

**Comment by MarcelGruenauer** [comment]
I still have the same issue even after using the above <plugin>.

Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 12, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-12.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"

Could someone please provide a .jar file for the latest commit? I'd like to try it with KataGo but can't get "mvn package" to work.
