### ISSUE TITLE
Lizzie cannot start properly

### ISSUE THREAD

**Issue by zzy96** [featurecat/lizzie#537]
Hi,

I have installed _leela-zero_ from `brew install leela-zero` (leela-zero 0.17). Downloaded the most recent `network.gz`. Built Lizzie from the current master. However, when I started Lizzie with `java -jar lizzie-0.6-shaded.jar`, the winrate went crazy and _leelaz process ended_ in just a few second. Screenshot attached here:

<img width="952" alt="Screen Shot 2019-05-23 at 21 38 26" src="https://user-images.githubusercontent.com/15527877/58257573-be752400-7da3-11e9-861c-b761b6244968.png">

I have tried both java 8 and java 11. The behavior is the same. Any help is appreciated!

**Comment by featurecat** [comment]
I think it's related to the GPU drivers on Macs. Could you please first try compiling for CPU-only mode and see if it works?

**Comment by zzy96** [comment]
It is working on my new Mac but not working on the old (Macpro 2015). May need your help on the instruction for CPU-only mode. This may be a similar issue #527

**Comment by zzy96** [comment]
Duplicate of #527
