### ISSUE TITLE
Omits some moves while loading SGF file

### ISSUE THREAD

**Issue by wonsiks** [featurecat/lizzie#55]
I don't know why but when I load a sgf file to lizzie some stones are not be shown on the board.
Please check the image below.
Another image is showing same sgf file loaded by zen 7.

Please check it out...
Thanks.

![20180403_145146](https://user-images.githubusercontent.com/37356450/38231864-0f93ec0a-3704-11e8-8a13-bae0430ba5bf.jpg)

**Comment by wonsiks** [comment]
I guess lizzie is missing every first move of each new lines from sgf file.

**Comment by dfannius** [comment]
This was fixed with pull request #51, which has been merged, so it will be in the next release.

**Comment by wonsiks** [comment]
Got it! Thanks~
