### ISSUE TITLE
Double quotes in engine-command need to be extra-extra escaped

### ISSUE THREAD

**Issue by lightvector** [featurecat/lizzie#559]
I'm attempting to use engine-command to run an engine remotely, and ran into a behavior that is highly non-intuitive.

**The bug:**
My engine command looked roughly like:
`C:/cygwin64/bin/ssh.exe REMOTE_SERVER 'cd somewhere; SET_SOME_ENV_VARIABLE="FOO BAR" ENGINE_COMMAND'`

This command works perfectly fine when running it in a Windows command prompt (except with backslashes instead of forward slashes). But it fails when I specify the following in engine-command in the config.txt as follows:
`"engine-command": "C:/cygwin64/bin/ssh.exe REMOTE_SERVER 'cd somewhere; SET_SOME_ENV_VARIABLE=\"FOO BAR\" ENGINE_COMMAND'`

Note that I have dutifully escaped the double quotes for the JSON format of the config, yet it still does not work, even though it is the JSON escaping of the command that works on the command line.

However, the following works:
`"engine-command": "C:/cygwin64/bin/ssh.exe REMOTE_SERVER 'cd somewhere; SET_SOME_ENV_VARIABLE=\\\"FOO BAR\\\" ENGINE_COMMAND'`

The double quotes must be escaped *again*! This is very nonintuitive.

**Explanation (by my understanding):**
I dug into the Lizzie source code, and the reason is that Lizzie internally uses java ProcessBuilder. Based on what I can find online, ProcessBuilder has buggy quoting semantics on Windows - when you add an argument to it, ProcessBuilder will internally wrap the argument in double quotes if the argument contains spaces, but does NOT itself escape anything before wrapping! 

For example, if trying to run the command:
`foo.exe -bar 'This is a double quote character: " yay'` 
by passing the following three strings in the List for ProcessBuilder:
`foo.exe`
`-bar`
`'This is a double quote character: " yay'`

ProcessBuilder will actually assemble them into the following command that actually gets executed on the system:
`foo.exe -bar "'This is a double quote character: " yay'"` 

The third argument contains spaces, so ProcessBuilder adds double-quotes around it, but due to a bug it does not escape the double quotes that are already within the third argument! So now the command has unbalanced double quotes and fails.

See: https://stackoverflow.com/questions/12124935/processbuilder-adds-extra-quotes-to-command-line
and: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6511002 (where Oracle has decided that they refuse to fix this bug for some reason).

**Possible fixes:**
* It would be great if Lizzie could pre-escape double quotes if an argument has spaces when running on Windows so that the right thing will happen when ProcessBuilder wraps double quotes. Alternatively, I think ProcessBuilder will never attempt to double-quote strings that already begin and end with double quotes, so Lizzie could simply *always* add double quotes around arguments on Windows and *always* escape properly, before passing them to ProcessBuilder. 
* If this is not possible, then it would be useful to at least add documentation to Lizzie that double quotes in the engine command might need to be extra-escaped beyond what's needed by either JSON or the normal command line execution of that command.

Thanks!

**Comment by zsalch** [comment]
I'll try to fix it. Thanks.

**Comment by zsalch** [comment]
Fixed. #562

**Comment by lightvector** [comment]
Nice! Thanks. :)
