### ISSUE TITLE
leelaz.exe can't find OpenCL.dll

### ISSUE THREAD

**Issue by ohyou** [featurecat/lizzie#56]
Windows 10, 64 bit. Have the latest nvidia drivers installed.
When trying to launch lizzie, nothing happens. The prompt says `Leelaz process ended`
When trying to launch leelaz.exe directly, the error pops up: `The code execution cannot proceed because OpenCL.dll was not found. Reinstalling the program may fix this problem.`

**Comment by featurecat** [comment]
copy all the dlls files from Leela Zero's folder to this folder. let me know if it fixes. if so, I'll just include all dlls next release.

**Comment by ohyou** [comment]
It did. Copied everything except for the `libopenblas.dll` (asked to replace, I declined).

**Comment by featurecat** [comment]
OK! sounds good... I'll probably release a patch/bug fix release soon so that this won't happen :)
