### ISSUE TITLE
Lizzie doesn't build on Debian Buster

### ISSUE THREAD

**Issue by seopsx** [featurecat/lizzie#580]
I have also tried the latest version of maven (3.6.1) with no success.

> $ mvn --version
> Apache Maven 3.6.0
> Maven home: /usr/share/maven
> Java version: 11.0.3, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
> Default locale: en_GB, platform encoding: UTF-8
> OS name: "linux", version: "4.19.0-5-amd64", arch: "amd64", family: "unix"
> 

Error messages while building with mvn:

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
> WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

> [INFO] Creating and setting up the bundle directories
> [INFO] Copying the native Java Application Stub
> [INFO] Copying the Icon File
> [INFO] Copying dependencies
> [INFO] Writing the Info.plist file
> [INFO] FileResourceLoader : adding path 'target/classes'
> [INFO] Null reference [template 'config/Info.plist', line 61, column 13] : $APP_ROOT cannot be resolved.
> [INFO] Copying additional resources
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  29.212 s
> [INFO] Finished at: 2019-07-21T10:03:29+03:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle (default) on project lizzie: Execution default of goal sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle failed: An API incompatibility was encountered while executing sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle: java.lang.ExceptionInInitializerError: null
> [ERROR] -----------------------------------------------------
> [ERROR] realm =    plugin>sh.tak.appbundler:appbundle-maven-plugin:1.2.0
> [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
> [ERROR] urls[0] = file:/home/user/.m2/repository/sh/tak/appbundler/appbundle-maven-plugin/1.2.0/appbundle-maven-plugin-1.2.0.jar
> [ERROR] urls[1] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
> [ERROR] urls[2] = file:/home/user/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
> [ERROR] urls[3] = file:/home/user/.m2/repository/commons-collections/commons-collections/3.1/commons-collections-3.1.jar
> [ERROR] urls[4] = file:/home/user/.m2/repository/velocity/velocity/1.5/velocity-1.5.jar
> [ERROR] urls[5] = file:/home/user/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
> [ERROR] urls[6] = file:/home/user/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
> [ERROR] urls[7] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-archiver/3.0.3/plexus-archiver-3.0.3.jar
> [ERROR] urls[8] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
> [ERROR] urls[9] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-io/2.7/plexus-io-2.7.jar
> [ERROR] urls[10] = file:/home/user/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
> [ERROR] urls[11] = file:/home/user/.m2/repository/org/apache/commons/commons-compress/1.10/commons-compress-1.10.jar
> [ERROR] urls[12] = file:/home/user/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
> [ERROR] urls[13] = file:/home/user/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
> [ERROR] urls[14] = file:/home/user/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
> [ERROR] urls[15] = file:/home/user/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
> [ERROR] urls[16] = file:/home/user/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
> [ERROR] urls[17] = file:/home/user/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
> [ERROR] urls[18] = file:/home/user/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
> [ERROR] urls[19] = file:/home/user/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
> [ERROR] urls[20] = file:/home/user/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
> [ERROR] urls[21] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
> [ERROR] urls[22] = file:/home/user/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
> [ERROR] urls[23] = file:/home/user/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
> [ERROR] urls[24] = file:/home/user/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
> [ERROR] Number of foreign imports: 1
> [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
> [ERROR] 
> [ERROR] -----------------------------------------------------
> [ERROR] : multiple points
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by kaorahi** [comment]
#532 works for me. (cf. #522)

**Comment by zsalch** [comment]
@seopsx 
If you use this #532, what is the result, please let me know.

**Comment by seopsx** [comment]
> @seopsx
> If you use this #532, what is the result, please let me know.

It builds successfully with the modification to pom.xml.

**Comment by zsalch** [comment]
Maybe you can press key 'E' to open the GtpConsole Dialog to check more details.

**Comment by seopsx** [comment]
> Maybe you can press key 'E' to open the GtpConsole Dialog to check more details.

![lizzie_gtp_console](https://user-images.githubusercontent.com/35587223/62652683-963da000-b964-11e9-8e37-922c9af20725.png)

**Comment by TFiFiE** [comment]
Does #598 fix it for you?

**Comment by seopsx** [comment]
> Does #598 fix it for you?

Yes, it fixed the problem.
