### ISSUE TITLE
YAZenGtp.exe unsafe

### ISSUE THREAD

**Issue by ParmuzinAlexander** [featurecat/lizzie#608]
YAZenGtp.exe 56/69
https://www.virustotal.com/gui/file/8983cf76ccceec84f19edfe37d792ab1471de3090315c5446ac6890514104609/detection

For comparison gtp4zen.exe 0/68
https://www.virustotal.com/gui/file/7b0e58958751480e0e44ef8f743540413364cad72482663f8b197f9fc9d99ee9/detection

**Comment by featurecat** [comment]
That's a serious issue. But I don't see YAZenGtp.exe in this repository. In that case, please make sure not to run the exe. It shouldn't be part of the current Lizzie repository, please let me know if I'm wrong.

I won't be accepting .exe files in pull requests in the future & I'll continue to pay attention to the security issues. I'll make sure to let collaborators know. Thanks.

**Comment by yzyray** [comment]
Have a try about this one:
link：https://pan.baidu.com/s/1QQ6hINPUHgXW1jI9KxCjkA
code：9lgj

**Comment by ParmuzinAlexander** [comment]
@yzyray how I see it, old files 528 KB - good
files from Aug 22 544.5 KB - bad https://github.com/yzyray/lizziey/commit/be1b0a0bc3821d4df8b7a99e3d8b3c50f65fd3d0
files from Sep 1 528 KB (reuploading old?) - good https://github.com/yzyray/lizziey/commit/b174659adc1925de44bf64018f32463299a6da09
