### ISSUE TITLE
KataGo compatibility

### ISSUE THREAD

**Issue by acosmicjoke** [featurecat/lizzie#609]
I'm unable to get KataGo to work with lizzie. If i understand correctly all i have to do is change the "engine command" variable in my config.txt, to katago, the line i have currently reads like:

`"engine-command": "/home/david/Git/KataGo/cpp/katago gtp -model /home/david/Git/KataGo/cpp
/model/model.txt.gz -config /home/david/Git/KataGo/cpp/configs/gtp_example.cfg",`

When i try to start lizzie like this i get an unresponsive white window. I already managed to get katago working with sabaki using the same command. This all happens on arch linux by the way.

**Comment by featurecat** [comment]
The issue is that you are not using the %network-file parameter. Change network-file to be your model file, and have engine-command reference %network-file as the model.

**Comment by acosmicjoke** [comment]
Actually, compiling the git rolling release version of lizzie instead of using the regular precompiled release version fixed the problem for me, i just completely forgot that i opened this issue here. I have no idea what the problem was, it certainly wasn't what you are suggesting because i still just ignore the %network-file parameter in the config and it works now.
