### ISSUE TITLE
Playout counter

### ISSUE THREAD

**Issue by BenRJDictus** [featurecat/lizzie#612]
Is it possible to show an overall playout-counter while Leela Zero is pondering?

**Comment by featurecat** [comment]
yeah - in the title bar next to the playouts per second?

**Comment by BenRJDictus** [comment]
I don't see the playouts per second.

![Screenshot](https://user-images.githubusercontent.com/29932625/65163963-41e60f80-da3c-11e9-953f-18bc18dfbc2c.jpg)

**Comment by featurecat** [comment]
it's a new feature only available when you compile lizzie from github, but it'll be shown in lizzie 0.7, soon ish

**Comment by BenRJDictus** [comment]
OK, thank you very much!
