### ISSUE TITLE
Linux/Ubuntu compilation issue

### ISSUE THREAD

**Issue by bocadillo55** [featurecat/lizzie#615]
I follow the instructions of compiling lizzie (v0.6) on Ubuntu (mine is 18.04). But, when compiling I get an error from the Network.cpp file. It occurs at ` #include <Eigen/Dense>`. The file or the folder 'Eigen/Dense' cannot be found. I looked up in the /leela-zero/src directory. There is only an empty 'Eigen' directory.

**Comment by kaorahi** [comment]
This?

https://github.com/leela-zero/leela-zero#example-of-compiling---ubuntu--similar

    git submodule update --init --recursive

**Comment by bocadillo55** [comment]
> This?
> 
> https://github.com/leela-zero/leela-zero#example-of-compiling---ubuntu--similar
> 
> ```
> git submodule update --init --recursive
> ```

Thanks! well yeah, that did the trick but not quit the way I wanted. That command rewrote some other directories in /leela-zero/src. So i just ended up copying the updated /Eigen directory (which contained another /Eigen directory; the second one was the one I copied). 
I would also suggest to install the build dependency `libboost-all-dev`, the recommended `libboost-dev` contains apparently not everything you need.
