### ISSUE TITLE
Mac/Linux READMe.txt 

### ISSUE THREAD

**Issue by bocadillo55** [featurecat/lizzie#617]
In the README.txt file it says, if one wants to use CPU-only, then `#define USE_OPENCL` in /leela-zero/src/config.h should be commented away. That is not enough because there is `#define USE_HALF` that will try to include half precision OpenCL with some of the OpenCL tools. So compilation by `make` gives an error. 
Thus `#define USE_HALF` should be commented away too.

**Comment by featurecat** [comment]
thank you. noted in the new readme

**Comment by alreadydone** [comment]
`#define USE_CPU_ONLY`

**Comment by featurecat** [comment]
Oh does that work? 😂 admittedly I didn't investigate this too closely.

**Comment by alreadydone** [comment]
Yes, and I think you can also add `-DUSE_CPU_ONLY` when compiling without modifying the source.
