### ISSUE TITLE
Zen Estimate function is works in Lizzie

### ISSUE THREAD

**Issue by zihevic** [featurecat/lizzie#619]
I just see you delete the Zen estimate function from code as it not works, but from my test it works. original Zen6 or 7 do not have GTP version, but someone did edit gtp version after zen release. so if let zen estimate works in lizzie, just need a gtp version zen6or7's exe application and zen.dll from original zen release.

**Comment by featurecat** [comment]
Ok. I will add it again, thanks for your feedback. Didn't realize anyone uses that. But definitely I can't distribute the exe, so it has to be unofficially distributed.

**Comment by ParmuzinAlexander** [comment]
And one more thing: default estimate in Lizzie v0.7 is Zen estimate. Removing manual counting is a strange decision. Without Zen and KataGo, Lizzie not have estimate.
