### ISSUE TITLE
featurecat, Is you message in my Tencent QQ Group?

### ISSUE THREAD

**Issue by cngoodboy** [featurecat/lizzie#620]
@featurecat 
![screenchot](https://user-images.githubusercontent.com/26163954/65843364-e2550180-e363-11e9-9f97-f1a6d584c10d.png)
I saw you are in my Tencent QQ Group, is he you？
I'm really happy if you are in my Qencent QQ Group <3

**Comment by featurecat** [comment]
yeah :) nice to know about the chinese lizzie community, I had no idea about the group chats until yesterday.
