### ISSUE TITLE
Feature Request: Stop Engine from Running After Auto Analysis

### ISSUE THREAD

**Issue by bdrose** [featurecat/lizzie#621]
It would be nice to have the engine stop automatically after running Auto Analyze (a). It is pointlessly utilizing the CPU/GPU by doing an insane amount of analysis on the last move if you do not manually stop it.

**Comment by featurecat** [comment]
you can enable it in the configuration. Max analyze time minutes. in the new version I set it to 99999, but you can change it.

**Comment by featurecat** [comment]
ohhh i see what you mean now. yeah that's a good idea, I can't believe I didn't think of that until now haha. I'll implement that for next version, hopefully we can release that much sooner this time.

**Comment by featurecat** [comment]
Fixed with 62d92669b5bbb4c7ddceb4e96abf29f11198b672
