### ISSUE TITLE
Can't Load sgf with handicap settings correctly

### ISSUE THREAD

**Issue by Flanforever** [featurecat/lizzie#63]
Handicap stones not showing when opening sgf with handicap settings eg: HA[7].

**Comment by featurecat** [comment]
Thanks. I will address this for the release of 0.4 this weekend :)

**Comment by cngoodboy** [comment]
Its based on 'AB' and 'AW' tag, I 'll trying.

**Comment by Flanforever** [comment]
Yup, you are correct:
HA[7]  KM[0]  AB[dp][pd][dd][pp][jj][dj][pj]

**Comment by featurecat** [comment]
I believe this was fixed.
