### ISSUE TITLE
Are there something different between lizzie0.7 with the "Korean version" of KataGo?

### ISSUE THREAD

**Issue by atoutw** [featurecat/lizzie#632]
The "Korean version"
https://github.com/wonsiks/BadukMegapack

![image](https://user-images.githubusercontent.com/43053753/66256103-80fabb80-e7c5-11e9-80c6-bcb371545b42.png)
Korean version

![image](https://user-images.githubusercontent.com/43053753/66256108-9374f500-e7c5-11e9-8e5f-9595e89a9d65.png)
lizzie0.7

![image](https://user-images.githubusercontent.com/43053753/66256130-c919de00-e7c5-11e9-9b42-95a31c720502.png)
Korean version

![image](https://user-images.githubusercontent.com/43053753/66256134-cf0fbf00-e7c5-11e9-956d-dc8926abe7c7.png)
lizzie0.7

Are there something (setting, engine, etc...) different between lizzie0.7 with the "Korean version" of KataGo?

**Comment by featurecat** [comment]
what is this file..? it doesn't look like Korean language to me. am I wrong?

anyway this isn't an officially released file so it's hard for me to tell you what's different. it looks similar.

**Comment by atoutw** [comment]
@featurecat 
Thanks for the reply! This file was downloaded from the site below.

https://blog.naver.com/wonsiksnz

![image](https://user-images.githubusercontent.com/43053753/66269017-4e60c980-e87e-11e9-8dac-5262a0f70249.png)

The two are indeed very similar.
After many tests, I think the reason for different is only from the setting of "randomness".

**Comment by wonsiks** [comment]
@atoutw The difference between those two is weight file.
Megapack contains 20 blocks weight while lizzie contains 10 blocks.
