### ISSUE TITLE
how to change komi for analysis

### ISSUE THREAD

**Issue by Matuiss2** [featurecat/lizzie#681]
I'm not being able to change the komi from 7.5 to 6.5 or 0(handicap games)on analysis mode with Katago.

Set GameInfo doesn't work. Is there a way to do it or I'm stuck at analyzing games with 7.5 komi?

**Comment by wonsiks** [comment]
Don't forget to click OK button when you set komi at Game Info setting dialog.

**Comment by Matuiss2** [comment]
I did it, the Game Info refuses to close after pressing ok, it does nothing and blocks doing anything else in the software until we press X to close that window, and when I close it Lizzie resets the komi to 7.5 anyway.

**Comment by wonsiks** [comment]
@Matuiss2 Okay, then you may try this.
1. Open GTP console window(Hotkey : E)
2. Send GTP command "komi 6.5(enter)" at the bottom of console window.
![20200203_001113](https://user-images.githubusercontent.com/37356450/73610372-bbf8e880-4619-11ea-983c-e514153a8a93.png)

**Comment by Matuiss2** [comment]
This worked, thanks. Should I close the issue?
