### ISSUE TITLE
Score is shown as "0.0" in saved analysis of KataGo 1.3

### ISSUE THREAD

**Issue by MarcelGruenauer** [featurecat/lizzie#683]
I auto-analyzed a game with KataGo 1.3 and saved the SGF file including the analysis. Then I opened that SGF file again. With "Pondering off", I assume it uses the saved information for each node. See the attached screenshot.

The problem is that while the violet graph (correctly) shows that Black is leading by 27.3 points for the selected move, the number in the top middle always shows "0.0".

Maybe it has to do with how KataGo 1.3 changed the score estimation (see KataGo's release notes for 1.3).

![lizzie-saved-points-bug](https://user-images.githubusercontent.com/60425018/74133380-bdfa1300-4be8-11ea-976d-7c8c42e82225.png)

**Comment by NTUST-MITLAB** [comment]
I wish the estimated ScoreMean number in the middle back. They are not redundant
