### ISSUE TITLE
How can lizzie connect to katago remotely running on google cloud? 

### ISSUE THREAD

**Issue by daxuebeng** [featurecat/lizzie#688]
I am running lizzie v0.7.2 on a local Windows 7/10 and want to connect lizzie to katago remotely running on google cloud (ubuntu).
I have realized this for leela zero remotely running on google cloud by adding the following command in config.txt
"engine-command": "ssh -i id_rsa root@ip leela-zero/build/autogtp/leelaz --gtp --lagbuffer 0 --weights %network-file",
But this method does not work for katago.
Has anyone figured out the right way to configure lizzie v0.7.2?

**Comment by kota7** [comment]
I am facing the same challenge.  It will be very helpful if there is a guide on editing config file in general.

**Comment by isty2e** [comment]
I wrote a [brief guide](https://demo.codimd.org/s/SJd5xS5Q8) for that, though it was for vast.ai instead of GCP or AWS. Hope this helps.

**Comment by kotamori4** [comment]
@isty2e Thanks.  I think I did mostly the same as your blog but still failed.  Would you mind sharing your working `config.txt` file?  It would be very helpful.  You can of course mask confidential information in the file, if any.

**Comment by isty2e** [comment]
[Here](https://pastebin.com/h5NU33jt) it is, though I think there is nothing special about it.

**Comment by kotamori4** [comment]
@isty2e Thanks a lot, I will give it a try later.

By the way, the config.txt file seems to keep only katago engine.  Have you ever succeeded to keep both leera-zero and katago in the list and switch between them on the GUI?  I assume both engine run on remote.

**Comment by isty2e** [comment]
I haven't tried, I'm using KataGo almost exclusively in these days.

**Comment by kota7** [comment]
@isty2e Thanks.  It worked now!  Well, it was a typo.  I spelled `KataGo` as `Katago`.  A very basic mistake but your example file helped me to quickly spot it:p  To answer the original question of this thread, the engine-command config for KataGo engine would be like:

```
"engine-command": "ssh -i <aws-sshkey.pem> ubuntu@<cloud IP> /home/ubuntu/KataGo/cpp/katago gtp -model /home/ubuntu/KataGo/g170-b20c256x2-s1913382912-d435450331.txt.gz -config /home/ubuntu/KataGo/cpp/configs/gtp_example.cfg"
```

Here you need to give the path for:
- katago software
- network file (.txt.gz)
- config file (.cfg)

They may be found at different locations.

I am using AWS, but should be similar for google cloud.

Making a .bat or .sh files for the command like @isty2e blog does would work as the same.  This implifies the lizzie's config file.

**Comment by daxuebeng** [comment]
Thanks for your help. @isty2e  and @kota7
I find the same way pointed out by kota7 is working. We need not to install putty. 'ssh.exe' in windows10 or openSSH in windows 7 is fine.
Then edit "engine-command" in config.txt as shown by kota7 
But I find I need to copy ssh.exe into the directory of lizzie; otherwise, lizzie can't find it.

**Comment by isty2e** [comment]
Oh, copying ssh.exe to the working directory, that was the trick. Thanks for the information.

**Comment by kotamori4** [comment]
@daxuebeng  Instead of copying the file, I think you can give a full path of ssh.exe in the config file.
Alternatively adding the folder where ssh.exe in to your PATH environment variable may work too.

**Comment by Sadaharu2624** [comment]
Hi @daxuebeng, I just saw this post and I'm figuring out how to run katago remotely on google cloud.
I can install lizzie and run normally on a windows server (obviously), but I don't know how to install katago on a ubuntu server because I've never worked with ubuntu before. Would you mind sharing the steps to install katago and then connecting to it successfully from a local machine?
