### ISSUE TITLE
Bug: Sign of score/win-rate flips.

### ISSUE THREAD

**Issue by PJTraill** [featurecat/lizzie#707]
Every now and again the score/win-rate graph (set broad) shows the score and win rate after some move as an extreme swing, which this last time I noticed was the near exact negative / opposite of the estimates before and after that move. After thinking for a while it usually gets corrected.

I cannot tell if this is a KataGo or Lizzie problem (I do not remember if I have seen this with Leela Zero, the only other engine I have used).

**Versions**
Lizzie 0.7.1
KataGo 1.3.5 , 1.4.2
64-bit Open Suse Leap 15.1 (fully updated)
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-suse-lp151.3.12.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.6+10-suse-lp151.3.12.1-x8664, mixed mode)

**Comment by PJTraill** [comment]
### P.S.
Do please let me know if there is something I can do to generate extra useful information – I do not know how to pin this down to KataGo or Lizzie. Since I see that KG 1.4.2 fixes a bug to do with signs flipping perhaps it is there, though that would mean they overlooked a similar bug. I have therefore noted this issue at https://github.com/lightvector/KataGo/issues/231 , though without details.

**Comment by PJTraill** [comment]
[Lightvector](https://github.com/lightvector) suggests that it is more likely to be in Lizzie; the sign flipping in KataGo had to do with input into the neural net, not GTP output, and they have also seen this behaviour.

**Comment by featurecat** [comment]
It's unlikely I'll be able to fix this in the current version of Lizzie since I'm working on a complete rewrite as the next version (separate, new code), but I will pay close attention that this bug is fixed during the rewrite's development.

**Comment by PJTraill** [comment]
That sounds like good news, as it is not really urgent (though confusing until you spot what is going on!).

Keep up the good work; Lizzie is a great addition to one’s toolbox.
