### ISSUE TITLE
Lizzie has some sort of bug or leak causing slowness?

### ISSUE THREAD

**Issue by lightvector** [featurecat/lizzie#717]
I suspect there is some sort of bug in Lizzie that causes user actions to take longer and longer based on the total number of actions taken so far in that instance of Lizzie.

To reproduce:
* Find an SGF file that has 200-300 moves in it.
* Open it in Lizzie. Also, open the GTP console, so you can watch the ids that Lizzie is sending to the bot to see how many moves and undos have happened, as a convenient way to count the total number of actions.
* Press spacebar to stop analysis, analysis does not need to be running to observe this bug.
* Press and hold page down to scroll to the end of the game, then press and hold page up to scroll to the start of the game, and repeat for a few minutes, scrolling to the end, then back to the start and again and again.

On my laptop, it starts off highly responsive and is very fast to scroll around in the game. But starting around 2000 total actions, there are hints of stutteryness, and by 4000 and 5000, lag from scrolling back and forth is very noticeable. By the time you hit 20000 actions or so, Lizzie is almost unusable for scrolling around the game due to the lag.

In case it's relevant, I'm running on Windows right now. The lag is present regardless of whether the bot used is Leela Zero or KataGo. I'm running both in the cloud, the actual process that Lizzie itself is running is an SSH script, which invokes the engine remotely and then stdin and stdout work exactly as if talking to the engine, but I also tested just now and also it happens for running bots locally too.

I think the lag also persists and does not go away when changing what bot is being used for analysis, and it definitely does not go away when opening a new sgf file. Indeed, opening many sgf files in the same run of Lizzie, one after another to analyze each one successively, was how I encountered this issue.

Whether it's in the graphics, or the processing it does to handle GTP command history, or somewhere else, I'm guessing there is something in Lizzie's internals that "should" be constant time but is instead implemented in a way that makes it linear in the total number of actions, or changes to the board, or something, so that the more that Lizzie is used without restarting, the slower it gets. Closing and opening a fresh Lizzie makes everything fast once more, until used enough that it slows down again.

**Comment by featurecat** [comment]
I'll try to find the leak and hotfix this weekend.

**Comment by lightvector** [comment]
Given that the workaround is easy (restart Lizzie) and that the issue only shows up after viewing multiple games in succession (a few thousand actions), I would say please don't consider this to be very urgent. If you're rewriting (?) a lot of things in 1.0 in a cleaner/better way using the experience you gained from all the work up to now, then there's a good chance that when you release 1.0 it will all be solved anyways.

I'm mostly posting this up here for the record, and also as maybe one thing to just keep in mind when you're designing 1.0. I know at least for me, if I'm taking a second shot at things, having in the back of my mind some of the trouble spots from earlier attempts can make things easier to get right the next time.

Either way, thanks for the attention and the work! Lizzie is still my top tool at the moment for playing with variations. :)

**Comment by yzyray** [comment]
I think maybe the GTPConsolePane causes the issue,all the commands and recorded in a JScrollPane,with commands growing up,the JScrollPane get lagged.

**Comment by kaorahi** [comment]
Something like this? (I know nothing about swing.)

https://github.com/kaorahi/lizzie/tree/fix717_slow

**Comment by featurecat** [comment]
Possibly fixed? Planning to release a version tonight with kaorahi's fix, thanks
