### ISSUE TITLE
It's labeled "Lizzie 0.7.2"

### ISSUE THREAD

**Issue by hope366** [featurecat/lizzie#718]
This is probably a very minor issue, and maybe it's intended and not even a problem, but I'm just reporting it as something I noticed.
Launch Lizzie 0.7.3 and go to the top tab, "Settings" -> "About Lizzie" and you'll see The window that appears shows "Lizzie 0.7.2" and the previous version is marked as "Lizzie 0.7.2".

**Comment by featurecat** [comment]
Whoops that was not intentional. Thanks

**Comment by hope366** [comment]
The software you developed has made my life in Go so wonderful!
Thank you so much for letting me use lizzie for free.
