### ISSUE TITLE
Inversion of winning percentage graph

### ISSUE THREAD

**Issue by hope366** [featurecat/lizzie#727]
This is probably related to #707, "Bug: Sign of score/win-rate flips."
Please see the attached image.
The green graph showing the winning percentage is reversed in the relatively early section of the game and a certain section in the final stage. This did not improve after a long search.

In the middle of the normal-looking interval, the win rate was often reversed, but it was limited to a very short time, and after a few seconds of searching, it returned to normal drawing.

Game information: 3 handicap games komi=0.5
Black = 9d (human)
White = katago-v1.4.5-CUDA 30b-s482

I played through Sabaki-v0.43.3 and loaded the saved sgf file into Lizzie-v0.7.3.

Windows10 Pro
Core-i7-9700 3.00GHz
NVIDIA GeForce RTX2060
jdk-14.0.1
jre1.8.0_251

I hope this information will serve as a reference for future development.
![lizzie](https://user-images.githubusercontent.com/63999713/86203662-87756280-bba0-11ea-9743-017d965d66d7.jpg)

**Comment by kaorahi** [comment]
There are strange numbers "-1.0%" and "101.0%" on the winrate bar in your screenshot. If you can reproduce this issue, what winrate is shown for each suggested move on the board?

This issue seems different from #707 in my impression. I suspect "wrap around" rather than "flip" of winrates.

**Comment by hope366** [comment]
I discarded the sgf file, but I played it manually because the game record was saved in the server of Net Go.
Regarding the upper and lower limits of the winning rate, if the difference in score is very large, it seems that it may show a value such as "-1.5%" or "101%".
![sae](https://user-images.githubusercontent.com/63999713/86371702-2fcc1980-bcbc-11ea-9fb3-aa6ceb89970f.jpg)

**Comment by hope366** [comment]
If the difference in score is very large, the winning percentage will show a number like "101.9%" or "-1.9%".
In this case, the green line showing the winning percentage is fixed at the middle position (line with 50% winning percentage) and does not try to draw.
![saa1](https://user-images.githubusercontent.com/63999713/86381547-6f98fe00-bcc8-11ea-941d-2be2d7332e9b.jpg)
When analysis is turned on and the number of searches is increased, the winning percentage shows a normal value such as "100.0%" or "0.0%", but at this point the winning percentage line is drawn normally. Seems to do.
![saa2](https://user-images.githubusercontent.com/63999713/86381656-7a539300-bcc8-11ea-8c43-bcb821a0a8c7.jpg)

**Comment by hope366** [comment]
If I try the same thing with lizzie right after compiling, the win percentage graph seems to be drawn correctly.
![sae10](https://user-images.githubusercontent.com/63999713/86390149-82b0cb80-bcd2-11ea-861b-4d4b90b985a8.jpg)
Something may have gone wrong while changing various settings.
I wondered what was causing it, but couldn't find a good conclusion.

**Comment by hope366** [comment]
I understood the cause.
There is an item called "How to display win rate" in the window displayed in "Settings" -> "Engine".
If "Lcb" is selected here, it seems that the winning percentage display may be below 0% or above 100% when the score difference is large.
If the white win rate falls below 0%, the graph is not drawn at that point because it is fixed at the 50% line, and when the black is hit next, it is drawn as if the white win rate was 100%.

**Comment by kaorahi** [comment]
KataGo can output negative LCBs that confuse Lizzie's winrate graph. Here is a doubtful line in `WinrateGraph.java`.

~~~~
        if (wr < 0) {
          wr = 100 - lastWr;
~~~~

**Comment by hope366** [comment]
`if (wr <0) {
           wr = 0;`
I tried it, but as before, when the white win rate is below 0%, it seems that the white win rate is drawn as if it is 100%.
I'm a complete layman in programming, so maybe I'm doing something irrelevant.

**Comment by hope366** [comment]
Next time,
`if (wr < 0) { wr = lastWr; `
I tried this.
When the white win rate is below 0% in the white turn, the graph is fixed at the 50% line and normal drawing is not performed, but when it is the next black turn, the 50% line The previous state, which was fixed at, was corrected and drawn to a black win rate of around 100%.

**Comment by hope366** [comment]
Great!
I modified the source code and compiled lizzie.
It can be an extreme draw for a second that is far from the correct win rate, but it's only for a very short period of time and will soon be drawn to show the correct position.
With the modified lizzie, I got the first game shown analyzed.
The graph is smooth throughout.
It can be an extreme drawing for a moment, but it seems to be fixed soon.
![lizzie-sss](https://user-images.githubusercontent.com/63999713/86516846-f41d8500-be5e-11ea-9ceb-84d3276957e7.jpg)

**Comment by kaorahi** [comment]
Though I fixed this issue in #728, the chart of LCB is meaningless actually.

LCB (lower confidence bound of winrate) is only used for comparison among suggested moves on a board situation. It is very pessimistic when the visits are small, and it converges to the estimated winrate as the visits increase. So it balances two criteria of good moves, "high winrate" (promising) and "large visits" (reliable).

Anyway, you don't need to mind LCB unless you are inspecting internal behaviors of engines.

**Comment by hope366** [comment]
Thank you for telling me a lot.
I didn't know what LCB was at all, but it was good that I was able to learn about machine learning, such as UCB and MCTS, with this opportunity.
