### ISSUE TITLE
"mean:~", "stdev:~", remains fixed

### ISSUE THREAD

**Issue by hope366** [featurecat/lizzie#729]
It is a story when the sgf file which has been pre-analyzed is read by lizzie0.7.3.
Above the win rate graph are "mean:~", "stdev:~", "Last move: ~%",
When moved in the state of pondering off, "mean" and "stdev" are fixed while indicating the numerical value of the final phase and do not change at all.

Also, apart from this problem, I don't know "Last move:~%". What does the numbers shown here mean?

**Comment by kaorahi** [comment]
"Last move:~%" is the difference of winrates before/after the last move. ("%" is misleading here.)

**Comment by hope366** [comment]
It's hard to understand what "Last move:~%" is just about, but when I saw your advice, I could understand it very well.
Thank you very much for changing the source code.
