### ISSUE TITLE
Enjoy the background

### ISSUE THREAD

**Issue by hope366** [featurecat/lizzie#733]
When I hide the panels such as the winning percentage graph and the comment column, something blurry is displayed. Is it possible to fix it so that it disappears completely?
You may want to use the main board only while enjoying the beauty of the background.
If you hide all the panels, you can see the background clearly, but the main board moves to the side. I want the main board to be in the center display.

**Comment by kaorahi** [comment]
Blurred regions are not updated in various cases since the corresponding checks were simply deleted in #441 (abd001a). As a workaround, you can force Lizzie to update them by changing the window size.

**Comment by hope366** [comment]
I can't find any item about changing the window size in config.txt. Does that mean holding the edge of the window with the mouse to resize it?

**Comment by kaorahi** [comment]
yes :)

**Comment by hope366** [comment]
Thank you
