### ISSUE TITLE
About the display of the error dialog when the engine start fails

### ISSUE THREAD

**Issue by hope366** [featurecat/lizzie#756]
[Show error dialog for typical engine troubles](https://github.com/featurecat/lizzie/pull/747)
By applying this, an error dialog will be displayed if the engine fails to start, but not in all cases.
I was able to see this error dialog in the following cases:
* If the folder where the engine is located does not exist in the Lizzie folder
* If "config.txt" is not in the Lizzie folder

Of course, these can happen, but in my experience, the most common cases of engine start failure are:
* If the weight file required to start the engine is not in the Lizzie folder
* If the syntax of the engine command is incorrect
* If the contents of the KataGo configuration file are incomplete
* If you have specified the CUDA version of KataGo for the engine, but the environment required to run it is not in place.

Is it possible to fix it so that an error dialog is displayed even in such a case?

**Comment by kaorahi** [comment]
New commits are added to #747.
