### ISSUE TITLE
Version display still 0.72

### ISSUE THREAD

**Issue by simonguoxm** [featurecat/lizzie#761]
I downloaded the Ver 0.7.3, but in Setting -- About, it still shows 0.7.2.

![Clipboard01](https://user-images.githubusercontent.com/4695131/94353657-2d6a2900-0039-11eb-8452-12370bbd9321.jpg)

**Comment by hope366** [comment]
If you compile using [bump version to 0.7.3](https://github.com/featurecat/lizzie/pull/720), the version information will be "0.7.3", If this is difficult ...
Lizzie-v0.7.3 with various improvements can be found [here](https://github.com/hope366/Lizzie-improvements/releases/tag/v1.2)
It also includes a fix to "0.7.3" in the version information.
Please use it if you like.

**Comment by featurecat** [comment]
![image](https://user-images.githubusercontent.com/10515890/94576690-9f15c300-0243-11eb-9939-83259d32563f.png)
Version is now fixed, thank you!
