### ISSUE TITLE
Patched 0.7.3

### ISSUE THREAD

**Issue by kaorahi** [featurecat/lizzie#762]
As we have 30 unmerged pull requests now, I merged almost all of them into my unofficial branch "patched_0.7.3" for convenience.

https://github.com/kaorahi/lizzie/tree/patched_0.7.3

* Fixed many bugs.
* Much improved diagnoses of engine troubles. (#677, #747, #759)
* Added new features by @yzyray and @TFiFiE.
  * #650 on subboard...
    * mouse hover to stop flicker
    * mouse wheel to change variation length
    * left/right click to show nth variation
  * #656 grayscale territory (toggled by Shift+Period key)

I cannot offer its binary by myself since I have no Windows machine.

Excluded PRs

* #651 (sound): It has sound files whose origin and license are unknown.
* #682 (handicap): #737 reverts the problematic feature of free handicap.
* #663 (dialog), #664 (println): They seem to be duplicated in #696.
* #696 (comment): This PR...
  * includes unrelated commits.
  * conflicts with other commits.
  * changes UI layouts as a side effect.
  * ignores the menu View > Panel > Comment.

**Comment by featurecat** [comment]
Thank you very much! That must have been a lot of work. I will merge this later today once I review the changes.

**Comment by kaorahi** [comment]
Congrats to 0.7.4 :)

I'm happy to close this issue so quickly.
