### ISSUE TITLE
0.7.4 can not see handicap stone after sgf loaded

### ISSUE THREAD

**Issue by tonypttin** [featurecat/lizzie#765]
lizzie 0.7.4 can not see handicap stone after sgf loaded, the analyze value will be showed on the handicap stone, have no problem with 0.7.3

0.7.4
![handicap](https://user-images.githubusercontent.com/33517405/94692725-7259cc80-0365-11eb-9fc6-248d53e2074b.png)

0.7.3
![handicap 0 7 3](https://user-images.githubusercontent.com/33517405/94693193-fdd35d80-0365-11eb-8092-bbdb251e5cf5.png)

**Comment by kaorahi** [comment]
Thanks for the report. I fixed this in #766.

**Comment by tonypttin** [comment]
Thanks for your work.
