### ISSUE TITLE
Can't open lizzie after the first time

### ISSUE THREAD

**Issue by eladzipper96** [featurecat/lizzie#77]
For the first time im running lizzie everything works just fine, but after i exit it and try to open it again nothing happands.

And an idie that doesn't have anything to do with it is maybe in the next version it will be possible to go back and forth to the SGF file, like if im trying other move to see what happands i can't go back and i need to reload the SGF file.

**Comment by dfannius** [comment]
1) Try removing leelaz_opencl_tuning and running again. I had to do this sometimes back when I was running the release, and at some point when I started building from master I stopped having to, so I never looked into it. Hopefully it will be better in the next release.

2) This was implemented in pull request #60 and will be in the 0.4 release.
