### ISSUE TITLE
Stale leelaz data displayed

### ISSUE THREAD

**Issue by dfannius** [featurecat/lizzie#78]
The following problem is made much more obvious by the way I personally use Lizzie: I have a local hack to always display winning percentages from Black's point of view, and my Leela Zero is a little laggy because I'm running it via `ssh` on a remote machine with a graphics card.

When `Board.place` is called, some information (like the new state of the board, and the current player) is updated immediately and rendered correspondingly, but we may still be waiting for the result of an old Leela Zero call to be coming in. `BoardRenderer` can then read an obsolete `bestMoves` list that no longer corresponds to the current board, and try to display it anyway. (In my situation, this causes old displays of, say, a winrate of 47% to be displayed as 53% for an instant before disappearing, since the current player has already been updated.)

I'm not certain what the best way to address this is. Maybe `Leelaz.playMove` could do something to make sure it doesn't try to parse old ponder output. The leelaz ponder output by itself doesn't seem to have enough information to identify what move produced it; otherwise we could identify and drop obsolete ponder output when we receive it.

**Comment by featurecat** [comment]
I'll fix this for the next version. with many thousands of playouts it can be pretty annoying.

**Comment by dfannius** [comment]
This is (or is at least related to) item 1 on [this checklist of issues](https://github.com/featurecat/lizzie/issues/64#issuecomment-382288884). I'm happy to dig back into it but would appreciate thoughts on solutions.

I feel like the "real" solution is to have a unique ID associated with each Leela Zero request and then receive the same ID back every time Leela Zero produces more ponder output, but that's probably too annoying (on the Leela Zero side, at least).

Another possibility, though it's a bit of a hack, is to send Leela Zero some fake innocuous command just before every time we want to start pondering a new position, like asking it for its version; then we know not to start looking at ponder responses again until we get the response to that dummy command. If that is deemed acceptable I'll probably just start with that.

**Comment by featurecat** [comment]
I feel like your hack. let's just do that :P
