### ISSUE TITLE
AMD OpenCL

### ISSUE THREAD

**Issue by roy7** [featurecat/lizzie#81]
Was helping someone set up Lizzie. They followed instructions but clinfo couldn't find any platforms. They googled around and problem was fixed with `sudo apt install mesa-opencl-icd` from https://askubuntu.com/questions/884483/how-to-get-opencl-to-work-on-an-amd-gpu-with-ubuntu-16-04. Maybe worth noting in the instructions for AMD users they might need to use that opencl instead? This was on Neon KDE Linux.

But of course it doesn't end up being so simple, since LeelaZ ends up segfaulting with this stack trace:

https://pastebin.com/W2SCFa05

**Comment by featurecat** [comment]
oh no :/ it was verified that Leela zero Normally runs fine? we should get input from other amd users.

**Comment by roy7** [comment]
I think his crashing is an OpenCL issue not related to Leela. But needing the mesa-opencl did seem relevant so I wanted to share that with you. :)
