### ISSUE TITLE
Multiple rings

### ISSUE THREAD

**Issue by TFiFiE** [featurecat/lizzie#84]
There is currently a red ring around the most visited child. Maybe also have a blue one for the best-scoring one and make it purple when they're the same. I also think they could be a bit thicker.

**Comment by featurecat** [comment]
what if we gave them a special color besides green?

**Comment by TFiFiE** [comment]
That's also possible, but you might want to start thinking about making all those colors configurable, including those on the green-to-red spectrum, because they are especially notorious from a colorblind perspective.

**Comment by dfannius** [comment]
Note that in master there's also a black or white ring showing the next move if there is one, so we have to be extra careful about clutter. (My personal opinion is that the current best scoring move is easy enough to find by eye and doesn't need additional calling out.)

**Comment by TFiFiE** [comment]
New idea: If the most visited child is also the best-scoring one, give it a fully blue color. Otherwise make it cyan and give the best-scoring one a blue ring. This is only two more colors and is also better from a theoretical point of view, because the best-scoring child won't then lose the visual cue indicating how far it's behind in terms of visits.

**Comment by featurecat** [comment]
IIRC, Leela Zero often abandons nodes with seemingly higher winrates than the principal variation, leaving them mostly unexplored. Possibly it's because it found a good refutation and stopped searching? But the winrate doesn't really get updated. Would this be an issue?

**Comment by dfannius** [comment]
Yeah, I don't really understand this behavior of LZ and I would like to. It's not really obvious to me what it means when LZ has a node with a better winrate than some others but it is not exploring it as much, and I'm a little reluctant to call out "this looks like the best option but LZ is declining to explore it" moves.

In minimax or alpha-beta, if you find a refutation, the value gets propagated up the tree appropriately and you don't get a situation where the eval that you're publishing doesn't match what you really think of the move. So I'm a little confused here.

**Comment by featurecat** [comment]
Apparently the actual winrate displayed by LeelaZ is an averaged value of some sort of its children nodes. I don't know the logic behind that vs the alpha-beta style. Roy7 has a fork that probably behaves more like alpha-beta: https://github.com/gcp/leela-zero/pull/883. It might be stronger, too, but it's been a pull request for a long time. It probably would fix the winrate problem.

**Comment by featurecat** [comment]
roy7 do you have any idea when+if your branch will get merged?

**Comment by roy7** [comment]
I think @gcp wanted someone to do a time based test but I can't do that myself since my server is always busy running bots and the speed in a given amount of time wouldn't be steady. Still though, it only adds a test at the end of search which is fast. So I don't think even time is going to show anything different, but it's worth doing at least once to be certain.
