### ISSUE TITLE
Autogtp / LZ training support

### ISSUE THREAD

**Issue by ryouiki** [featurecat/lizzie#85]
Having a good network weight is a essential part of Lizzie, and it relies on Leelazero's training process.

Though, Lizzie is so popular in asian go/baduk communities recently, most of them have no idea where 'network' file comes from.
I guess even 5% of Lizzie users running autogtp, would be a good gain to LZ project.

I suggest,

1. Include autogtp inside release .zip and guide how to run it and to contribute LZ project.
2. Show autogtp output (selfplay/match) visually
3. Notify if we have new best net, and let user to choose to refresh current 'network'.

**Comment by hydrogenpi** [comment]
any action on this?

**Comment by featurecat** [comment]
sounds good. I had no idea we were very popular in Asian communities :) could you provide me a link to one?

1) yes
2) sure
3) yeah.. that was going to make it into 0.3 but it's been pretty delayed. it'll happen as well as much more :)

**Comment by featurecat** [comment]
No, have you ever enjoyed being nagged about something?

**Comment by hydrogenpi** [comment]
what about a scoreboard showing which users have top donated gpu time?

**Comment by featurecat** [comment]
That's best directed towards gcp

**Comment by ryouiki** [comment]
@featurecat For Chinese community, aerisnju may know better.
For Korean communities, asking like 'how to get lizzie', 'i cannot run lizzie' posted everyday, though one of them made a youtube video to instruct how to run. https://youtu.be/uriNNyu6q2I
One of top amature (byflash on foxserver, ouyaouya on tygem) said, "Thanks for guiding me to run Lizzie. After reviewing game with it, I realized how I've been poor at go."
http://gall.dcinside.com/board/view/?id=baduk&no=432645

**Comment by featurecat** [comment]
Thanks for sharing, it's so interesting to hear about :)

**Comment by afalturki** [comment]
@dfannius Personally, I think it's best that the default behavior is to auto-update network weights but that an option is given to disable it. Most people I think would like to be on the latest strongest network and might not have the know-how or patience to manually download new networks.

**Comment by featurecat** [comment]
FYI I probably won't add auto updating for 0.4 unless someone makes a PR for it this weekend. I was going to tackle it when I added support to play against any network.

**Comment by dfannius** [comment]
@afalturki I don't mind auto-update being the default. I agree that most people will probably want it, and it makes more sense to require extra work to turn it off rather than require extra work to turn it on.

**Comment by OlivierBlanvillain** [comment]
I think this is out of the scope of Lizzie. In my opinion the main goal of this program is to review and study games, not train the network which has orthogonal requirements (good hardware, no UI needed). I will close this for now.
