### ISSUE TITLE
Packaging/run instructions

### ISSUE THREAD

**Issue by Ka-zam** [featurecat/lizzie#86]
Hi,

I have zero experience w/ java but managed to install maven and generate the jar files. Great. Don't seem to run though:

    MS-7A70:~/src/lizzie$ java -cp target/lizzie-1.3.jar wagner.stephanie.lizzie.Lizzie 
    Error: Unable to initialize main class wagner.stephanie.lizzie.Lizzie
    Caused by: java.lang.NoClassDefFoundError: org/json/JSONException
    MS-7A70:~/src/lizzie$ 

This is on Ubuntu 18.04 using openjdk-9. So I'm guessing it's some sort of dependency that I don't have. 

How can I add this, or better yet, package the whole thing into a release. I have patched my version of leelaz with your UCTSearch.cpp so that shouldn't be a problem. 

Thx!

**Comment by featurecat** [comment]
I use intellij to compile. on Ubuntu 17.10 w oracle jdk. personally I don't use javac by command-line. could you try intellij, possibly? otherwise i can try to come up with a javac method when I have time.

**Comment by dfannius** [comment]
I use `mvn pacakge` to build and `java -jar target/lizzie-1.3-shaded.jar' (like @bittsitt) to run. The JSON library is present, but only the "shaded" jar has it packaged in, and I don't know enough about the Java ecosystem to tell Java where to find it otherwise.

**Comment by dfannius** [comment]
@Ka-zam Try deleting `leelaz_opencl_tuning` and running Lizzie again. For a while I was having an issue where I needed to do that to run Lizzie. I haven't had a problem recently, but it's worth trying.

**Comment by Ka-zam** [comment]
@dfannius 
Tried that, didn't work. I traced out the commands though and it turns out next branch segfaults on "time_left b 0 0" command. So that's a bug in leelaz and I will raise an issue there.

**Comment by Ka-zam** [comment]
This has been fixed now but not pulled in. If you still want it to work you need to implement this fix:
https://github.com/gcp/leela-zero/issues/1201
