### ISSUE TITLE
When Lizzie allows LZ to ponder for 50k+ playouts, once the move is played, Lizzie doesn't show the pondering results of the next move

### ISSUE THREAD

**Issue by jillybob** [featurecat/lizzie#88]
I have noticed this mostly in the opening. When I have a total of about 70+ playouts, once I play the first move, LZ does not load the winrates anymore. Here is an example:

Step 1: Let LZ ponder until high number of playouts

https://i.imgur.com/nELhFaq.jpg

Step 2: play the #1 recommended move:

https://i.imgur.com/nELhFaq.jpg

Blank board. Now if I play a second move.
https://i.imgur.com/Hejt6to.jpg
blank board again, it is like LZ stopped working

If I now press spacebar, the playouts start again.

**Comment by featurecat** [comment]
I think this is a bug with leelaz: it can take Leelaz a bit more time to move to next move after the tree gets large. It might be fizable but I'm not sure.

**Comment by hydrogenpi** [comment]
![image](https://user-images.githubusercontent.com/35181396/38769787-40abe34e-3fbd-11e8-95cf-07278b481cc0.png)

**Comment by hydrogenpi** [comment]
Please fix this bug for tomorrow mornings match I'm trying to follow along

**Comment by featurecat** [comment]
You only have to wait a few seconds and it should update the playout info. I know it's annoying but I don't see an easy way of fixing it currently.

**Comment by featurecat** [comment]
oh, that bug. same thing. not sure. help is wanted
