### ISSUE TITLE
Shadows don't display

### ISSUE THREAD

**Issue by pondturtle** [featurecat/lizzie#89]
Shadows don't display for me no matter what (yes they are turned on in config). LZ is working as both GPUs have 100% load

**Comment by pondturtle** [comment]
Please include the fact, that Lizzie needs and contains modified version of LZ into readme. Will prevent a lot of trouble for many I suspect

**Comment by featurecat** [comment]
are you still having issues with shadows?

that fact *is* in the Readme that comes with Lizzie as are other instructions

**Comment by pondturtle** [comment]
No. It works perfectly now. I had my own compile of LZ and that was the problem. 

Yes it is indeed there. Very easy to miss. had to re-read. I apologize. Thank you for awesome app btw.

**Comment by featurecat** [comment]
so glad it works! thanks :)
