### ISSUE TITLE
Option to customize threads

### ISSUE THREAD

**Issue by ayssia** [featurecat/lizzie#9]
Currently lizzie calls leelaz.exe with "-t 2" command, is it possible to add a config file to customize this?

**Comment by MartinDevelopment** [comment]
This really needs to be added, on cpu only with 2 threads using this program is useless.

**Comment by CamWagner** [comment]
I see, I will add a config file for the next release. I'll let users customize the leelaz commandline arguments. Are there any other options that would be useful to put in it?

**Comment by qwiffs** [comment]
For multiple GPUs....

**Comment by featurecat** [comment]
Added to 0.3 release
