### ISSUE TITLE
Add rotating board co-ordinates.

### ISSUE THREAD

**Issue by jillybob** [featurecat/lizzie#95]
In most Western board games, board co-ordinates are [A19 top left](https://i.imgur.com/7h2l9rp.png)  However in Lizzie, [A1 is top left](https://i.imgur.com/YhykT6X.jpg). Can it be made so that Pressing C toggles between A19 top left, A1 top left and blank (no co-ordinates)?

**Comment by featurecat** [comment]
Yes, this is fixed in development version already. Already fixed for next release.
